---
title: "R ile Çoklu Regresyon Analizi Ödev Soruları ve Cevapları"
author: "Dr. Hüseyin Utku Demir"
date: 2020-12-01T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
type: book
weight: 80
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>
<link href="/rmarkdown-libs/pagedtable/css/pagedtable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/pagedtable/js/pagedtable.js"></script>


<p>Bu bölümde bazı örnek soruları cevap veriyoruz.</p>
<!--more-->
<div id="ödev" class="section level2">
<h2>Ödev</h2>
<div id="wooldridge-bölüm-soruları" class="section level3">
<h3>Wooldridge Bölüm Soruları</h3>
<ol style="list-style-type: decimal">
<li>4137 üniversite öğrencisi üzerinde GPA2’deki verileri kullanarak, en küçük kareler (OLS) tarafından aşağıdaki denklem tahmin edilmiştir:</li>
</ol>
<p><span class="math display">\[
üniversite.not.ortalaması=1.392 - 0.0135 lmsyd + 0.00148sat
\]</span></p>
<p>lmsyd, öğrencilerin lise mezuniyet sınıflarındaki yüzdelik dilimi göstermektedir. Örneğin, lmsyd=5, sınıfın ilk %5’inde olduğu anlamına gelir. sat, öğrenci başarı testindeki birleştirilmiş matematik ve sözel puanlardır.</p>
<ol style="list-style-type: lower-alpha">
<li>lmsyd katsayısının negatif olması neden mantıklıdır?</li>
<li>lmsyd = 20 ve sat = 1.050 olduğunda tahmini üniversite not ortalaması nedir?</li>
<li>Diyelim ki iki lise mezunu, A ve B, liseden aynı yüzdelik dilimde mezun oldular.
Ancak Öğrenci A’nın SAT puanı 140 puan daha yüksek. (aynı zamanda yaklaşık bir standart sapmaya sahip). Bu iki öğrenci için üniversite not ortalamasında tahmini fark nedir? Bu fark büyük bir fark mı?</li>
<li>lmsyd sabit tutulduğunda, SAT puanlarındaki hangi fark, tahmini üniversite not ortalaması farkına 0,50 veya bir notun yarısı kadar farka yol açar? Cevabınıza yorum yapın.</li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>Aşağıdaki model, Biddle ve Hamermesh (1990) tarafından uyumak ve çalışmak için harcanan zaman arasındaki dengeyi incelemek ve uykuyu etkileyen diğer faktörleri incelemek için kullanılan çoklu regresyon modelinin basitleştirilmiş bir versiyonudur:</li>
</ol>
<p><span class="math display">\[
uyku=\beta_0 + \beta_1 toplam.iş+ \beta_2 eğitim + \beta3 yaş + u
\]</span></p>
<p>uyku ve toplam iş dakikayla, eğitim ve yaş yılla hesaplanmıştır.</p>
<ol style="list-style-type: lower-alpha">
<li>Yetişkinler iş için uykuyu takas ediyorsa, <span class="math inline">\(\beta_1\)</span>’in işareti nedir?</li>
<li><span class="math inline">\(\beta_2\)</span> ve <span class="math inline">\(\beta_3\)</span>’ün hangi işaretleri olacağını düşünüyorsunuz?</li>
<li>SLEEP75’teki verileri kullanarak, tahmin edilen denklem şu şekildedir:</li>
</ol>
<p><span class="math display">\[
uyku=3,638.25 - 0.148 toplam.iş - 11.13 eğitim + 2.20 yaş
\]</span>
<span class="math inline">\(n=706\)</span> ve <span class="math inline">\(R^2=0.113\)</span></p>
<p>Birisi haftada beş saat daha fazla çalışırsa, uykunun kaç dakika düşeceği tahmin edilir?
bu büyük bir takas mı?
d.Eğitim üzerindeki tahmini katsayının üzerindeki işaretini ve büyüklüğünü tartışın.
e.Uykudaki çeşitliliğin çoğunu toplam iş, eğitim ve yaşın açıkladığını söyleyebilir misiniz? Uyuyarak geçirilen süreyi başka hangi faktörler etkileyebilir? Bunların toplam iş ile ilişkili olması muhtemel mi?</p>
<ol start="3" style="list-style-type: decimal">
<li>Üniversite not ortalamasını çeşitli etkinliklerde harcanan zamanla ilişkilendiren bir çalışma yapmak istiyorsunuz, birkaç öğrenciye bir anket dağıttınız. Öğrencilere her hafta dört aktivitede kaç saat geçirdikleri sordunuz: ders çalışmak, uyumak, bir işte çalışmak ve boş zaman. Herhangi bir aktivite dört kategoriden birine konur, böylece her öğrenci için dört aktivitedeki saatlerin toplamı 168 olmalıdır.</li>
</ol>
<p><span class="math display">\[
not.ortalaması=\beta_0 + \beta_1 ders.çalışma+ \beta_2 uyumak + \beta3 iş.çalışma + \beta4 boş.zaman + u
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(\beta_1\)</span>’i yorumladığınızda çalışmayı değiştirirken uykuyu, işi ve boş zamanları sabit tutmak mantıklı mı?</li>
<li>Bu modelin neden MLR.3 Varsayımını ihlal ettiğini açıklayın.</li>
<li>Modeli, parametrelerinin faydalı bir yoruma sahip olması için nasıl yeniden formüle edebilirsiniz ve varsayım MLR.3’ü ihlal edilmez?</li>
</ol>
</div>
<div id="cevaplar" class="section level3">
<h3>Cevaplar</h3>
<ol style="list-style-type: decimal">
<li></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>lmsyd, ne kadar küçükse öğrencinin lisedeki durumu o kadar düşük olacak şekilde tanımlanır. Diğer her şey eşittir, öğrencinin lisedeki durumu ne kadar kötüyse, beklenen üniversite not ortalaması o kadar düşük olur.</p></li>
<li><p>Sadece bu değerleri denkleme yerleştirin</p></li>
</ol>
<p><span class="math display">\[
üniversite.not.ortalaması=1.392 - 0.0135 \cdot 20 + 0.00148 \cdot 1050 = 2.676
\]</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>A ve B arasındaki fark, sat katsayısının 140 katıdır, çünkü lmsyd her iki öğrenci için de aynıdır. Dolayısıyla A’nın <span class="math inline">\(0.00148 \cdot (140)= 0.207\)</span> daha yüksek bir puana sahip olduğu tahmin edilmektedir.</p></li>
<li><p>lmsy sabit olduğunda, <span class="math inline">\(\Delta universite.not.ortalaması = 0.00148 \cdot \Delta sat\)</span>. Bu durumda <span class="math inline">\(0.5 = 0.00148 \cdot \Delta sat\)</span> veya <span class="math inline">\(\Delta sat= \frac{0.00148}{0.5}\)</span> olacak şekilde bulmak istiyoruz. <span class="math inline">\(\Delta sat= 338\)</span></p></li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Diğer herşey eşit olduğunda, yetişkinler uykuyu iş için tercih ediyorsa, daha fazla iş daha az uyku anlamına gelir, bu yüzden <span class="math inline">\(\beta_1&lt;0\)</span> olur.</li>
<li><span class="math inline">\(\beta_2\)</span> ve <span class="math inline">\(\beta_3\)</span> işaretleri kişiden kişiye göre değişir. Vereceğiniz örneklere göre bu katsayıların işaretleri eksi veya artı olabilir. Bu yüzden bu çalışma için herhangi bir beklenti içinde olamayız. Kimi yaş ilerledikçe uykunun azaldığını söyler, kimi arttığını ve bunu gerekçeleriyle örneklendirebilir. Aynı durum eğitim ile ilgili olarak da tartışılabilir.</li>
<li>Uyku ve toplam iş dakika ile ölçüldüğünden 5 saati dakikaya çevirmeniz gerekir (<span class="math inline">\(5 \cdot 60= 300\)</span>). 300 dakikayı formülde yerine koyarsak <span class="math inline">\(0.148 \cdot 300= 44.4\)</span> dakika. Uyku bir hafta içinde 44.4 dakika düşer bunun çok fazla bir düşüş olduğunu söyleyemeyiz.
d.Daha fazla eğitim, daha az tahmini uyku süresi anlamına gelir, ancak etkisi oldukça küçüktür. Üniversite ile lise arasındaki farkın dört yıl olduğunu varsayarsak, modelimiz diğer değişkenler sabit olduğunda üniversite mezunu olan kişinin lise mezunu olan bir kişiye göre haftada yaklaşık 45 dakika (11.13 ) daha az uyuduğunu tahmin ediyor.</li>
<li>Şaşırtıcı olmayan bir şekilde, üç açıklayıcı değişken, katılımcıların yalnızca yaklaşık %11.3’ünü (<span class="math inline">\(R^2\)</span>) açıklamaktadır. Hata terimindeki önemli bir faktör genel sağlıktır. Bir diğeri ise medeni durum ve kişinin çocuğu olup olmadığıdır. Sağlık, medeni durum ve çocukların sayısı ve yaşları genellikle toplam iş süresiyle ile ilişkilidir.</li>
</ol>
<ol start="3" style="list-style-type: decimal">
<li></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Hayır. Tanım olarak, çalışma + uyku + iş + boş zaman = 168. Bu nedenle, çalışmayı değiştirirsek, toplamın hala 168 olması için diğer kategorilerden en az birini değiştirmeliyiz.</li>
<li><ol style="list-style-type: lower-alpha">
<li>kısmından, mesela iş değişkenini diğer bağımsız değişkenlerin mükemmel bir lineer fonksiyonu olarak yazabiliriz: <span class="math inline">\(iş = 168 - uyku - ders - boş zaman\)</span> Bu her gözlem için geçerlidir, dolayısıyla MLR.3 ihlal edilmiştir.</li>
</ol></li>
<li>Bağımsız değişkenlerden birini modelden çıkarın, mesela boş zaman değişkenini çıkarın:</li>
</ol>
<p><span class="math display">\[
not.ortalaması=\beta_0 + \beta_1 ders.çalışma+ \beta_2 uyumak + \beta3 iş.çalışma + u
\]</span></p>
<p>Bu durumda, <span class="math inline">\(\beta_1\)</span> ders çalışma bir saat arttığında, uyku, iş ve <span class="math inline">\(u\)</span> sabit tutulduğu zaman not ortalamasındaki değişiklik olarak yorumlanır. Uykuyu ve çalışmayı sabit tutuyoruz, ancak ders çalışmayı bir saat artırıyorsak, boş zamanı bir saat azaltıyor olmalıyız. Diğer eğim parametreleri de benzer bir yoruma sahiptir.</p>
</div>
<div id="wooldridge-veri-sorusu" class="section level3">
<h3>Wooldridge Veri Sorusu</h3>
<ol style="list-style-type: decimal">
<li>Sağlık görevlilerinin ilgilendiği sorunlardan biri, hamilelik sırasında sigara içmenin bebek sağlığı üzerindeki etkilerini belirlemektir. Bebek sağlığının bir ölçüsü doğum ağırlığıdır; çok düşük doğum ağırlığı, bebeği çeşitli hastalıklara yakalanma riskine sokabilir. Doğum ağırlığını etkileyen sigara içimi dışındaki faktörlerin sigara ile ilişkili olması muhtemel olduğundan, bu faktörleri dikkate almalıyız. Örneğin, daha yüksek gelir genellikle daha iyi doğum öncesi bakıma erişimin yanı sıra anne için daha iyi beslenme ile sonuçlanır. Bunu tanımlayan bir denklem</li>
</ol>
<p><span class="math display">\[
bwght=\beta_0 + \beta_1 cigs+ \beta_2 faminc + u
\]</span></p>
<p>Wooldridge BWGHT data setini kullanın.</p>
<ol style="list-style-type: lower-alpha">
<li>Modelin değişkenlerinin ne anlama geldiğini yazın.</li>
<li>Modeli tahmin etmeden, <span class="math inline">\(\beta_2\)</span> için en olası işaret nedir?</li>
<li>cigs ve faminc’in ilişkili olabileceğini düşünüyor musunuz? Korelasyonun pozitif mi negatif mi olabilir?</li>
<li>Şimdi, BWGHT’deki verileri kullanarak, faminc olan ve olmayan denklemi tahmin edin. sonuçları rapor edin. örnek boyutu ve R-kare dahil olmak üzere denklem formunda yazın. Sonuçlarınızı tartışın, faminc eklemenin cigs’in bwght üzerindeki tahmini etkisini önemli ölçüde değiştirip değiştirmediğine odaklanın.</li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>Bu soruyu yanıtlamak için DISCRIM verilerini kullanın. Bunlar, New Jersey ve Pennsylvania’daki fast-food restoranlarındaki çeşitli ürünlerin fiyatlarına ilişkin posta kodu düzeyinde veriler ve posta kodu popülasyonunun özellikleridir. Buradaki fikir, fast-food restoranlarının siyahların daha yoğun olduğu bölgelerde daha yüksek fiyatlar talep edip etmediğini öğrenmektir. Modelimiz</li>
</ol>
<p><span class="math display">\[
psoda=\beta_0 + \beta_1 prpblck+ \beta_2 income + u
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Modelin değişkenlerinin ve prppov değişkeninin ne anlama geldiğini yazın.</li>
<li>ortalama prpblck ve income değerlerini standart sapmalarıyla birlikte bulun. prpblck ve income ölçü birimleri nelerdir?</li>
<li>Bu modeli OLS ile tahmin edin ve sonuçları, n ve R-kare dahil olmak üzere denklem biçiminde rapor edin. (Tahminleri raporlarken bilimsel gösterimi kullanmayın.) prpblck üzerindeki katsayıyı yorumlayın. Sizce ekonomik olarak büyük mü?</li>
<li>Basit regresyon
<span class="math display">\[
psoda=\beta_0 + \beta_1 prpblck + u
\]</span>
modelini kullanarak basit regresyonu tahmin edin. Ayrımcılık etkisi income’ı kontrol ettiğiniz modele göre daha mı büyük daha mı küçük?</li>
<li>Gelire göre sabit fiyat esnekliğine sahip bir model daha uygun olabilir.
<span class="math display">\[
log(psoda)=\beta_0 + \beta_1 prpblck+ \beta_2 log(income) + u
\]</span></li>
</ol>
<p>Modelin tahmin edin ve tahminlerini raporlayın.
Eğer prpblck .20 (20 yüzde puanı) artarsa, psoda’nın tahmini yüzde değişimi ne olur? (İpucu: Cevap 2.xx’dir, burada “xx”i doldurursunuz)</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Şimdi prppov değişkenini kısım e’deki regresyona ekleyin. <span class="math inline">\(\beta_1\)</span>’e ne olur?</li>
<li>log(income) ve prppov arasındaki ilişkiyi bulun. Kabaca beklediğiniz gibi mi?</li>
<li>Aşağıdaki ifadeyi değerlendirin: “log(income) ve prppov çok yüksek oranda ilişkili olduğundan, aynı regresyonda olmalarına gerek yoktur.”</li>
</ol>
<ol start="3" style="list-style-type: decimal">
<li>Tek ebeveynli hanelerin öğrencilerin matematik performansı üzerindeki etkilerini incelemek için MEAPSINGLE’daki verileri kullanın. Bu veriler, 2000 yılı için güneydoğu Michigan’daki okulların bir alt kümesi içindir. Sosyo-ekonomik değişkenler, Posta kodu düzeyinde elde edilir (burada Posta kodu okulların posta adreslerine göre atanır).</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>math4, pctsgle, lmedinc ve free değişkenlerinin ne anlama geldiklerini yazın.</li>
<li>Math4’ün basit regresyonunu pctsgle üzerinde çalıştırın ve sonuçları normal biçimde rapor edin. Eğim katsayısını yorumlayın. Tek ebeveynliğin etkisi büyük mü yoksa küçük mü görünüyor?</li>
<li>lmedinc ve free değişkenlerini denkleme ekleyin. pctsgle üzerindeki katsayıya ne olur?</li>
<li>lmedinc ve free arasındaki örnek korelasyonu bulun. Beklediğiniz işaret var mı?</li>
<li>Imedinc ve free arasındaki önemli korelasyon varsa. Tek ebeveynliğin öğrenci performansı üzerindeki nedensel etkisini daha iyi tahmin etmek için bir tanesini regresyondan analizinden çıkarmanız gerektiği anlamına gelir mi? Açıklayın.</li>
<li>Görünen açıklayıcı değişkenlerin her biri için varyans enflasyon faktörlerini (VIF’ler) bulun. Hangi değişken en büyük VIF’ye sahiptir? Bu bilgi, tek ebeveynliğin matematik performansı üzerindeki nedensel etkisini incelemek için kullanacağınız modeli etkiler mi?</li>
</ol>
</div>
<div id="wooldridge-veri-soruları-cevapları" class="section level3">
<h3>Wooldridge Veri Soruları Cevapları</h3>
<ol style="list-style-type: decimal">
<li></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>library(wooldridge)
library(rmarkdown)
data(&quot;bwght&quot;)
head(bwght)</code></pre>
<pre><code>##   faminc cigtax cigprice bwght fatheduc motheduc parity male white cigs
## 1   13.5   16.5    122.3   109       12       12      1    1     1    0
## 2    7.5   16.5    122.3   133        6       12      2    1     0    0
## 3    0.5   16.5    122.3   129       NA       12      2    0     0    0
## 4   15.5   16.5    122.3   126       12       12      2    1     0    0
## 5   27.5   16.5    122.3   134       14       12      2    1     1    0
## 6    7.5   16.5    122.3   118       12       14      6    1     0    0
##     lbwght bwghtlbs packs    lfaminc
## 1 4.691348   6.8125     0  2.6026897
## 2 4.890349   8.3125     0  2.0149031
## 3 4.859812   8.0625     0 -0.6931472
## 4 4.836282   7.8750     0  2.7408400
## 5 4.897840   8.3750     0  3.3141861
## 6 4.770685   7.3750     0  2.0149031</code></pre>
<pre class="r"><code>help(bwght)</code></pre>
<p>kullanacağımız değişkenlerin tanımları</p>
<p>-faminc: 1988 family income, $1000s, 1988 aile geliri
-cigs: cigs smked per day while preg, hamileyken içilen günlük sigara sayısı
-bwght: birth weight, ounces, doğum ağırlığı, ons</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Bir yandan, gelirdeki bir artış genellikle gıda tüketimini arttırır ve sigara ile aile geliri arasında pozitif bir ilişki olabilir. Öte yandan, daha fazla eğitime sahip ailelerin aile gelirleri de daha yüksektir ve daha fazla eğitim ile sigara içme arasında olumsuz bir ilişki vardır.</li>
<li>Sigara ve faminc arasındaki örnek korelasyonu yaklaşık -0.173’tür ve negatif bir korelasyona işaret eder.</li>
<li></li>
</ol>
<pre class="r"><code>ilkreg &lt;- lm(bwght~ cigs,data = bwght)
ikincireg&lt;- lm(bwght~ cigs+faminc,data = bwght)
library(stargazer)</code></pre>
<pre><code>## 
## Please cite as:</code></pre>
<pre><code>##  Hlavac, Marek (2018). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
<pre><code>##  R package version 5.2.2. https://CRAN.R-project.org/package=stargazer</code></pre>
<pre class="r"><code>stargazer(list(ilkreg,ikincireg),type = &quot;text&quot;)</code></pre>
<pre><code>## 
## =====================================================================
##                                    Dependent variable:               
##                     -------------------------------------------------
##                                           bwght                      
##                               (1)                      (2)           
## ---------------------------------------------------------------------
## cigs                       -0.514***                -0.463***        
##                             (0.090)                  (0.092)         
##                                                                      
## faminc                                               0.093***        
##                                                      (0.029)         
##                                                                      
## Constant                   119.772***               116.974***       
##                             (0.572)                  (1.049)         
##                                                                      
## ---------------------------------------------------------------------
## Observations                 1,388                    1,388          
## R2                           0.023                    0.030          
## Adjusted R2                  0.022                    0.028          
## Residual Std. Error    20.129 (df = 1386)       20.063 (df = 1385)   
## F Statistic         32.235*** (df = 1; 1386) 21.274*** (df = 2; 1385)
## =====================================================================
## Note:                                     *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p>Denklem şeklinde rapor</p>
<p><span class="math display">\[
bwght=116.974-0.463 cigs + 0.093faminc
\]</span></p>
<p><span class="math display">\[
bwght=119.772-0.514 cigs
\]</span></p>
<p>Regresyona faminc eklendiğinde sigara içmenin etkisi biraz daha az ama aradaki fark çok büyük değil. Bunun nedeni, cigs ve faminc’in çok ilişkili olmaması ve faminc üzerindeki katsayının pratik olarak küçük olmasıdır. (Faminc değişkeni binlerle ölçülür, yani 1988’de 10.000$ daha fazla gelir, öngörülen doğum ağırlığını yalnızca .93 ons artırır.)</p>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>data(&quot;discrim&quot;)
head(discrim)</code></pre>
<pre><code>##   psoda pfries pentree wagest nmgrs nregs hrsopen  emp psoda2 pfries2 pentree2
## 1  1.12   1.06    1.02   4.25     3     5    16.0 27.5   1.11    1.11     1.05
## 2  1.06   0.91    0.95   4.75     3     3    16.5 21.5   1.05    0.89     0.95
## 3  1.06   0.91    0.98   4.25     3     5    18.0 30.0   1.05    0.94     0.98
## 4  1.12   1.02    1.06   5.00     4     5    16.0 27.5   1.15    1.05     1.05
## 5  1.12     NA    0.49   5.00     3     3    16.0  5.0   1.04    1.01     0.58
## 6  1.06   0.95    1.01   4.25     4     4    15.0 17.5   1.05    0.94     1.00
##   wagest2 nmgrs2 nregs2 hrsopen2 emp2 compown chain density    crmrte state
## 1    5.05      5      5     15.0 27.0       1     3    4030 0.0528866     1
## 2    5.05      4      3     17.5 24.5       0     1    4030 0.0528866     1
## 3    5.05      4      5     17.5 25.0       0     1   11400 0.0360003     1
## 4    5.05      4      5     16.0   NA       0     3    8345 0.0484232     1
## 5    5.05      3      3     16.0 12.0       0     1     720 0.0615890     1
## 6    5.05      3      4     15.0 28.0       0     1    4424 0.0334823     1
##     prpblck    prppov   prpncar hseval nstores income county     lpsoda
## 1 0.1711542 0.0365789 0.0788428 148300       3  44534     18 0.11332869
## 2 0.1711542 0.0365789 0.0788428 148300       3  44534     18 0.05826885
## 3 0.0473602 0.0879072 0.2694298 169200       3  41164     12 0.05826885
## 4 0.0528394 0.0591227 0.1366903 171600       3  50366     10 0.11332869
## 5 0.0344800 0.0254145 0.0738020 249100       1  72287     10 0.11332869
## 6 0.0591327 0.0835001 0.1151341 148000       2  44515     18 0.05826885
##       lpfries  lhseval  lincome ldensity NJ BK KFC RR
## 1  0.05826885 11.90699 10.70401 8.301521  1  0   0  1
## 2 -0.09431065 11.90699 10.70401 8.301521  1  1   0  0
## 3 -0.09431065 12.03884 10.62532 9.341369  1  1   0  0
## 4  0.01980261 12.05292 10.82707 9.029418  1  0   0  1
## 5          NA 12.42561 11.18840 6.579251  1  1   0  0
## 6 -0.05129331 11.90497 10.70358 8.394799  1  1   0  0</code></pre>
<pre class="r"><code>help(discrim)</code></pre>
<p>Gördüğünüz gibi veri setinde bazı değişkenler için bazı gözlemler NA değerine sahip. NA (not available) o gözlem için mevcut değil anlamına geliyor. Örneğin pfries (price of small fries, küçük kızartmanın fiyatı) değişkeninin beşinci gözlemi veri setinde bulunan beşinci restoranının küçük kızartma fiyatını bilmediğimiz anlamı taşıyor. Mevcut olmayan gözlemler analizlerde her zaman sorunlar çıkarır. Bu mevcut olmayan değişkenlerle nasıl başa çıkacağımızı yavaş yavaş öğrenmemiz gerekir.</p>
<p>Modelin değişkenlerinin ve prppov değişkeninin anlamı.</p>
<p>-psoda: price of medium soda, 1st wave, orta sodanın fiyatı.
-prpblck: proportion black, zipcode, restoranın bulunduğu bölgede siyahi oranı
-income: median family income, zipcode, restoranın bulunduğu bölgenin medyan (ortanca) aile geliri.
-prppov: proportion in poverty, zipcode, restoranın bulunduğu bölgede yoksulluk oranı</p>
<ol start="2" style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>mean(discrim$prpblck)</code></pre>
<pre><code>## [1] NA</code></pre>
<pre class="r"><code>sd(discrim$prpblck)</code></pre>
<pre><code>## [1] NA</code></pre>
<pre class="r"><code>mean(discrim$income)</code></pre>
<pre><code>## [1] NA</code></pre>
<pre class="r"><code>sd(discrim$income)</code></pre>
<pre><code>## [1] NA</code></pre>
<p>Bildiğimiz mean ve sd fonksiyonlarını kullanarak ortama ve standart sapma değerlerini bulamadık. Çıkan NA sonucu bize bu değişkenlerin içinde bazı gözlemlerin mevcut olmadığını gösteriyor olabilir. discrim veri setinde 410 gözlem olduğundan her bir gözlemi kontrol edemiyorz ve bu değişkenlerin içinde kaç tane gözlemin mevcut olmadığını çıkaramıyoruz. R bize bu konuda is.na fonksiyonu ile yardımcı oluyor. is.na aslında sorduğumuz ingilizce bir soru ve is na? derken R’a mevcut olmayan gözlem var mı diye soru soruyoruz. R’da bize her bir gözlem için o gözlemin değeri olup olmadığını TRUE (doğru) ve FALSE (yanlış) olarak geri veriyor. Örnek vermek gerekirse konsola is.na(discrim$income) yazarsanız, R income değişkeninin her bir gözlemi için TRUE ve FALSE değerlerini yükler. TRUE o gözlemin mecut olmadığını, FALSE gözlemin olduğunu söylemektedir. Ancak tekrar aynı sorunla karşı karşıya kalırız. 410 gözlem için TRUE ve FALSE değerlerini okumamız ve FALSE olanları toplamamız kaç gözlemin var olmadığını bulmamıza yol açacaktır. sum(is.na(discrim$income)) income değişkenin içindeki var olmayan gözlem sayısını toplayacak ve bize verecektir.</p>
<pre class="r"><code>sum(is.na(discrim$prpblck))</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>sum(is.na(discrim$income))</code></pre>
<pre><code>## [1] 1</code></pre>
<p>Gördüğünüz gibi hem prbblck hem income değişkenlerinin birer gözlemi boş değere sahip. Bu yüzden mean ve sd fonksiyonlarının NA gözlemlerinine sahip olduğunu söylememiz lazım.</p>
<pre class="r"><code>mean(discrim$prpblck,na.rm = TRUE)</code></pre>
<pre><code>## [1] 0.1134864</code></pre>
<pre class="r"><code>sd(discrim$prpblck,na.rm = TRUE)</code></pre>
<pre><code>## [1] 0.1824165</code></pre>
<pre class="r"><code>mean(discrim$income, na.rm = TRUE)</code></pre>
<pre><code>## [1] 47053.78</code></pre>
<pre class="r"><code>sd(discrim$income, na.rm = TRUE)</code></pre>
<pre><code>## [1] 13179.29</code></pre>
<p>fonksiyonun içine yazdığımız na.rm (na remove, çıkar) öevcut olmayan gözlemleri hesaplamadan çıkarmamızı söyler. prbblck değişkeninin ortalaması 0.11, standart sapması 0.18, income değişkeninin ortalaması 47053, standart sapması 13179 olacaktır.</p>
<p>Diyelim ki siz bütün değişkenler için kaç tane gözlemin mevcut olmadığını, kaç tane gözlemin var olduğunu, ortalamasını ve standart sapmasını görmek istiyorsunuz. Bu durumda vtable paketi size yardımcı olacaktır. Aşağıdaki komutu kullanmak için vtable paketini yüklemeniz gerektiğini unutmayın.</p>
<pre class="r"><code>library(vtable)</code></pre>
<pre><code>## Loading required package: kableExtra</code></pre>
<pre class="r"><code>sumtable(discrim, summ=c(&#39;notNA(x)&#39;, &#39;countNA(x)&#39;, &#39;mean(x)&#39;,&#39;sd(x)&#39;),out=&#39;return&#39;)</code></pre>
<pre><code>##    Variable NotNA CountNA       Mean        Sd
## 1     psoda   402       8      1.045     0.089
## 2    pfries   393      17      0.922     0.106
## 3   pentree   398      12      1.322     0.643
## 4    wagest   390      20      4.616     0.347
## 5     nmgrs   404       6       3.42     1.018
## 6     nregs   388      22      3.608     1.244
## 7   hrsopen   410       0     14.439      2.81
## 8       emp   404       6     17.622     9.423
## 9    psoda2   388      22      1.045     0.094
## 10  pfries2   382      28      0.941     0.109
## 11 pentree2   386      24      1.354      0.65
## 12  wagest2   389      21      4.996     0.253
## 13   nmgrs2   404       6      3.484      1.14
## 14   nregs2   388      22      3.608     1.244
## 15 hrsopen2   399      11     14.466     2.752
## 16     emp2   397      13     17.567     8.607
## 17  compown   410       0      0.344     0.476
## 18    chain   410       0      2.117      1.11
## 19  density   409       1   4561.803  5132.408
## 20   crmrte   409       1      0.053     0.047
## 21    state   410       0      1.193     0.395
## 22  prpblck   409       1      0.113     0.182
## 23   prppov   409       1      0.071     0.067
## 24  prpncar   409       1      0.115     0.117
## 25   hseval   409       1 147399.267 56070.468
## 26  nstores   410       0      3.139     1.809
## 27   income   409       1  47053.785 13179.286
## 28   county   410       0     13.659     8.045
## 29   lpsoda   402       8       0.04     0.085
## 30  lpfries   393      17     -0.088     0.115
## 31  lhseval   409       1     11.829     0.389
## 32  lincome   409       1      10.72     0.284
## 33 ldensity   409       1      7.959     0.996
## 34       NJ   410       0      0.807     0.395
## 35       BK   410       0      0.417     0.494
## 36      KFC   410       0      0.195     0.397
## 37       RR   410       0      0.241     0.428</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>discrimreg &lt;- lm(psoda~prpblck+income, data = discrim)
summary(discrimreg)</code></pre>
<pre><code>## 
## Call:
## lm(formula = psoda ~ prpblck + income, data = discrim)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.29401 -0.05242  0.00333  0.04231  0.44322 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 9.563e-01  1.899e-02  50.354  &lt; 2e-16 ***
## prpblck     1.150e-01  2.600e-02   4.423 1.26e-05 ***
## income      1.603e-06  3.618e-07   4.430 1.22e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.08611 on 398 degrees of freedom
##   (9 observations deleted due to missingness)
## Multiple R-squared:  0.06422,    Adjusted R-squared:  0.05952 
## F-statistic: 13.66 on 2 and 398 DF,  p-value: 1.835e-06</code></pre>
<p><span class="math display">\[
psoda=0.956 + 0.115 prpblck+ 0.0000016 income + u
\]</span></p>
<p>Örnek boyutu 399 gözlemdir (398 serbestlik derecesi ve 9 eksik gözlem ile gösterilir) ve ayarlanmış <span class="math inline">\(R^2\)</span> 0.595’tir. prpblck katsayısı, her şey eşit olduğunda, prpblck %10 artarsa, soda fiyatının ekonomik olarak önemli olmayan derecede yaklaşık 1,2 sent artacağını gösterir.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>basitdiscrimreg &lt;- lm(psoda~prpblck, data = discrim)
summary(basitdiscrimreg)</code></pre>
<pre><code>## 
## Call:
## lm(formula = psoda ~ prpblck, data = discrim)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.30884 -0.05963  0.01135  0.03206  0.44840 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.03740    0.00519  199.87  &lt; 2e-16 ***
## prpblck      0.06493    0.02396    2.71  0.00702 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.0881 on 399 degrees of freedom
##   (9 observations deleted due to missingness)
## Multiple R-squared:  0.01808,    Adjusted R-squared:  0.01561 
## F-statistic: 7.345 on 1 and 399 DF,  p-value: 0.007015</code></pre>
<p>Basit regresyon ile prpblack üzerindeki katsayının tahmini 0.065’tir. Bu, önceki tahminden daha düşüktür ve bu nedenle, gelir hariç tutulduğunda ayrımcılık etkisinin azaldığını gösterir.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>logdiscrimreg &lt;- lm(log(psoda)~prpblck+log(income), data = discrim)
summary(logdiscrimreg)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(psoda) ~ prpblck + log(income), data = discrim)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.33563 -0.04695  0.00658  0.04334  0.35413 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.79377    0.17943  -4.424 1.25e-05 ***
## prpblck      0.12158    0.02575   4.722 3.24e-06 ***
## log(income)  0.07651    0.01660   4.610 5.43e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.0821 on 398 degrees of freedom
##   (9 observations deleted due to missingness)
## Multiple R-squared:  0.06809,    Adjusted R-squared:  0.06341 
## F-statistic: 14.54 on 2 and 398 DF,  p-value: 8.039e-07</code></pre>
<pre class="r"><code>paste( (0.2*100)*0.122, &quot;yüzdelik artış&quot;)</code></pre>
<pre><code>## [1] &quot;2.44 yüzdelik artış&quot;</code></pre>
<p>“Prpblck” yüzde 20 artarsa, psoda tahmini olarak %2,44 artacaktır.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>logdiscrimregprpov &lt;- lm(log(psoda)~prpblck+log(income)+prppov, data = discrim)
summary(logdiscrimregprpov)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(psoda) ~ prpblck + log(income) + prppov, data = discrim)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.32218 -0.04648  0.00651  0.04272  0.35622 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.46333    0.29371  -4.982  9.4e-07 ***
## prpblck      0.07281    0.03068   2.373   0.0181 *  
## log(income)  0.13696    0.02676   5.119  4.8e-07 ***
## prppov       0.38036    0.13279   2.864   0.0044 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.08137 on 397 degrees of freedom
##   (9 observations deleted due to missingness)
## Multiple R-squared:  0.08696,    Adjusted R-squared:  0.08006 
## F-statistic:  12.6 on 3 and 397 DF,  p-value: 6.917e-08</code></pre>
<p>prppov eklemek, prpblck katsayısının 0,0738’e düşmesine neden olur.</p>
<ol start="7" style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>cor(log(discrim$income), discrim$prppov, use = &quot;complete.obs&quot;)</code></pre>
<pre><code>## [1] -0.838467</code></pre>
<p>Korelasyon yaklaşık olarak -0.838’dir. Bu mantıklı, çünkü gelirdeki düşüşlerin daha yüksek yoksulluk oranlarıyla sonuçlanması beklenebilir.</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Yüksek düzeyde ilişkili olmalarına rağmen, her ikisinin de dahil edilmesi mükemmel bir doğrusallık ile sonuçlanmaz ve bunun yerine, ayırt edici etkiyi izole etmeye yardımcı olan başka bir kontrol değişkeni ekleyerek modeli tamamlar.</li>
</ol>
<ol start="3" style="list-style-type: decimal">
<li></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>data(&quot;meapsingle&quot;)
paged_table(meapsingle)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["dcode"],"name":[1],"type":["int"],"align":["right"]},{"label":["bcode"],"name":[2],"type":["int"],"align":["right"]},{"label":["math4"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["read4"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["enroll"],"name":[5],"type":["int"],"align":["right"]},{"label":["exppp"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["free"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["reduced"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["lunch"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["medinc"],"name":[10],"type":["int"],"align":["right"]},{"label":["totchild"],"name":[11],"type":["int"],"align":["right"]},{"label":["married"],"name":[12],"type":["int"],"align":["right"]},{"label":["single"],"name":[13],"type":["int"],"align":["right"]},{"label":["pctsgle"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["zipcode"],"name":[15],"type":["int"],"align":["right"]},{"label":["lenroll"],"name":[16],"type":["dbl"],"align":["right"]},{"label":["lexppp"],"name":[17],"type":["dbl"],"align":["right"]},{"label":["lmedinc"],"name":[18],"type":["dbl"],"align":["right"]}],"data":[{"1":"63010","2":"3030","3":"92.8","4":"82.5","5":"607","6":"6619.54","7":"1.0","8":"0.7","9":"1.700000","10":"110322","11":"4076","12":"3542","13":"534","14":"13.101080","15":"48009","16":"6.408529","17":"8.797781","18":"11.61116"},{"1":"63010","2":"3133","3":"100.0","4":"94.3","5":"370","6":"6619.54","7":"0.0","8":"0.0","9":"0.000000","10":"110322","11":"4076","12":"3542","13":"534","14":"13.101080","15":"48009","16":"5.913503","17":"8.797781","18":"11.61116"},{"1":"63270","2":"2023","3":"72.1","4":"46.5","5":"220","6":"5607.56","7":"5.9","8":"5.0","9":"10.900000","10":"65119","11":"2524","12":"2091","13":"433","14":"17.155310","15":"48017","16":"5.393628","17":"8.631871","18":"11.08397"},{"1":"63270","2":"2978","3":"76.1","4":"65.7","5":"356","6":"5829.53","7":"8.1","8":"2.8","9":"10.900000","10":"65119","11":"2524","12":"2091","13":"433","14":"17.155310","15":"48017","16":"5.874931","17":"8.670691","18":"11.08397"},{"1":"63010","2":"316","3":"95.2","4":"80.6","5":"329","6":"6619.54","7":"0.3","8":"0.3","9":"0.600000","10":"109313","11":"3486","12":"3241","13":"245","14":"7.028112","15":"48025","16":"5.796058","17":"8.797781","18":"11.60197"},{"1":"63010","2":"5670","3":"88.6","4":"72.7","5":"331","6":"6619.54","7":"1.2","8":"0.9","9":"2.100000","10":"109313","11":"3486","12":"3241","13":"245","14":"7.028112","15":"48025","16":"5.802118","17":"8.797781","18":"11.60197"},{"1":"63010","2":"1494","3":"95.2","4":"90.5","5":"288","6":"6619.55","7":"12.2","8":"5.2","9":"17.400000","10":"109313","11":"3486","12":"3241","13":"245","14":"7.028112","15":"48025","16":"5.662961","17":"8.797783","18":"11.60197"},{"1":"63130","2":"1631","3":"66.7","4":"46.3","5":"452","6":"6092.66","7":"50.2","8":"17.5","9":"67.700000","10":"43750","11":"4651","12":"3258","13":"1393","14":"29.950550","15":"48030","16":"6.113682","17":"8.714840","18":"10.68625"},{"1":"63130","2":"1753","3":"83.9","4":"44.6","5":"428","6":"5155.40","7":"40.2","8":"10.0","9":"50.200000","10":"43750","11":"4651","12":"3258","13":"1393","14":"29.950550","15":"48030","16":"6.059123","17":"8.547800","18":"10.68625"},{"1":"63130","2":"2254","3":"95.7","4":"56.5","5":"238","6":"6095.71","7":"24.4","8":"17.6","9":"42.000000","10":"43750","11":"4651","12":"3258","13":"1393","14":"29.950550","15":"48030","16":"5.472270","17":"8.715341","18":"10.68625"},{"1":"63130","2":"3280","3":"100.0","4":"90.0","5":"216","6":"5464.97","7":"43.5","8":"13.9","9":"57.400000","10":"43750","11":"4651","12":"3258","13":"1393","14":"29.950550","15":"48030","16":"5.375278","17":"8.606114","18":"10.68625"},{"1":"63130","2":"4259","3":"93.5","4":"82.6","5":"364","6":"5132.18","7":"32.7","8":"14.0","9":"46.700000","10":"43750","11":"4651","12":"3258","13":"1393","14":"29.950550","15":"48030","16":"5.897154","17":"8.543285","18":"10.68625"},{"1":"63130","2":"4422","3":"90.5","4":"47.6","5":"577","6":"5183.29","7":"41.9","8":"19.6","9":"61.500000","10":"43750","11":"4651","12":"3258","13":"1393","14":"29.950550","15":"48030","16":"6.357842","17":"8.553195","18":"10.68625"},{"1":"63060","2":"24","3":"65.6","4":"41.0","5":"406","6":"7532.52","7":"28.3","8":"9.1","9":"37.400000","10":"59646","11":"5284","12":"3264","13":"2020","14":"38.228610","15":"48034","16":"6.006353","17":"8.926985","18":"10.99618"},{"1":"63060","2":"6032","3":"62.8","4":"90.7","5":"303","6":"9013.97","7":"23.4","8":"5.6","9":"29.000000","10":"59646","11":"5284","12":"3264","13":"2020","14":"38.228610","15":"48034","16":"5.713733","17":"9.106531","18":"10.99618"},{"1":"63060","2":"2295","3":"70.0","4":"53.3","5":"416","6":"6731.69","7":"33.2","8":"9.6","9":"42.800000","10":"59646","11":"5284","12":"3264","13":"2020","14":"38.228610","15":"48034","16":"6.030685","17":"8.814582","18":"10.99618"},{"1":"63040","2":"5105","3":"73.9","4":"52.2","5":"152","6":"7113.84","7":"11.2","8":"5.9","9":"17.100000","10":"67614","11":"4150","12":"3456","13":"694","14":"16.722890","15":"48067","16":"5.023880","17":"8.869798","18":"11.12157"},{"1":"63040","2":"2255","3":"90.0","4":"75.0","5":"207","6":"7818.74","7":"13.0","8":"0.0","9":"13.000000","10":"67614","11":"4150","12":"3456","13":"694","14":"16.722890","15":"48067","16":"5.332719","17":"8.964279","18":"11.12157"},{"1":"63040","2":"2805","3":"90.7","4":"67.4","5":"282","6":"6081.90","7":"11.0","8":"5.0","9":"16.000000","10":"67614","11":"4150","12":"3456","13":"694","14":"16.722890","15":"48067","16":"5.641907","17":"8.713073","18":"11.12157"},{"1":"63040","2":"4518","3":"66.1","4":"62.9","5":"373","6":"5489.56","7":"10.2","8":"5.1","9":"15.300000","10":"67614","11":"4150","12":"3456","13":"694","14":"16.722890","15":"48067","16":"5.921578","17":"8.610603","18":"11.12157"},{"1":"63050","2":"464","3":"94.8","4":"88.3","5":"525","6":"5154.88","7":"1.1","8":"0.2","9":"1.300000","10":"97206","11":"1581","12":"1352","13":"229","14":"14.484500","15":"48070","16":"6.263398","17":"8.547699","18":"11.48459"},{"1":"63280","2":"1089","3":"88.0","4":"62.0","5":"300","6":"5778.84","7":"8.7","8":"5.3","9":"14.000000","10":"51364","11":"6047","12":"4832","13":"1215","14":"20.092610","15":"48071","16":"5.703783","17":"8.661959","18":"10.84669"},{"1":"63280","2":"1682","3":"80.0","4":"52.0","5":"448","6":"5272.60","7":"34.6","8":"5.8","9":"40.400000","10":"51364","11":"6047","12":"4832","13":"1215","14":"20.092610","15":"48071","16":"6.104793","17":"8.570279","18":"10.84669"},{"1":"63280","2":"2168","3":"91.2","4":"73.5","5":"242","6":"7012.47","7":"15.7","8":"2.5","9":"18.200000","10":"51364","11":"6047","12":"4832","13":"1215","14":"20.092610","15":"48071","16":"5.488938","17":"8.855445","18":"10.84669"},{"1":"63280","2":"3483","3":"92.7","4":"56.1","5":"260","6":"6407.14","7":"15.4","8":"2.3","9":"17.700000","10":"51364","11":"6047","12":"4832","13":"1215","14":"20.092610","15":"48071","16":"5.560682","17":"8.765168","18":"10.84669"},{"1":"63140","2":"1083","3":"74.1","4":"56.6","5":"249","6":"7721.39","7":"30.5","8":"8.8","9":"39.300000","10":"51364","11":"6047","12":"4832","13":"1215","14":"20.092610","15":"48071","16":"5.517453","17":"8.951750","18":"10.84669"},{"1":"63140","2":"1537","3":"89.7","4":"38.5","5":"292","6":"5737.43","7":"34.2","8":"14.4","9":"48.600000","10":"51364","11":"6047","12":"4832","13":"1215","14":"20.092610","15":"48071","16":"5.676754","17":"8.654767","18":"10.84669"},{"1":"63140","2":"4280","3":"86.7","4":"58.3","5":"257","6":"5853.70","7":"28.0","8":"9.3","9":"37.300000","10":"51364","11":"6047","12":"4832","13":"1215","14":"20.092610","15":"48071","16":"5.549076","17":"8.674829","18":"10.84669"},{"1":"63050","2":"1875","3":"86.0","4":"68.8","5":"359","6":"5206.81","7":"6.1","8":"5.0","9":"11.100000","10":"66968","11":"3321","12":"2837","13":"484","14":"14.573920","15":"48072","16":"5.883322","17":"8.557723","18":"11.11197"},{"1":"63050","2":"2974","3":"65.0","4":"55.0","5":"298","6":"5159.14","7":"5.4","8":"6.0","9":"11.400000","10":"66968","11":"3321","12":"2837","13":"484","14":"14.573920","15":"48072","16":"5.697093","17":"8.548525","18":"11.11197"},{"1":"63050","2":"1549","3":"66.7","4":"60.3","5":"370","6":"4623.55","7":"6.2","8":"1.9","9":"8.099999","10":"66968","11":"3321","12":"2837","13":"484","14":"14.573920","15":"48072","16":"5.913503","17":"8.438918","18":"11.11197"},{"1":"63040","2":"4264","3":"93.9","4":"72.7","5":"233","6":"5660.08","7":"5.6","8":"6.0","9":"11.600000","10":"68331","11":"5960","12":"5132","13":"828","14":"13.892620","15":"48073","16":"5.451038","17":"8.641193","18":"11.13212"},{"1":"63040","2":"2381","3":"97.7","4":"88.6","5":"283","6":"6128.28","7":"5.7","8":"1.4","9":"7.100000","10":"68331","11":"5960","12":"5132","13":"828","14":"13.892620","15":"48073","16":"5.645447","17":"8.720670","18":"11.13212"},{"1":"63040","2":"2781","3":"86.8","4":"72.2","5":"281","6":"5376.37","7":"4.6","8":"0.7","9":"5.300000","10":"68331","11":"5960","12":"5132","13":"828","14":"13.892620","15":"48073","16":"5.638355","17":"8.589768","18":"11.13212"},{"1":"63040","2":"2800","3":"71.6","4":"57.5","5":"454","6":"5564.07","7":"6.6","8":"2.2","9":"8.800000","10":"68331","11":"5960","12":"5132","13":"828","14":"13.892620","15":"48073","16":"6.118097","17":"8.624085","18":"11.13212"},{"1":"63040","2":"2950","3":"100.0","4":"67.9","5":"215","6":"5960.48","7":"10.7","8":"3.7","9":"14.400000","10":"68331","11":"5960","12":"5132","13":"828","14":"13.892620","15":"48073","16":"5.370638","17":"8.692906","18":"11.13212"},{"1":"63040","2":"4057","3":"78.3","4":"66.7","5":"349","6":"5377.22","7":"8.3","8":"1.7","9":"10.000000","10":"68331","11":"5960","12":"5132","13":"828","14":"13.892620","15":"48073","16":"5.855072","17":"8.589927","18":"11.13212"},{"1":"63060","2":"2146","3":"95.0","4":"88.8","5":"539","6":"7675.18","7":"27.1","8":"7.1","9":"34.200000","10":"65871","11":"4058","12":"2947","13":"1111","14":"27.378020","15":"48075","16":"6.289716","17":"8.945747","18":"11.09545"},{"1":"63060","2":"1948","3":"58.2","4":"56.7","5":"363","6":"6353.08","7":"24.5","8":"7.2","9":"31.700000","10":"65871","11":"4058","12":"2947","13":"1111","14":"27.378020","15":"48075","16":"5.894403","17":"8.756695","18":"11.09545"},{"1":"63060","2":"5284","3":"95.2","4":"88.7","5":"373","6":"6184.35","7":"23.3","8":"6.4","9":"29.700000","10":"65871","11":"4058","12":"2947","13":"1111","14":"27.378020","15":"48075","16":"5.921578","17":"8.729777","18":"11.09545"},{"1":"63060","2":"1311","3":"87.1","4":"62.0","5":"437","6":"7752.37","7":"26.3","8":"6.4","9":"32.700000","10":"75224","11":"6331","12":"5004","13":"1327","14":"20.960350","15":"48076","16":"6.079933","17":"8.955754","18":"11.22823"},{"1":"63060","2":"1423","3":"91.2","4":"92.6","5":"391","6":"7161.15","7":"16.9","8":"10.0","9":"26.900000","10":"75224","11":"6331","12":"5004","13":"1327","14":"20.960350","15":"48076","16":"5.968708","17":"8.876426","18":"11.22823"},{"1":"63060","2":"5764","3":"88.8","4":"79.7","5":"400","6":"7209.10","7":"15.8","8":"4.5","9":"20.300000","10":"75224","11":"6331","12":"5004","13":"1327","14":"20.960350","15":"48076","16":"5.991465","17":"8.883100","18":"11.22823"},{"1":"63060","2":"4278","3":"90.2","4":"90.2","5":"377","6":"7819.51","7":"44.0","8":"9.8","9":"53.800000","10":"75224","11":"6331","12":"5004","13":"1327","14":"20.960350","15":"48076","16":"5.932245","17":"8.964377","18":"11.22823"},{"1":"63150","2":"6941","3":"100.0","4":"93.3","5":"440","6":"5741.81","7":"3.0","8":"1.6","9":"4.600000","10":"71303","11":"5088","12":"4529","13":"559","14":"10.986640","15":"48083","16":"6.086775","17":"8.655530","18":"11.17469"},{"1":"63010","2":"2995","3":"84.8","4":"57.6","5":"295","6":"6619.54","7":"0.7","8":"1.0","9":"1.700000","10":"88754","11":"3054","12":"2832","13":"222","14":"7.269155","15":"48084","16":"5.686975","17":"8.797781","18":"11.39362"},{"1":"63150","2":"6940","3":"100.0","4":"93.1","5":"474","6":"6213.45","7":"3.8","8":"0.0","9":"3.800000","10":"88754","11":"3054","12":"2832","13":"222","14":"7.269155","15":"48084","16":"6.161207","17":"8.734471","18":"11.39362"},{"1":"63150","2":"2618","3":"87.2","4":"76.1","5":"376","6":"4916.78","7":"10.9","8":"2.4","9":"13.300000","10":"88754","11":"3054","12":"2832","13":"222","14":"7.269155","15":"48084","16":"5.929589","17":"8.500409","18":"11.39362"},{"1":"63150","2":"6124","3":"100.0","4":"94.9","5":"492","6":"5953.01","7":"0.8","8":"0.2","9":"1.000000","10":"88754","11":"3054","12":"2832","13":"222","14":"7.269155","15":"48084","16":"6.198479","17":"8.691652","18":"11.39362"},{"1":"63150","2":"5537","3":"100.0","4":"87.3","5":"357","6":"5279.58","7":"5.9","8":"0.8","9":"6.700000","10":"88754","11":"3054","12":"2832","13":"222","14":"7.269155","15":"48084","16":"5.877736","17":"8.571602","18":"11.39362"},{"1":"63150","2":"3715","3":"98.7","4":"94.7","5":"505","6":"6144.30","7":"0.8","8":"0.4","9":"1.200000","10":"105000","11":"12360","12":"11479","13":"881","14":"7.127832","15":"48098","16":"6.224558","17":"8.723280","18":"11.56172"},{"1":"63150","2":"6365","3":"95.1","4":"75.3","5":"435","6":"5824.83","7":"4.6","8":"0.9","9":"5.500000","10":"105000","11":"12360","12":"11479","13":"881","14":"7.127832","15":"48098","16":"6.075346","17":"8.669885","18":"11.56172"},{"1":"81010","2":"6","3":"63.0","4":"61.1","5":"331","6":"5679.86","7":"17.5","8":"1.5","9":"19.000000","10":"80468","11":"10996","12":"8941","13":"2055","14":"18.688610","15":"48103","16":"5.802118","17":"8.644682","18":"11.29562"},{"1":"81010","2":"163","3":"64.8","4":"61.1","5":"244","6":"6433.83","7":"17.6","8":"5.7","9":"23.300000","10":"80468","11":"10996","12":"8941","13":"2055","14":"18.688610","15":"48103","16":"5.497168","17":"8.769325","18":"11.29562"},{"1":"81010","2":"2303","3":"77.8","4":"72.2","5":"384","6":"5626.63","7":"8.1","8":"3.1","9":"11.200000","10":"80468","11":"10996","12":"8941","13":"2055","14":"18.688610","15":"48103","16":"5.950643","17":"8.635266","18":"11.29562"},{"1":"81010","2":"915","3":"82.2","4":"71.2","5":"343","6":"5225.96","7":"17.5","8":"3.2","9":"20.700000","10":"80468","11":"10996","12":"8941","13":"2055","14":"18.688610","15":"48103","16":"5.837730","17":"8.561394","18":"11.29562"},{"1":"81010","2":"1064","3":"88.6","4":"67.1","5":"314","6":"5537.87","7":"11.8","8":"1.9","9":"13.700000","10":"80468","11":"10996","12":"8941","13":"2055","14":"18.688610","15":"48103","16":"5.749393","17":"8.619366","18":"11.29562"},{"1":"81010","2":"1534","3":"82.7","4":"69.3","5":"411","6":"4937.80","7":"12.2","8":"2.9","9":"15.100000","10":"80468","11":"10996","12":"8941","13":"2055","14":"18.688610","15":"48103","16":"6.018593","17":"8.504675","18":"11.29562"},{"1":"81010","2":"2143","3":"89.0","4":"74.4","5":"442","6":"4934.01","7":"14.3","8":"5.2","9":"19.500000","10":"80468","11":"10996","12":"8941","13":"2055","14":"18.688610","15":"48103","16":"6.091310","17":"8.503907","18":"11.29562"},{"1":"81010","2":"4562","3":"89.2","4":"79.7","5":"375","6":"5032.30","7":"7.2","8":"3.5","9":"10.700000","10":"80468","11":"10996","12":"8941","13":"2055","14":"18.688610","15":"48103","16":"5.926926","17":"8.523632","18":"11.29562"},{"1":"81010","2":"99","3":"98.0","4":"84.3","5":"288","6":"5520.19","7":"13.2","8":"7.3","9":"20.500000","10":"89045","11":"3907","12":"3434","13":"473","14":"12.106470","15":"48104","16":"5.662961","17":"8.616168","18":"11.39690"},{"1":"81010","2":"455","3":"88.2","4":"70.6","5":"370","6":"5416.43","7":"8.6","8":"1.6","9":"10.200000","10":"89045","11":"3907","12":"3434","13":"473","14":"12.106470","15":"48104","16":"5.913503","17":"8.597192","18":"11.39690"},{"1":"81010","2":"533","3":"61.1","4":"51.9","5":"306","6":"6202.08","7":"23.5","8":"7.5","9":"31.000000","10":"89045","11":"3907","12":"3434","13":"473","14":"12.106470","15":"48104","16":"5.723585","17":"8.732640","18":"11.39690"},{"1":"81010","2":"1939","3":"76.3","4":"56.9","5":"338","6":"6441.83","7":"19.5","8":"11.5","9":"31.000000","10":"89045","11":"3907","12":"3434","13":"473","14":"12.106470","15":"48104","16":"5.823046","17":"8.770568","18":"11.39690"},{"1":"81010","2":"2973","3":"69.7","4":"52.5","5":"368","6":"5702.08","7":"23.1","8":"7.1","9":"30.200000","10":"89045","11":"3907","12":"3434","13":"473","14":"12.106470","15":"48104","16":"5.908083","17":"8.648586","18":"11.39690"},{"1":"81010","2":"3060","3":"80.9","4":"66.0","5":"235","6":"6206.67","7":"19.6","8":"6.4","9":"26.000000","10":"89045","11":"3907","12":"3434","13":"473","14":"12.106470","15":"48104","16":"5.459586","17":"8.733379","18":"11.39690"},{"1":"81902","2":"8333","3":"60.0","4":"26.7","5":"232","6":"8372.16","7":"78.9","8":"4.7","9":"83.600000","10":"89045","11":"3907","12":"3434","13":"473","14":"12.106470","15":"48104","16":"5.446737","17":"9.032667","18":"11.39690"},{"1":"81010","2":"6697","3":"85.4","4":"72.9","5":"322","6":"5794.20","7":"12.7","8":"2.2","9":"14.900000","10":"73103","11":"7037","12":"5956","13":"1081","14":"15.361660","15":"48105","16":"5.774551","17":"8.664613","18":"11.19963"},{"1":"81010","2":"5760","3":"88.9","4":"83.1","5":"369","6":"5252.18","7":"4.6","8":"1.1","9":"5.700000","10":"73103","11":"7037","12":"5956","13":"1081","14":"15.361660","15":"48105","16":"5.910797","17":"8.566399","18":"11.19963"},{"1":"81010","2":"2766","3":"74.5","4":"57.4","5":"342","6":"5412.25","7":"19.9","8":"10.2","9":"30.100000","10":"73103","11":"7037","12":"5956","13":"1081","14":"15.361660","15":"48105","16":"5.834811","17":"8.596420","18":"11.19963"},{"1":"81010","2":"4182","3":"71.1","4":"66.3","5":"346","6":"5415.91","7":"9.5","8":"5.5","9":"15.000000","10":"73103","11":"7037","12":"5956","13":"1081","14":"15.361660","15":"48105","16":"5.846439","17":"8.597096","18":"11.19963"},{"1":"81010","2":"2582","3":"70.0","4":"65.0","5":"245","6":"6303.75","7":"16.7","8":"7.8","9":"24.500000","10":"65257","11":"5271","12":"3924","13":"1347","14":"25.554920","15":"48108","16":"5.501258","17":"8.748900","18":"11.08609"},{"1":"81040","2":"2720","3":"87.3","4":"70.4","5":"415","6":"4376.73","7":"1.2","8":"1.2","9":"2.400000","10":"77177","11":"2932","12":"2518","13":"414","14":"14.120050","15":"48118","16":"6.028278","17":"8.384057","18":"11.25386"},{"1":"81040","2":"8517","3":"83.8","4":"59.3","5":"405","6":"4262.31","7":"5.4","8":"1.7","9":"7.100000","10":"77177","11":"2932","12":"2518","13":"414","14":"14.120050","15":"48118","16":"6.003887","17":"8.357567","18":"11.25386"},{"1":"81040","2":"3507","3":"64.6","4":"54.2","5":"387","6":"4891.32","7":"4.9","8":"2.3","9":"7.200000","10":"77177","11":"2932","12":"2518","13":"414","14":"14.120050","15":"48118","16":"5.958425","17":"8.495217","18":"11.25386"},{"1":"81050","2":"214","3":"71.3","4":"64.6","5":"466","6":"4755.97","7":"3.2","8":"2.1","9":"5.300000","10":"80321","11":"2975","12":"2597","13":"378","14":"12.705880","15":"48130","16":"6.144186","17":"8.467156","18":"11.29379"},{"1":"81080","2":"5816","3":"82.5","4":"75.0","5":"464","6":"4308.88","7":"6.9","8":"2.2","9":"9.100000","10":"69199","11":"1650","12":"1363","13":"287","14":"17.393940","15":"48158","16":"6.139884","17":"8.368433","18":"11.14474"},{"1":"81100","2":"2930","3":"76.7","4":"50.9","5":"657","6":"5435.27","7":"11.7","8":"5.0","9":"16.700000","10":"63938","11":"2728","12":"2200","13":"528","14":"19.354840","15":"48160","16":"6.487684","17":"8.600664","18":"11.06567"},{"1":"63240","2":"2684","3":"72.0","4":"63.2","5":"490","6":"3983.24","7":"12.9","8":"5.9","9":"18.800000","10":"73438","11":"1668","12":"1478","13":"190","14":"11.390890","15":"48165","16":"6.194406","17":"8.289851","18":"11.20420"},{"1":"81120","2":"7527","3":"78.8","4":"56.5","5":"539","6":"4763.39","7":"3.3","8":"2.2","9":"5.500000","10":"86934","11":"5371","12":"4748","13":"623","14":"11.599330","15":"48176","16":"6.289716","17":"8.468715","18":"11.37290"},{"1":"81120","2":"8504","3":"86.6","4":"69.4","5":"635","6":"4879.58","7":"3.6","8":"3.0","9":"6.600000","10":"86934","11":"5371","12":"4748","13":"623","14":"11.599330","15":"48176","16":"6.453625","17":"8.492814","18":"11.37290"},{"1":"63240","2":"3522","3":"87.8","4":"77.5","5":"536","6":"3835.93","7":"7.1","8":"4.1","9":"11.200000","10":"79842","11":"6080","12":"5396","13":"684","14":"11.250000","15":"48178","16":"6.284134","17":"8.252167","18":"11.28780"},{"1":"63240","2":"3496","3":"77.1","4":"61.5","5":"700","6":"3669.58","7":"5.0","8":"1.3","9":"6.300000","10":"79842","11":"6080","12":"5396","13":"684","14":"11.250000","15":"48178","16":"6.551080","17":"8.207832","18":"11.28780"},{"1":"81070","2":"2186","3":"57.4","4":"47.1","5":"784","6":"4410.00","7":"18.9","8":"6.0","9":"24.900000","10":"64385","11":"10808","12":"7580","13":"3228","14":"29.866760","15":"48197","16":"6.664409","17":"8.391630","18":"11.07264"},{"1":"81020","2":"988","3":"55.4","4":"40.0","5":"360","6":"4887.21","7":"52.2","8":"11.9","9":"64.100000","10":"64385","11":"10808","12":"7580","13":"3228","14":"29.866760","15":"48197","16":"5.886104","17":"8.494377","18":"11.07264"},{"1":"81020","2":"1157","3":"60.4","4":"39.6","5":"369","6":"4427.06","7":"25.7","8":"7.0","9":"32.700000","10":"64385","11":"10808","12":"7580","13":"3228","14":"29.866760","15":"48197","16":"5.910797","17":"8.395491","18":"11.07264"},{"1":"81020","2":"1153","3":"40.3","4":"38.7","5":"360","6":"5078.97","7":"48.6","8":"7.8","9":"56.400000","10":"47308","11":"8772","12":"5088","13":"3684","14":"41.997260","15":"48198","16":"5.886104","17":"8.532864","18":"10.76443"},{"1":"81020","2":"2825","3":"53.2","4":"41.0","5":"408","6":"5401.05","7":"57.1","8":"6.6","9":"63.700000","10":"47308","11":"8772","12":"5088","13":"3684","14":"41.997260","15":"48198","16":"6.011267","17":"8.594349","18":"10.76443"},{"1":"81150","2":"5953","3":"75.8","4":"51.5","5":"343","6":"3684.20","7":"42.3","8":"10.5","9":"52.800000","10":"47308","11":"8772","12":"5088","13":"3684","14":"41.997260","15":"48198","16":"5.837730","17":"8.211808","18":"10.76443"},{"1":"81150","2":"1705","3":"61.3","4":"41.9","5":"394","6":"3723.28","7":"53.6","8":"13.5","9":"67.100000","10":"47308","11":"8772","12":"5088","13":"3684","14":"41.997260","15":"48198","16":"5.976351","17":"8.222361","18":"10.76443"},{"1":"81150","2":"1638","3":"71.4","4":"32.1","5":"230","6":"5083.97","7":"69.1","8":"10.4","9":"79.500000","10":"47308","11":"8772","12":"5088","13":"3684","14":"41.997260","15":"48198","16":"5.438079","17":"8.533848","18":"10.76443"},{"1":"63020","2":"4155","3":"88.6","4":"73.3","5":"424","6":"4634.42","7":"8.0","8":"6.8","9":"14.800000","10":"50028","11":"4818","12":"3078","13":"1740","14":"36.114570","15":"48220","16":"6.049734","17":"8.441266","18":"10.82034"},{"1":"63020","2":"4241","3":"18.9","4":"17.0","5":"335","6":"5047.83","7":"73.7","8":"11.6","9":"85.300000","10":"50028","11":"4818","12":"3078","13":"1740","14":"36.114570","15":"48220","16":"5.814130","17":"8.526713","18":"10.82034"},{"1":"63020","2":"4590","3":"50.0","4":"33.3","5":"375","6":"7241.43","7":"46.7","8":"14.4","9":"61.100000","10":"50028","11":"4818","12":"3078","13":"1740","14":"36.114570","15":"48220","16":"5.926926","17":"8.887574","18":"10.82034"},{"1":"63130","2":"2150","3":"85.7","4":"57.1","5":"281","6":"5727.38","7":"40.2","8":"8.5","9":"48.700000","10":"50028","11":"4818","12":"3078","13":"1740","14":"36.114570","15":"48220","16":"5.638355","17":"8.653013","18":"10.82034"},{"1":"63250","2":"1097","3":"53.8","4":"46.2","5":"658","6":"4064.26","7":"31.0","8":"8.1","9":"39.100000","10":"52012","11":"7922","12":"5521","13":"2401","14":"30.308000","15":"48237","16":"6.489205","17":"8.309987","18":"10.85923"},{"1":"63250","2":"2032","3":"46.8","4":"45.0","5":"436","6":"5288.03","7":"51.1","8":"8.0","9":"59.100000","10":"52012","11":"7922","12":"5521","13":"2401","14":"30.308000","15":"48237","16":"6.077642","17":"8.573201","18":"10.85923"},{"1":"63250","2":"3006","3":"56.1","4":"32.7","5":"528","6":"4241.30","7":"31.6","8":"8.5","9":"40.100000","10":"52012","11":"7922","12":"5521","13":"2401","14":"30.308000","15":"48237","16":"6.269096","17":"8.352625","18":"10.85923"},{"1":"63010","2":"818","3":"96.0","4":"78.8","5":"559","6":"6607.55","7":"0.4","8":"0.0","9":"0.400000","10":"128274","11":"3728","12":"3533","13":"195","14":"5.230687","15":"48301","16":"6.326149","17":"8.795968","18":"11.76192"},{"1":"63010","2":"5686","3":"94.7","4":"90.8","5":"618","6":"6640.96","7":"1.3","8":"0.0","9":"1.300000","10":"128274","11":"3728","12":"3533","13":"195","14":"5.230687","15":"48301","16":"6.426488","17":"8.801012","18":"11.76192"},{"1":"63080","2":"4830","3":"91.4","4":"78.6","5":"405","6":"7558.80","7":"0.5","8":"0.0","9":"0.500000","10":"138188","11":"3535","12":"3299","13":"236","14":"6.676096","15":"48302","16":"6.003887","17":"8.930468","18":"11.83637"},{"1":"63080","2":"5160","3":"86.4","4":"73.9","5":"470","6":"5905.47","7":"1.7","8":"0.2","9":"1.900000","10":"138188","11":"3535","12":"3299","13":"236","14":"6.676096","15":"48302","16":"6.152733","17":"8.683635","18":"11.83637"},{"1":"63080","2":"5538","3":"91.6","4":"80.7","5":"417","6":"6300.76","7":"0.5","8":"0.0","9":"0.500000","10":"138188","11":"3535","12":"3299","13":"236","14":"6.676096","15":"48302","16":"6.033086","17":"8.748425","18":"11.83637"},{"1":"63010","2":"1571","3":"98.1","4":"86.8","5":"393","6":"6619.53","7":"1.3","8":"0.3","9":"1.600000","10":"123516","11":"3666","12":"3284","13":"382","14":"10.420080","15":"48304","16":"5.973810","17":"8.797780","18":"11.72413"},{"1":"63080","2":"5076","3":"94.5","4":"87.7","5":"473","6":"6012.12","7":"3.4","8":"0.0","9":"3.400000","10":"123516","11":"3666","12":"3284","13":"382","14":"10.420080","15":"48304","16":"6.159095","17":"8.701532","18":"11.72413"},{"1":"63260","2":"178","3":"94.2","4":"83.9","5":"811","6":"3774.88","7":"0.1","8":"0.0","9":"0.100000","10":"114237","11":"7060","12":"6647","13":"413","14":"5.849858","15":"48306","16":"6.698268","17":"8.236124","18":"11.64603"},{"1":"63260","2":"1114","3":"98.7","4":"89.9","5":"452","6":"4823.65","7":"0.4","8":"0.0","9":"0.400000","10":"114237","11":"7060","12":"6647","13":"413","14":"5.849858","15":"48306","16":"6.113682","17":"8.481286","18":"11.64603"},{"1":"63260","2":"7310","3":"97.4","4":"87.2","5":"501","6":"4324.30","7":"1.0","8":"1.0","9":"2.000000","10":"114237","11":"7060","12":"6647","13":"413","14":"5.849858","15":"48306","16":"6.216606","17":"8.372005","18":"11.64603"},{"1":"63260","2":"7350","3":"96.2","4":"88.5","5":"457","6":"4212.53","7":"0.0","8":"0.0","9":"0.000000","10":"114237","11":"7060","12":"6647","13":"413","14":"5.849858","15":"48306","16":"6.124683","17":"8.345819","18":"11.64603"},{"1":"63260","2":"410","3":"96.8","4":"87.4","5":"604","6":"4430.24","7":"3.1","8":"3.8","9":"6.900000","10":"76424","11":"9152","12":"7764","13":"1388","14":"15.166080","15":"48307","16":"6.403574","17":"8.396209","18":"11.24405"},{"1":"63260","2":"1551","3":"94.8","4":"80.2","5":"511","6":"4648.62","7":"3.7","8":"3.9","9":"7.600000","10":"76424","11":"9152","12":"7764","13":"1388","14":"15.166080","15":"48307","16":"6.236370","17":"8.444325","18":"11.24405"},{"1":"63260","2":"7855","3":"96.7","4":"71.7","5":"589","6":"4883.38","7":"5.8","8":"2.9","9":"8.700001","10":"76424","11":"9152","12":"7764","13":"1388","14":"15.166080","15":"48307","16":"6.378426","17":"8.493593","18":"11.24405"},{"1":"63260","2":"1773","3":"94.2","4":"71.2","5":"280","6":"4795.69","7":"3.6","8":"3.2","9":"6.800000","10":"76424","11":"9152","12":"7764","13":"1388","14":"15.166080","15":"48307","16":"5.634789","17":"8.475472","18":"11.24405"},{"1":"63260","2":"2731","3":"90.4","4":"85.5","5":"589","6":"4054.84","7":"6.6","8":"3.1","9":"9.700000","10":"76424","11":"9152","12":"7764","13":"1388","14":"15.166080","15":"48307","16":"6.378426","17":"8.307667","18":"11.24405"},{"1":"63070","2":"7446","3":"100.0","4":"93.5","5":"372","6":"5512.27","7":"3.8","8":"1.3","9":"5.100000","10":"95516","11":"6336","12":"5825","13":"511","14":"8.065025","15":"48309","16":"5.918894","17":"8.614732","18":"11.46705"},{"1":"63260","2":"5239","3":"100.0","4":"85.7","5":"413","6":"4223.98","7":"1.2","8":"0.5","9":"1.700000","10":"95516","11":"6336","12":"5825","13":"511","14":"8.065025","15":"48309","16":"6.023448","17":"8.348533","18":"11.46705"},{"1":"63260","2":"2498","3":"90.1","4":"74.1","5":"416","6":"4563.44","7":"0.2","8":"0.0","9":"0.200000","10":"95516","11":"6336","12":"5825","13":"511","14":"8.065025","15":"48309","16":"6.030685","17":"8.425832","18":"11.46705"},{"1":"63260","2":"6270","3":"100.0","4":"77.9","5":"488","6":"4746.81","7":"1.8","8":"0.2","9":"2.000000","10":"95516","11":"6336","12":"5825","13":"511","14":"8.065025","15":"48309","16":"6.190315","17":"8.465228","18":"11.46705"},{"1":"63160","2":"3271","3":"93.2","4":"86.3","5":"356","6":"6356.23","7":"20.8","8":"7.9","9":"28.700000","10":"59714","11":"920","12":"726","13":"194","14":"21.086960","15":"48320","16":"5.874931","17":"8.757191","18":"10.99732"},{"1":"63200","2":"994","3":"94.7","4":"72.9","5":"398","6":"5603.87","7":"3.3","8":"1.5","9":"4.800000","10":"101783","11":"7034","12":"6529","13":"505","14":"7.179414","15":"48322","16":"5.986452","17":"8.631213","18":"11.53060"},{"1":"63290","2":"6283","3":"75.3","4":"50.7","5":"470","6":"5437.54","7":"3.8","8":"1.9","9":"5.700000","10":"101783","11":"7034","12":"6529","13":"505","14":"7.179414","15":"48322","16":"6.152733","17":"8.601082","18":"11.53060"},{"1":"63160","2":"5783","3":"91.3","4":"71.0","5":"412","6":"5900.13","7":"5.6","8":"1.0","9":"6.600000","10":"101783","11":"7034","12":"6529","13":"505","14":"7.179414","15":"48322","16":"6.021023","17":"8.682730","18":"11.53060"},{"1":"63160","2":"1401","3":"94.4","4":"74.6","5":"496","6":"5909.15","7":"4.6","8":"1.8","9":"6.400000","10":"101783","11":"7034","12":"6529","13":"505","14":"7.179414","15":"48322","16":"6.206576","17":"8.684258","18":"11.53060"},{"1":"63080","2":"5766","3":"96.0","4":"88.0","5":"316","6":"8389.23","7":"0.9","8":"0.9","9":"1.800000","10":"116893","11":"4607","12":"4184","13":"423","14":"9.181680","15":"48323","16":"5.755742","17":"9.034704","18":"11.66901"},{"1":"63080","2":"5349","3":"92.4","4":"72.7","5":"329","6":"7126.12","7":"0.0","8":"0.0","9":"0.000000","10":"116893","11":"4607","12":"4184","13":"423","14":"9.181680","15":"48323","16":"5.796058","17":"8.871522","18":"11.66901"},{"1":"63290","2":"7447","3":"92.4","4":"71.4","5":"596","6":"5220.97","7":"3.2","8":"1.7","9":"4.900000","10":"116893","11":"4607","12":"4184","13":"423","14":"9.181680","15":"48323","16":"6.390241","17":"8.560438","18":"11.66901"},{"1":"63290","2":"4235","3":"76.7","4":"67.4","5":"349","6":"6627.02","7":"2.3","8":"2.0","9":"4.300000","10":"116893","11":"4607","12":"4184","13":"423","14":"9.181680","15":"48323","16":"5.855072","17":"8.798910","18":"11.66901"},{"1":"63160","2":"1491","3":"84.7","4":"76.5","5":"477","6":"5692.00","7":"3.4","8":"1.3","9":"4.700000","10":"116893","11":"4607","12":"4184","13":"423","14":"9.181680","15":"48323","16":"6.167517","17":"8.646817","18":"11.66901"},{"1":"63290","2":"2001","3":"95.4","4":"87.2","5":"651","6":"4876.39","7":"0.8","8":"1.1","9":"1.900000","10":"96568","11":"5077","12":"4650","13":"427","14":"8.410479","15":"48324","16":"6.478509","17":"8.492161","18":"11.47800"},{"1":"63070","2":"148","3":"90.9","4":"60.0","5":"374","6":"5245.76","7":"11.8","8":"2.7","9":"14.500000","10":"61227","11":"3677","12":"2855","13":"822","14":"22.355180","15":"48326","16":"5.924256","17":"8.565175","18":"11.02234"},{"1":"63070","2":"5363","3":"94.0","4":"86.2","5":"354","6":"5431.56","7":"9.6","8":"7.1","9":"16.700000","10":"61227","11":"3677","12":"2855","13":"822","14":"22.355180","15":"48326","16":"5.869297","17":"8.599981","18":"11.02234"},{"1":"63030","2":"4532","3":"57.5","4":"62.5","5":"320","6":"6315.68","7":"44.7","8":"6.6","9":"51.300000","10":"61227","11":"3677","12":"2855","13":"822","14":"22.355180","15":"48326","16":"5.768321","17":"8.750791","18":"11.02234"},{"1":"63300","2":"897","3":"93.0","4":"69.7","5":"306","6":"4595.37","7":"16.7","8":"7.2","9":"23.900000","10":"64886","11":"4577","12":"3645","13":"932","14":"20.362680","15":"48327","16":"5.723585","17":"8.432804","18":"11.08039"},{"1":"63300","2":"2138","3":"90.9","4":"83.6","5":"355","6":"4669.76","7":"5.9","8":"3.4","9":"9.300000","10":"64886","11":"4577","12":"3645","13":"932","14":"20.362680","15":"48327","16":"5.872118","17":"8.448863","18":"11.08039"},{"1":"63300","2":"4535","3":"76.5","4":"63.0","5":"414","6":"4536.00","7":"19.3","8":"7.2","9":"26.500000","10":"64886","11":"4577","12":"3645","13":"932","14":"20.362680","15":"48327","16":"6.025866","17":"8.419801","18":"11.08039"},{"1":"63300","2":"522","3":"67.3","4":"46.2","5":"310","6":"4405.63","7":"29.7","8":"5.5","9":"35.200000","10":"57274","11":"5412","12":"4035","13":"1377","14":"25.443460","15":"48328","16":"5.736572","17":"8.390638","18":"10.95560"},{"1":"63300","2":"933","3":"64.9","4":"49.1","5":"385","6":"4620.95","7":"35.1","8":"3.4","9":"38.500000","10":"57274","11":"5412","12":"4035","13":"1377","14":"25.443460","15":"48328","16":"5.953243","17":"8.438355","18":"10.95560"},{"1":"63300","2":"1106","3":"56.3","4":"52.1","5":"327","6":"4382.68","7":"27.8","8":"13.1","9":"40.900000","10":"57274","11":"5412","12":"4035","13":"1377","14":"25.443460","15":"48328","16":"5.789960","17":"8.385416","18":"10.95560"},{"1":"63300","2":"1484","3":"80.6","4":"65.3","5":"394","6":"4412.77","7":"17.8","8":"5.3","9":"23.100000","10":"70044","11":"5887","12":"5167","13":"720","14":"12.230340","15":"48329","16":"5.976351","17":"8.392258","18":"11.15688"},{"1":"63300","2":"1891","3":"91.5","4":"88.7","5":"345","6":"4531.62","7":"2.6","8":"2.0","9":"4.600000","10":"70044","11":"5887","12":"5167","13":"720","14":"12.230340","15":"48329","16":"5.843544","17":"8.418835","18":"11.15688"},{"1":"63300","2":"3418","3":"92.8","4":"79.5","5":"417","6":"4503.36","7":"11.8","8":"4.6","9":"16.400000","10":"70044","11":"5887","12":"5167","13":"720","14":"12.230340","15":"48329","16":"6.033086","17":"8.412579","18":"11.15688"},{"1":"63300","2":"4169","3":"71.6","4":"71.6","5":"468","6":"4434.99","7":"9.4","8":"7.1","9":"16.500000","10":"70044","11":"5887","12":"5167","13":"720","14":"12.230340","15":"48329","16":"6.148468","17":"8.397281","18":"11.15688"},{"1":"63200","2":"5100","3":"91.1","4":"80.0","5":"308","6":"6799.22","7":"1.6","8":"1.3","9":"2.900000","10":"109185","11":"5935","12":"5400","13":"535","14":"9.014322","15":"48331","16":"5.730100","17":"8.824563","18":"11.60080"},{"1":"63200","2":"4579","3":"97.9","4":"72.3","5":"282","6":"6749.77","7":"1.8","8":"0.4","9":"2.200000","10":"109185","11":"5935","12":"5400","13":"535","14":"9.014322","15":"48331","16":"5.641907","17":"8.817264","18":"11.60080"},{"1":"63200","2":"255","3":"81.8","4":"74.2","5":"400","6":"5328.28","7":"6.8","8":"3.0","9":"9.800000","10":"81223","11":"3763","12":"3193","13":"570","14":"15.147490","15":"48334","16":"5.991465","17":"8.580784","18":"11.30495"},{"1":"63200","2":"7251","3":"100.0","4":"96.2","5":"306","6":"6257.07","7":"0.7","8":"0.3","9":"1.000000","10":"81223","11":"3763","12":"3193","13":"570","14":"15.147490","15":"48334","16":"5.723585","17":"8.741467","18":"11.30495"},{"1":"63200","2":"2012","3":"86.4","4":"74.6","5":"374","6":"6781.45","7":"4.8","8":"1.1","9":"5.900000","10":"81223","11":"3763","12":"3193","13":"570","14":"15.147490","15":"48334","16":"5.924256","17":"8.821946","18":"11.30495"},{"1":"63200","2":"5865","3":"68.8","4":"59.7","5":"419","6":"6243.73","7":"8.6","8":"2.4","9":"11.000000","10":"81223","11":"3763","12":"3193","13":"570","14":"15.147490","15":"48334","16":"6.037871","17":"8.739333","18":"11.30495"},{"1":"63200","2":"1404","3":"88.0","4":"65.3","5":"542","6":"6311.01","7":"4.4","8":"0.9","9":"5.300000","10":"78289","11":"4124","12":"3675","13":"449","14":"10.887490","15":"48335","16":"6.295266","17":"8.750051","18":"11.26816"},{"1":"63200","2":"7444","3":"89.4","4":"78.7","5":"572","6":"6090.31","7":"3.0","8":"1.6","9":"4.600000","10":"78289","11":"4124","12":"3675","13":"449","14":"10.887490","15":"48335","16":"6.349139","17":"8.714455","18":"11.26816"},{"1":"63200","2":"2252","3":"85.1","4":"61.2","5":"388","6":"5720.36","7":"3.1","8":"0.3","9":"3.400000","10":"78289","11":"4124","12":"3675","13":"449","14":"10.887490","15":"48335","16":"5.961005","17":"8.651787","18":"11.26816"},{"1":"63200","2":"2132","3":"89.6","4":"65.4","5":"464","6":"5816.61","7":"7.1","8":"3.7","9":"10.800000","10":"72073","11":"5759","12":"4711","13":"1048","14":"18.197600","15":"48336","16":"6.139884","17":"8.668473","18":"11.18543"},{"1":"63200","2":"4537","3":"60.5","4":"51.2","5":"257","6":"6184.22","7":"16.7","8":"3.9","9":"20.600000","10":"72073","11":"5759","12":"4711","13":"1048","14":"18.197600","15":"48336","16":"5.549076","17":"8.729756","18":"11.18543"},{"1":"63030","2":"45","3":"36.7","4":"25.4","5":"369","6":"7147.68","7":"55.3","8":"8.4","9":"63.700000","10":"36615","11":"6377","12":"3229","13":"3148","14":"49.364910","15":"48340","16":"5.910797","17":"8.874543","18":"10.50821"},{"1":"63030","2":"1139","3":"39.0","4":"27.1","5":"303","6":"6096.19","7":"74.3","8":"7.3","9":"81.600010","10":"36615","11":"6377","12":"3229","13":"3148","14":"49.364910","15":"48340","16":"5.713733","17":"8.715419","18":"10.50821"},{"1":"63030","2":"2144","3":"72.5","4":"58.5","5":"433","6":"5499.44","7":"46.7","8":"5.1","9":"51.800000","10":"36615","11":"6377","12":"3229","13":"3148","14":"49.364910","15":"48340","16":"6.070738","17":"8.612402","18":"10.50821"},{"1":"63030","2":"2922","3":"41.8","4":"25.4","5":"365","6":"7768.24","7":"53.7","8":"6.3","9":"60.000000","10":"36615","11":"6377","12":"3229","13":"3148","14":"49.364910","15":"48340","16":"5.899898","17":"8.957799","18":"10.50821"},{"1":"63030","2":"834","3":"46.5","4":"34.9","5":"310","6":"6507.43","7":"65.8","8":"4.2","9":"70.000000","10":"39255","11":"4246","12":"2008","13":"2238","14":"52.708430","15":"48341","16":"5.736572","17":"8.780700","18":"10.57783"},{"1":"63030","2":"275","3":"44.4","4":"22.2","5":"266","6":"7658.13","7":"71.4","8":"7.1","9":"78.500000","10":"39255","11":"4246","12":"2008","13":"2238","14":"52.708430","15":"48341","16":"5.583496","17":"8.943523","18":"10.57783"},{"1":"63030","2":"4423","3":"48.1","4":"44.2","5":"384","6":"5426.06","7":"57.6","8":"5.2","9":"62.800000","10":"39255","11":"4246","12":"2008","13":"2238","14":"52.708430","15":"48341","16":"5.950643","17":"8.598969","18":"10.57783"},{"1":"63030","2":"1652","3":"81.0","4":"57.1","5":"357","6":"6833.36","7":"60.5","8":"6.7","9":"67.200000","10":"31935","11":"5745","12":"2497","13":"3248","14":"56.536120","15":"48342","16":"5.877736","17":"8.829572","18":"10.37146"},{"1":"63030","2":"2260","3":"100.0","4":"82.9","5":"314","6":"6144.62","7":"69.4","8":"4.8","9":"74.200000","10":"31935","11":"5745","12":"2497","13":"3248","14":"56.536120","15":"48342","16":"5.749393","17":"8.723332","18":"10.37146"},{"1":"63030","2":"2384","3":"33.3","4":"15.4","5":"324","6":"7760.81","7":"65.4","8":"8.3","9":"73.700000","10":"31935","11":"5745","12":"2497","13":"3248","14":"56.536120","15":"48342","16":"5.780744","17":"8.956842","18":"10.37146"},{"1":"63030","2":"5752","3":"54.5","4":"55.6","5":"419","6":"4786.32","7":"64.7","8":"7.9","9":"72.600000","10":"31935","11":"5745","12":"2497","13":"3248","14":"56.536120","15":"48342","16":"6.037871","17":"8.473517","18":"10.37146"},{"1":"63190","2":"704","3":"96.1","4":"74.7","5":"351","6":"5634.92","7":"3.7","8":"3.1","9":"6.800000","10":"76856","11":"5603","12":"4604","13":"999","14":"17.829730","15":"48346","16":"5.860786","17":"8.636738","18":"11.24969"},{"1":"63190","2":"5624","3":"81.1","4":"60.8","5":"377","6":"6258.94","7":"11.4","8":"8.2","9":"19.600000","10":"76856","11":"5603","12":"4604","13":"999","14":"17.829730","15":"48346","16":"5.932245","17":"8.741766","18":"11.24969"},{"1":"63190","2":"3054","3":"89.9","4":"65.2","5":"379","6":"5943.68","7":"9.8","8":"4.7","9":"14.500000","10":"76856","11":"5603","12":"4604","13":"999","14":"17.829730","15":"48346","16":"5.937536","17":"8.690084","18":"11.24969"},{"1":"63190","2":"170","3":"91.8","4":"72.4","5":"432","6":"5992.99","7":"1.6","8":"2.3","9":"3.900000","10":"89651","11":"5950","12":"5222","13":"728","14":"12.235290","15":"48348","16":"6.068426","17":"8.698346","18":"11.40368"},{"1":"63190","2":"8056","3":"92.6","4":"75.3","5":"440","6":"5440.06","7":"3.6","8":"0.7","9":"4.300000","10":"89651","11":"5950","12":"5222","13":"728","14":"12.235290","15":"48348","16":"6.086775","17":"8.601545","18":"11.40368"},{"1":"63190","2":"95","3":"88.9","4":"79.4","5":"342","6":"5890.68","7":"6.1","8":"2.9","9":"9.000000","10":"71602","11":"1902","12":"1638","13":"264","14":"13.880130","15":"48350","16":"5.834811","17":"8.681127","18":"11.17888"},{"1":"63210","2":"877","3":"84.6","4":"61.5","5":"500","6":"4219.22","7":"17.6","8":"6.0","9":"23.600000","10":"71602","11":"1902","12":"1638","13":"264","14":"13.880130","15":"48350","16":"6.214608","17":"8.347405","18":"11.17888"},{"1":"63220","2":"6490","3":"82.8","4":"64.1","5":"446","6":"4166.48","7":"7.2","8":"3.8","9":"11.000000","10":"73938","11":"2331","12":"2019","13":"312","14":"13.384810","15":"48356","16":"6.100319","17":"8.334826","18":"11.21098"},{"1":"63220","2":"5309","3":"67.9","4":"47.0","5":"511","6":"4071.70","7":"15.1","8":"10.6","9":"25.700000","10":"65684","11":"2543","12":"1959","13":"584","14":"22.965000","15":"48357","16":"6.236370","17":"8.311816","18":"11.09261"},{"1":"63220","2":"8608","3":"76.1","4":"66.2","5":"444","6":"4397.09","7":"4.3","8":"4.5","9":"8.800000","10":"65684","11":"2543","12":"1959","13":"584","14":"22.965000","15":"48357","16":"6.095825","17":"8.388699","18":"11.09261"},{"1":"63220","2":"5787","3":"82.4","4":"64.6","5":"409","6":"4489.95","7":"12.7","8":"8.3","9":"21.000000","10":"65684","11":"2543","12":"1959","13":"584","14":"22.965000","15":"48357","16":"6.013715","17":"8.409596","18":"11.09261"},{"1":"63230","2":"8443","3":"100.0","4":"92.5","5":"490","6":"4374.70","7":"3.7","8":"2.7","9":"6.400000","10":"70385","11":"1913","12":"1591","13":"322","14":"16.832200","15":"48359","16":"6.194406","17":"8.383594","18":"11.16174"},{"1":"63230","2":"6281","3":"89.6","4":"84.6","5":"503","6":"4981.50","7":"5.6","8":"2.2","9":"7.800000","10":"90982","11":"3464","12":"3220","13":"244","14":"7.043880","15":"48360","16":"6.220590","17":"8.513486","18":"11.41842"},{"1":"63230","2":"347","3":"85.7","4":"68.8","5":"474","6":"4388.55","7":"8.0","8":"2.3","9":"10.300000","10":"79958","11":"3464","12":"2947","13":"517","14":"14.924940","15":"48362","16":"6.161207","17":"8.386754","18":"11.28926"},{"1":"63230","2":"6280","3":"98.8","4":"90.4","5":"573","6":"4506.41","7":"7.2","8":"1.4","9":"8.599999","10":"79958","11":"3464","12":"2947","13":"517","14":"14.924940","15":"48362","16":"6.350886","17":"8.413256","18":"11.28926"},{"1":"63230","2":"4414","3":"98.9","4":"83.2","5":"570","6":"3954.79","7":"0.7","8":"1.9","9":"2.600000","10":"79958","11":"3464","12":"2947","13":"517","14":"14.924940","15":"48362","16":"6.345636","17":"8.282682","18":"11.28926"},{"1":"63110","2":"2160","3":"53.8","4":"26.9","5":"165","6":"4612.22","7":"6.1","8":"2.4","9":"8.500000","10":"71932","11":"1346","12":"1143","13":"203","14":"15.081720","15":"48367","16":"5.105946","17":"8.436464","18":"11.18348"},{"1":"63110","2":"713","3":"95.3","4":"80.0","5":"535","6":"4371.84","7":"3.2","8":"0.6","9":"3.800000","10":"75635","11":"5021","12":"4336","13":"685","14":"13.642700","15":"48371","16":"6.282267","17":"8.382939","18":"11.23367"},{"1":"63110","2":"8629","3":"77.5","4":"59.2","5":"492","6":"4304.29","7":"9.6","8":"4.5","9":"14.100000","10":"75635","11":"5021","12":"4336","13":"685","14":"13.642700","15":"48371","16":"6.198479","17":"8.367368","18":"11.23367"},{"1":"63110","2":"7997","3":"93.5","4":"62.3","5":"237","6":"4464.62","7":"5.1","8":"2.1","9":"7.200000","10":"75635","11":"5021","12":"4336","13":"685","14":"13.642700","15":"48371","16":"5.468060","17":"8.403939","18":"11.23367"},{"1":"63100","2":"2788","3":"92.5","4":"85.0","5":"413","6":"6497.45","7":"0.5","8":"0.5","9":"1.000000","10":"118204","11":"4616","12":"4287","13":"329","14":"7.127383","15":"48374","16":"6.023448","17":"8.779165","18":"11.68017"},{"1":"63100","2":"7349","3":"97.6","4":"78.9","5":"578","6":"6224.42","7":"1.6","8":"1.9","9":"3.500000","10":"118204","11":"4616","12":"4287","13":"329","14":"7.127383","15":"48374","16":"6.359574","17":"8.736236","18":"11.68017"},{"1":"63100","2":"2843","3":"95.0","4":"89.0","5":"478","6":"6580.66","7":"1.0","8":"0.8","9":"1.800000","10":"91318","11":"5437","12":"5099","13":"338","14":"6.216663","15":"48375","16":"6.169611","17":"8.791890","18":"11.42210"},{"1":"63100","2":"6173","3":"96.6","4":"93.1","5":"373","6":"8171.93","7":"1.3","8":"1.1","9":"2.400000","10":"91318","11":"5437","12":"5099","13":"338","14":"6.216663","15":"48375","16":"5.921578","17":"9.008460","18":"11.42210"},{"1":"63290","2":"7544","3":"85.7","4":"59.0","5":"500","6":"5712.58","7":"11.4","8":"3.4","9":"14.800000","10":"60611","11":"1937","12":"1458","13":"479","14":"24.728960","15":"48377","16":"6.214608","17":"8.650426","18":"11.01223"},{"1":"63220","2":"175","3":"75.6","4":"53.7","5":"288","6":"3920.48","7":"17.7","8":"5.9","9":"23.600000","10":"75047","11":"3271","12":"2598","13":"673","14":"20.574750","15":"48381","16":"5.662961","17":"8.273970","18":"11.22587"},{"1":"63220","2":"1965","3":"79.3","4":"66.7","5":"465","6":"3867.95","7":"10.8","8":"2.6","9":"13.400000","10":"75047","11":"3271","12":"2598","13":"673","14":"20.574750","15":"48381","16":"6.142037","17":"8.260480","18":"11.22587"},{"1":"63220","2":"5759","3":"83.3","4":"79.5","5":"511","6":"3342.19","7":"6.1","8":"2.7","9":"8.800000","10":"75047","11":"3271","12":"2598","13":"673","14":"20.574750","15":"48381","16":"6.236370","17":"8.114382","18":"11.22587"},{"1":"63220","2":"7811","3":"90.0","4":"82.2","5":"735","6":"3317.43","7":"3.1","8":"2.6","9":"5.700000","10":"85873","11":"5661","12":"5109","13":"552","14":"9.750927","15":"48382","16":"6.599871","17":"8.106946","18":"11.36062"},{"1":"63290","2":"763","3":"96.1","4":"80.3","5":"506","6":"5388.58","7":"3.4","8":"2.8","9":"6.200000","10":"85873","11":"5661","12":"5109","13":"552","14":"9.750927","15":"48382","16":"6.226537","17":"8.592037","18":"11.36062"},{"1":"63220","2":"413","3":"64.3","4":"52.4","5":"334","6":"4572.56","7":"20.7","8":"10.2","9":"30.900000","10":"78940","11":"3464","12":"2938","13":"526","14":"15.184760","15":"48383","16":"5.811141","17":"8.427829","18":"11.27644"},{"1":"63220","2":"6489","3":"92.8","4":"65.2","5":"497","6":"4074.64","7":"2.6","8":"2.0","9":"4.600000","10":"78940","11":"3464","12":"2938","13":"526","14":"15.184760","15":"48383","16":"6.208590","17":"8.312537","18":"11.27644"},{"1":"63220","2":"5070","3":"72.1","4":"54.4","5":"445","6":"4121.88","7":"14.6","8":"5.8","9":"20.400000","10":"72554","11":"3864","12":"3379","13":"485","14":"12.551760","15":"48386","16":"6.098074","17":"8.324064","18":"11.19209"},{"1":"63290","2":"961","3":"82.1","4":"69.5","5":"580","6":"5266.52","7":"5.0","8":"2.6","9":"7.600000","10":"72554","11":"3864","12":"3379","13":"485","14":"12.551760","15":"48386","16":"6.363028","17":"8.569125","18":"11.19209"},{"1":"63300","2":"946","3":"89.1","4":"81.8","5":"406","6":"4315.54","7":"8.4","8":"2.0","9":"10.400000","10":"72554","11":"3864","12":"3379","13":"485","14":"12.551760","15":"48386","16":"6.006353","17":"8.369978","18":"11.19209"},{"1":"63290","2":"1420","3":"77.6","4":"72.9","5":"446","6":"5980.60","7":"3.1","8":"1.6","9":"4.700000","10":"69181","11":"4900","12":"4130","13":"770","14":"15.714290","15":"48390","16":"6.100319","17":"8.696277","18":"11.14448"},{"1":"63290","2":"889","3":"91.5","4":"69.0","5":"436","6":"5543.03","7":"3.9","8":"3.7","9":"7.600000","10":"69181","11":"4900","12":"4130","13":"770","14":"15.714290","15":"48390","16":"6.077642","17":"8.620296","18":"11.14448"},{"1":"63290","2":"2809","3":"93.0","4":"80.8","5":"434","6":"6566.75","7":"0.2","8":"1.2","9":"1.400000","10":"69181","11":"4900","12":"4130","13":"770","14":"15.714290","15":"48390","16":"6.073044","17":"8.789774","18":"11.14448"},{"1":"63290","2":"4341","3":"78.1","4":"67.2","5":"436","6":"5706.25","7":"12.6","8":"5.5","9":"18.100000","10":"69181","11":"4900","12":"4130","13":"770","14":"15.714290","15":"48390","16":"6.077642","17":"8.649318","18":"11.14448"},{"1":"63290","2":"5706","3":"82.4","4":"79.7","5":"535","6":"5241.78","7":"5.0","8":"2.4","9":"7.400000","10":"61250","11":"3933","12":"3063","13":"870","14":"22.120520","15":"48393","16":"6.282267","17":"8.564416","18":"11.02272"},{"1":"63210","2":"1699","3":"77.4","4":"39.6","5":"389","6":"4365.29","7":"18.3","8":"10.0","9":"28.300000","10":"60936","11":"4817","12":"4056","13":"761","14":"15.798210","15":"48442","16":"5.963579","17":"8.381440","18":"11.01758"},{"1":"63210","2":"2976","3":"69.1","4":"44.4","5":"541","6":"4223.75","7":"16.3","8":"7.4","9":"23.700000","10":"60936","11":"4817","12":"4056","13":"761","14":"15.798210","15":"48442","16":"6.293419","17":"8.348478","18":"11.01758"},{"1":"63210","2":"8497","3":"68.3","4":"48.3","5":"500","6":"3622.06","7":"9.6","8":"4.8","9":"14.400000","10":"60936","11":"4817","12":"4056","13":"761","14":"15.798210","15":"48442","16":"6.214608","17":"8.194798","18":"11.01758"},{"1":"63180","2":"262","3":"94.5","4":"81.3","5":"422","6":"4207.36","7":"5.5","8":"5.0","9":"10.500000","10":"81196","11":"3675","12":"3196","13":"479","14":"13.034010","15":"48462","16":"6.045005","17":"8.344590","18":"11.30462"},{"1":"63180","2":"5846","3":"91.0","4":"69.0","5":"558","6":"3988.39","7":"10.6","8":"5.2","9":"15.800000","10":"81196","11":"3675","12":"3196","13":"479","14":"13.034010","15":"48462","16":"6.324359","17":"8.291142","18":"11.30462"},{"1":"63180","2":"5180","3":"93.2","4":"71.2","5":"369","6":"4038.07","7":"12.2","8":"3.3","9":"15.500000","10":"81196","11":"3675","12":"3196","13":"479","14":"13.034010","15":"48462","16":"5.910797","17":"8.303522","18":"11.30462"},{"1":"38090","2":"302","3":"69.4","4":"40.3","5":"406","6":"3805.50","7":"19.2","8":"8.4","9":"27.600000","10":"54146","11":"9573","12":"7353","13":"2220","14":"23.190220","15":"49201","16":"6.006353","17":"8.244203","18":"10.89944"},{"1":"38170","2":"66","3":"50.0","4":"33.3","5":"417","6":"4987.81","7":"79.4","8":"12.0","9":"91.400000","10":"54146","11":"9573","12":"7353","13":"2220","14":"23.190220","15":"49201","16":"6.033086","17":"8.514752","18":"10.89944"},{"1":"38170","2":"914","3":"63.6","4":"50.0","5":"309","6":"4907.41","7":"40.1","8":"9.7","9":"49.800000","10":"54146","11":"9573","12":"7353","13":"2220","14":"23.190220","15":"49201","16":"5.733341","17":"8.498502","18":"10.89944"},{"1":"38090","2":"989","3":"51.7","4":"37.9","5":"364","6":"4757.82","7":"39.3","8":"6.6","9":"45.900000","10":"39536","11":"4805","12":"2718","13":"2087","14":"43.433920","15":"49202","16":"5.897154","17":"8.467545","18":"10.58497"},{"1":"38170","2":"1793","3":"76.7","4":"36.2","5":"616","6":"5830.30","7":"70.8","8":"10.4","9":"81.200000","10":"39536","11":"4805","12":"2718","13":"2087","14":"43.433920","15":"49202","16":"6.423247","17":"8.670824","18":"10.58497"},{"1":"38170","2":"5802","3":"56.0","4":"33.3","5":"760","6":"4812.44","7":"73.4","8":"10.8","9":"84.200000","10":"39536","11":"4805","12":"2718","13":"2087","14":"43.433920","15":"49202","16":"6.633318","17":"8.478959","18":"10.58497"},{"1":"38140","2":"6116","3":"73.0","4":"55.4","5":"605","6":"4049.48","7":"21.5","8":"6.9","9":"28.400000","10":"39536","11":"4805","12":"2718","13":"2087","14":"43.433920","15":"49202","16":"6.405229","17":"8.306344","18":"10.58497"},{"1":"38170","2":"1334","3":"66.3","4":"47.3","5":"830","6":"4821.26","7":"61.7","8":"9.2","9":"70.900000","10":"47305","11":"9851","12":"6374","13":"3477","14":"35.295910","15":"49203","16":"6.721426","17":"8.480790","18":"10.76437"},{"1":"38170","2":"2471","3":"54.5","4":"30.3","5":"210","6":"5421.55","7":"88.1","8":"9.5","9":"97.600000","10":"47305","11":"9851","12":"6374","13":"3477","14":"35.295910","15":"49203","16":"5.347107","17":"8.598137","18":"10.76437"},{"1":"38020","2":"1254","3":"74.3","4":"47.6","5":"678","6":"4064.82","7":"24.2","8":"7.4","9":"31.600000","10":"47305","11":"9851","12":"6374","13":"3477","14":"35.295910","15":"49203","16":"6.519147","17":"8.310124","18":"10.76437"},{"1":"38040","2":"412","3":"69.8","4":"67.4","5":"478","6":"3869.58","7":"14.2","8":"5.4","9":"19.600000","10":"57266","11":"2023","12":"1620","13":"403","14":"19.920910","15":"49230","16":"6.169611","17":"8.260901","18":"10.95546"},{"1":"38040","2":"578","3":"72.7","4":"53.0","5":"395","6":"4455.49","7":"12.2","8":"5.3","9":"17.500000","10":"45278","11":"343","12":"282","13":"61","14":"17.784260","15":"49233","16":"5.978886","17":"8.401893","18":"10.72058"},{"1":"38080","2":"767","3":"68.1","4":"44.9","5":"453","6":"3736.43","7":"15.0","8":"12.1","9":"27.100000","10":"54491","11":"827","12":"688","13":"139","14":"16.807740","15":"49237","16":"6.115892","17":"8.225886","18":"10.90579"},{"1":"38050","2":"1382","3":"63.5","4":"48.6","5":"524","6":"3966.26","7":"8.4","8":"3.4","9":"11.800000","10":"63770","11":"1675","12":"1479","13":"196","14":"11.701490","15":"49240","16":"6.261492","17":"8.285579","18":"11.06304"},{"1":"38120","2":"3138","3":"51.9","4":"35.6","5":"520","6":"4104.29","7":"24.8","8":"10.2","9":"35.000000","10":"47727","11":"778","12":"606","13":"172","14":"22.107970","15":"49254","16":"6.253829","17":"8.319788","18":"10.77325"},{"1":"38010","2":"2965","3":"81.6","4":"61.2","5":"404","6":"3379.16","7":"13.9","8":"7.7","9":"21.600000","10":"52892","11":"1834","12":"1459","13":"375","14":"20.447110","15":"49269","16":"6.001415","17":"8.125382","18":"10.87601"},{"1":"38010","2":"236","3":"94.2","4":"84.6","5":"367","6":"3973.37","7":"25.1","8":"9.3","9":"34.400000","10":"59479","11":"594","12":"490","13":"104","14":"17.508420","15":"49283","16":"5.905362","17":"8.287370","18":"10.99338"},{"1":"38010","2":"4352","3":"75.9","4":"58.5","5":"403","6":"3471.11","7":"20.8","8":"5.5","9":"26.300000","10":"59479","11":"594","12":"490","13":"104","14":"17.508420","15":"49283","16":"5.998937","17":"8.152229","18":"10.99338"},{"1":"38150","2":"3573","3":"80.0","4":"56.0","5":"494","6":"3967.85","7":"32.2","8":"9.7","9":"41.900000","10":"44943","11":"723","12":"544","13":"179","14":"24.757950","15":"49284","16":"6.202536","17":"8.285979","18":"10.71315"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>help(meapsingle)</code></pre>
<p>math4, pctsgle, lmedinc ve free değişkenlerinin ne anlama geldikleri</p>
<p>-math4: percent satisfactory, 4th grade math, matematik başarı yüzdesi
-pctsgle: percent of children not in married-couple families, evli-çift ailelerde olmayan çocukların yüzdesi
-lmedinc: log(medinc), medinc: zipcode median family, $ (1999), bölgenin ortanca geliri
-free: percent eligible, free lunch, bedava öğle yemeğine uygun görülen yüzdesi</p>
<ol start="2" style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>basitreg3&lt;- lm(math4~pctsgle, data = meapsingle)
summary(basitreg3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = math4 ~ pctsgle, data = meapsingle)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -47.791  -8.310   1.600   8.092  50.317 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 96.77043    1.59680   60.60   &lt;2e-16 ***
## pctsgle     -0.83288    0.07068  -11.78   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.48 on 227 degrees of freedom
## Multiple R-squared:  0.3795, Adjusted R-squared:  0.3768 
## F-statistic: 138.9 on 1 and 227 DF,  p-value: &lt; 2.2e-16</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>coklureg3&lt;- lm(math4~pctsgle+lmedinc+free, data = meapsingle)
summary(coklureg3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = math4 ~ pctsgle + lmedinc + free, data = meapsingle)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -34.919  -7.195   0.931   7.313  50.152 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 51.72322   58.47814   0.884    0.377    
## pctsgle     -0.19965    0.15872  -1.258    0.210    
## lmedinc      3.56013    5.04170   0.706    0.481    
## free        -0.39642    0.07035  -5.635  5.2e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.7 on 225 degrees of freedom
## Multiple R-squared:  0.4598, Adjusted R-squared:  0.4526 
## F-statistic: 63.85 on 3 and 225 DF,  p-value: &lt; 2.2e-16</code></pre>
<ol start="4" style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>cor(meapsingle$free,meapsingle$lmedinc)</code></pre>
<pre><code>## [1] -0.7469703</code></pre>
<ol start="5" style="list-style-type: lower-alpha">
<li></li>
</ol>
<pre class="r"><code>library(car)</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre class="r"><code>vif(coklureg3)</code></pre>
<pre><code>##  pctsgle  lmedinc     free 
## 5.740981 4.118812 3.188079</code></pre>
</div>
</div>
