---
title: "R ile Çoklu Regresyon Analizi: Çıkarım: (Wooldridge Örnekleri)"
author: "Dr. Hüseyin Utku Demir"
date: 2020-12-01T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
type: book
weight: 40
---
<link href="/rmarkdown-libs/pagedtable/css/pagedtable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/pagedtable/js/pagedtable.js"></script>
<link href="/rmarkdown-libs/pagedtable/css/pagedtable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/pagedtable/js/pagedtable.js"></script>

Bu bölümde, çoklu regresyon analizine devam ediyoruz. Popülasyon regresyon modelindeki parametrelerle ilgili hipotezleri test etmemiz gerekiyor. En küçük kareler yöntemiyle tahmin ettiğimiz parametrelerin dağılımlarına bakacağız ve normal dağılıp dağılmadığını anlamaya çalışacağız. Daha sonra parametrelerle ilgili hipotez testlerini oluşturacağız. 

<!--more-->

{{< icon name="clock" pack="fas" >}} Haftada 1-2 saat, 2 hafta için.

## En küçük kareler tahmincilerinin örneklem dağılımları

Bu bölüme başlamadan önce 6. varsayımımızı hatırlamamız gerekecek.

- Altıncı Varsayım (MLR.6): Normalite (Normality), popülasyon hatası $u$ açıklayıcı değişkenler, $x_1, x_2, ..., x_k$, den bağımsızdır ve ortalaması sıfır, varyansı $\delta^2$ olmak üzere normal dağılmıştır. ($u \sim Normal(0,\delta^2)$)

Eğer MLR.6 varsayımını kabul etmek, MLR.4 ve MLR.5 varsayımlarını kabul etmemizi zorunlu kılar. MLR.1'den MLR.6'ya kadar olab varsayımlar klasik lineer model (CLM) varsayımları olarak bilinir. Klasik lineer model (CLM) varsayımları bütün Gauss-Markov varsayımları artı normal dağılan hatalar varsayımı olarak da bilinir.

Klasik lineer model (CLM) varsayımları sağlandığında en küçük kareler (OLS) yöntemi en az varyansa sahip ve sapmasız tahminci olarak adlandırılabilir. Unutulmamalıdır ki, bu varsayım çok güçlü bir varsayımdır ve sağlanması oldukça zordur. Örneğin maaşlar böyle bir değişkendir. Popülasyonda bulunan bir çok kişi minimum ücret alır ve maaşların sıfırın altına düşmesi söz konusu değildir. Gelir eşitsizliğine de bakarsak, maaşlar sağ kuyruğa doğru da oldukça uzayabilir. 

## Tek Bir Popülasyon Parametresi Hakkında Hipotezlerin Test Edilmesi: t Testi

Çoklu popülasyon modelimizi hatırlayalım

$$
y= \beta_0 + \beta_1 x_1 + \beta_2 x_2  + \beta_3 x_3 + ... + \beta_k x_k  + u
$$

Bu bölümde herhangi bir $\beta_j$ parametresini test etmeyi öğreneceğiz.

CLM varsayımları sayesinde biliyoruz ki $\frac{\hat{\beta_j}-\beta_j}{se(\hat{\beta_j})} \sim Normal(0,1)$. Popülasyon için kullandığımız bu normal dağılım, örneklem için t-dağılımına dönüşür $\frac{\hat{\beta_j}-\beta_j}{se(\hat{\beta_j})} \sim t_{n-k-1}=t_{df}$. n-k-1 t-dağılımının esneklik derecesini (degrees of freedom, df) verir. n veri setinde kaç gözlem olduğunu, k modelimizde kaç bağımsız değişken olduğunu söyler. 


Bir örnek vermemiz gerekirse maaş veri seti üzerinden tartışabiliriz.


$$
maaş= \beta_0 + \beta_1 eğitim + \beta_2 deneyim  + \beta_3 iş.yılı + u
$$


Bir hipotez kurup test etmek istediğimizde, katsayılardan birini seçip $H_0$ nul hipotezini kurabiliriz.

Örneğin,

$H_0: \beta_2=0$, eğitim ve iş yılı sabit tutulduğunda, deneyimin saatlik maaşlar üzerinde hiçbir etkisi yoktur anlamı taşır. Eğer bu hipotez doğruysa, şu anda çalışdığı işten önce kişinin çalışmış olduğu yılların ücretin üzerinde hiçbir etkisi olmadığı anlamı çıkar. Eğer $\beta_2>0$ ise, önceki iş yılları, üretkenliğe dolayısıyla ücretlere pozitif etki yapmaktadır.

$H_0: \beta_2=0$ olup olmadığını test ettiğimize göre, t istatistiğini (t oranı) şu şekide bulabiliriz.

$t_{\hat{\beta_j}} = \frac{\hat{\beta_j}}{se(\hat{\beta_j})}$

$\beta_2$'nun sıfır olup olmadığını ($\beta_2 \neq 0$) test etmek için $t_{\hat{\beta_j}}$ iyi bir araç mı? $H_0: \beta_2=0$ test ediyoruz, fakat gerçek $\beta_2$ değerini bilmiyoruz. Ancak elimizde $\beta_2$ değerinin en iyi sapmasız tahmini $\hat{\beta_j}$ var. $H_0: \beta_2=0$ gerçek olsa bile, biz asla bu gerçek değere sahip olan bir $\hat{\beta_j}$ değerine sahip olamıyacağız. Asıl sormamız gereken soru, tahminimiz $\hat{\beta_j}$'nin sıfıra ne kadar yakın olduğu. Bu ölçünün uzaklığını bize ancak standart hata değeri verebilir. Standar hata sayesinde $\hat{\beta_j}$ değerinin sıfırdan kaç standart sapma uzak olduğunu hesaplayabiliriz. Bu kaç standart sapma uzaklıkta oldğunu veren değer $t_{\hat{\beta_j}}$ değeridir. $t_{\hat{\beta_j}}$ değeri ne kadar büyükse, gerçek parametre değerimiz sıfırdan o kadar uzaktır ve $H_0: \beta_2=0$ hipotezini reddetmemiz için o kadar kanıt sağlar.

### Örnek 4.1 Saatlik Maaş Denklemi

Wooldridge wage1 datasını kullanalım.


```r
library(wooldridge)
data(wage1)
```

Verilere bir göz gezdirin.


```r
library(rmarkdown)
paged_table(wage1)
```

<div data-pagedtable="false">
  <script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["wage"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["educ"],"name":[2],"type":["int"],"align":["right"]},{"label":["exper"],"name":[3],"type":["int"],"align":["right"]},{"label":["tenure"],"name":[4],"type":["int"],"align":["right"]},{"label":["nonwhite"],"name":[5],"type":["int"],"align":["right"]},{"label":["female"],"name":[6],"type":["int"],"align":["right"]},{"label":["married"],"name":[7],"type":["int"],"align":["right"]},{"label":["numdep"],"name":[8],"type":["int"],"align":["right"]},{"label":["smsa"],"name":[9],"type":["int"],"align":["right"]},{"label":["northcen"],"name":[10],"type":["int"],"align":["right"]},{"label":["south"],"name":[11],"type":["int"],"align":["right"]},{"label":["west"],"name":[12],"type":["int"],"align":["right"]},{"label":["construc"],"name":[13],"type":["int"],"align":["right"]},{"label":["ndurman"],"name":[14],"type":["int"],"align":["right"]},{"label":["trcommpu"],"name":[15],"type":["int"],"align":["right"]},{"label":["trade"],"name":[16],"type":["int"],"align":["right"]},{"label":["services"],"name":[17],"type":["int"],"align":["right"]},{"label":["profserv"],"name":[18],"type":["int"],"align":["right"]},{"label":["profocc"],"name":[19],"type":["int"],"align":["right"]},{"label":["clerocc"],"name":[20],"type":["int"],"align":["right"]},{"label":["servocc"],"name":[21],"type":["int"],"align":["right"]},{"label":["lwage"],"name":[22],"type":["dbl"],"align":["right"]},{"label":["expersq"],"name":[23],"type":["int"],"align":["right"]},{"label":["tenursq"],"name":[24],"type":["int"],"align":["right"]}],"data":[{"1":"3.10","2":"11","3":"2","4":"0","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.1314021","23":"4","24":"0","_rn_":"1"},{"1":"3.24","2":"12","3":"22","4":"2","5":"0","6":"1","7":"1","8":"3","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.1755733","23":"484","24":"4","_rn_":"2"},{"1":"3.00","2":"11","3":"2","4":"0","5":"0","6":"0","7":"0","8":"2","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"4","24":"0","_rn_":"3"},{"1":"6.00","2":"8","3":"44","4":"28","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.7917595","23":"1936","24":"784","_rn_":"4"},{"1":"5.30","2":"12","3":"7","4":"2","5":"0","6":"0","7":"1","8":"1","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6677068","23":"49","24":"4","_rn_":"5"},{"1":"8.75","2":"16","3":"9","4":"8","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.1690538","23":"81","24":"64","_rn_":"6"},{"1":"11.25","2":"18","3":"15","4":"7","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.4203682","23":"225","24":"49","_rn_":"7"},{"1":"5.00","2":"12","3":"5","4":"3","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.6094379","23":"25","24":"9","_rn_":"8"},{"1":"3.60","2":"12","3":"26","4":"4","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.2809339","23":"676","24":"16","_rn_":"9"},{"1":"18.18","2":"17","3":"22","4":"21","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.9003222","23":"484","24":"441","_rn_":"10"},{"1":"6.25","2":"16","3":"8","4":"2","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8325815","23":"64","24":"4","_rn_":"11"},{"1":"8.13","2":"13","3":"3","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"2.0955610","23":"9","24":"0","_rn_":"12"},{"1":"8.77","2":"12","3":"15","4":"0","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.1713369","23":"225","24":"0","_rn_":"13"},{"1":"5.50","2":"12","3":"18","4":"3","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7047480","23":"324","24":"9","_rn_":"14"},{"1":"22.20","2":"12","3":"31","4":"15","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"3.1000924","23":"961","24":"225","_rn_":"15"},{"1":"17.33","2":"16","3":"14","4":"0","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.8524392","23":"196","24":"0","_rn_":"16"},{"1":"7.50","2":"12","3":"10","4":"0","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"2.0149031","23":"100","24":"0","_rn_":"17"},{"1":"10.63","2":"13","3":"16","4":"10","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.3636801","23":"256","24":"100","_rn_":"18"},{"1":"3.60","2":"12","3":"13","4":"0","5":"0","6":"1","7":"1","8":"3","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2809339","23":"169","24":"0","_rn_":"19"},{"1":"4.50","2":"12","3":"36","4":"6","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.5040774","23":"1296","24":"36","_rn_":"20"},{"1":"6.88","2":"12","3":"11","4":"4","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.9286187","23":"121","24":"16","_rn_":"21"},{"1":"8.48","2":"12","3":"29","4":"13","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.1377103","23":"841","24":"169","_rn_":"22"},{"1":"6.33","2":"16","3":"9","4":"9","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8453002","23":"81","24":"81","_rn_":"23"},{"1":"0.53","2":"12","3":"3","4":"1","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"-0.6348783","23":"9","24":"1","_rn_":"24"},{"1":"6.00","2":"11","3":"37","4":"8","5":"1","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.7917595","23":"1369","24":"64","_rn_":"25"},{"1":"9.56","2":"16","3":"3","4":"3","5":"1","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.2575877","23":"9","24":"9","_rn_":"26"},{"1":"7.78","2":"16","3":"11","4":"10","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.0515563","23":"121","24":"100","_rn_":"27"},{"1":"12.50","2":"16","3":"31","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.5257287","23":"961","24":"0","_rn_":"28"},{"1":"12.50","2":"15","3":"30","4":"0","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.5257287","23":"900","24":"0","_rn_":"29"},{"1":"3.25","2":"8","3":"9","4":"1","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.1786550","23":"81","24":"1","_rn_":"30"},{"1":"13.00","2":"14","3":"23","4":"5","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.5649493","23":"529","24":"25","_rn_":"31"},{"1":"4.50","2":"14","3":"2","4":"5","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5040774","23":"4","24":"25","_rn_":"32"},{"1":"9.68","2":"13","3":"16","4":"16","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.2700620","23":"256","24":"256","_rn_":"33"},{"1":"5.00","2":"12","3":"7","4":"3","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.6094379","23":"49","24":"9","_rn_":"34"},{"1":"4.68","2":"12","3":"3","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"0","22":"1.5432981","23":"9","24":"0","_rn_":"35"},{"1":"4.27","2":"16","3":"22","4":"4","5":"1","6":"1","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.4516138","23":"484","24":"16","_rn_":"36"},{"1":"6.15","2":"12","3":"15","4":"6","5":"1","6":"1","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.8164521","23":"225","24":"36","_rn_":"37"},{"1":"3.51","2":"4","3":"39","4":"15","5":"0","6":"0","7":"1","8":"5","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2556161","23":"1521","24":"225","_rn_":"38"},{"1":"3.00","2":"14","3":"3","4":"3","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.0986123","23":"9","24":"9","_rn_":"39"},{"1":"6.25","2":"12","3":"11","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.8325815","23":"121","24":"0","_rn_":"40"},{"1":"7.81","2":"12","3":"3","4":"0","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"2.0554049","23":"9","24":"0","_rn_":"41"},{"1":"10.00","2":"12","3":"20","4":"5","5":"1","6":"1","7":"1","8":"4","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"2.3025851","23":"400","24":"25","_rn_":"42"},{"1":"4.50","2":"14","3":"16","4":"0","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.5040774","23":"256","24":"0","_rn_":"43"},{"1":"4.00","2":"11","3":"45","4":"12","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.3862944","23":"2025","24":"144","_rn_":"44"},{"1":"6.38","2":"13","3":"11","4":"4","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8531681","23":"121","24":"16","_rn_":"45"},{"1":"13.70","2":"15","3":"20","4":"13","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.6173959","23":"400","24":"169","_rn_":"46"},{"1":"1.67","2":"10","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"0.5128236","23":"1","24":"0","_rn_":"47"},{"1":"2.93","2":"12","3":"36","4":"2","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.0750024","23":"1296","24":"4","_rn_":"48"},{"1":"3.65","2":"14","3":"9","4":"2","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.2947272","23":"81","24":"4","_rn_":"49"},{"1":"2.90","2":"12","3":"15","4":"1","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.0647107","23":"225","24":"1","_rn_":"50"},{"1":"1.63","2":"12","3":"18","4":"0","5":"0","6":"1","7":"0","8":"2","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"0.4885800","23":"324","24":"0","_rn_":"51"},{"1":"8.60","2":"16","3":"3","4":"2","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.1517622","23":"9","24":"4","_rn_":"52"},{"1":"5.00","2":"12","3":"15","4":"5","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.6094379","23":"225","24":"25","_rn_":"53"},{"1":"6.00","2":"12","3":"7","4":"7","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7917595","23":"49","24":"49","_rn_":"54"},{"1":"2.50","2":"12","3":"2","4":"0","5":"0","6":"0","7":"0","8":"2","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"0.9162908","23":"4","24":"0","_rn_":"55"},{"1":"3.25","2":"15","3":"3","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.1786550","23":"9","24":"0","_rn_":"56"},{"1":"3.40","2":"16","3":"1","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.2237755","23":"1","24":"1","_rn_":"57"},{"1":"10.00","2":"8","3":"13","4":"0","5":"1","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.3025851","23":"169","24":"0","_rn_":"58"},{"1":"21.63","2":"18","3":"8","4":"8","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"3.0740812","23":"64","24":"64","_rn_":"59"},{"1":"4.38","2":"16","3":"7","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.4770488","23":"49","24":"0","_rn_":"60"},{"1":"11.71","2":"13","3":"40","4":"20","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.4604433","23":"1600","24":"400","_rn_":"61"},{"1":"12.39","2":"14","3":"42","4":"5","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.5168898","23":"1764","24":"25","_rn_":"62"},{"1":"6.25","2":"10","3":"36","4":"8","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.8325815","23":"1296","24":"64","_rn_":"63"},{"1":"3.71","2":"10","3":"13","4":"0","5":"1","6":"1","7":"0","8":"4","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.3110319","23":"169","24":"0","_rn_":"64"},{"1":"7.78","2":"14","3":"9","4":"3","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.0515563","23":"81","24":"9","_rn_":"65"},{"1":"19.98","2":"14","3":"26","4":"23","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.9947317","23":"676","24":"529","_rn_":"66"},{"1":"6.25","2":"16","3":"7","4":"4","5":"1","6":"1","7":"1","8":"3","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8325815","23":"49","24":"16","_rn_":"67"},{"1":"10.00","2":"12","3":"25","4":"3","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.3025851","23":"625","24":"9","_rn_":"68"},{"1":"5.71","2":"16","3":"10","4":"5","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.7422190","23":"100","24":"25","_rn_":"69"},{"1":"2.00","2":"12","3":"3","4":"2","5":"0","6":"1","7":"0","8":"4","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"0.6931472","23":"9","24":"4","_rn_":"70"},{"1":"5.71","2":"16","3":"3","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.7422190","23":"9","24":"0","_rn_":"71"},{"1":"13.08","2":"17","3":"17","4":"2","5":"1","6":"0","7":"1","8":"3","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.5710843","23":"289","24":"4","_rn_":"72"},{"1":"4.91","2":"12","3":"17","4":"8","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5912739","23":"289","24":"64","_rn_":"73"},{"1":"2.91","2":"12","3":"20","4":"34","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"0","22":"1.0681531","23":"400","24":"1156","_rn_":"74"},{"1":"3.75","2":"12","3":"7","4":"0","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.3217559","23":"49","24":"0","_rn_":"75"},{"1":"11.90","2":"13","3":"24","4":"19","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.4765384","23":"576","24":"361","_rn_":"76"},{"1":"4.00","2":"12","3":"28","4":"0","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.3862944","23":"784","24":"0","_rn_":"77"},{"1":"3.10","2":"12","3":"2","4":"1","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.1314021","23":"4","24":"1","_rn_":"78"},{"1":"8.45","2":"12","3":"19","4":"13","5":"0","6":"0","7":"1","8":"4","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.1341665","23":"361","24":"169","_rn_":"79"},{"1":"7.14","2":"18","3":"13","4":"0","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.9657128","23":"169","24":"0","_rn_":"80"},{"1":"4.50","2":"9","3":"22","4":"5","5":"0","6":"0","7":"1","8":"4","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5040774","23":"484","24":"25","_rn_":"81"},{"1":"4.65","2":"16","3":"3","4":"1","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5368673","23":"9","24":"1","_rn_":"82"},{"1":"2.90","2":"10","3":"4","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.0647107","23":"16","24":"0","_rn_":"83"},{"1":"6.67","2":"12","3":"7","4":"5","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8976198","23":"49","24":"25","_rn_":"84"},{"1":"3.50","2":"12","3":"6","4":"2","5":"1","6":"1","7":"0","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.2527629","23":"36","24":"4","_rn_":"85"},{"1":"3.26","2":"12","3":"13","4":"3","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.1817272","23":"169","24":"9","_rn_":"86"},{"1":"3.25","2":"12","3":"14","4":"0","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.1786550","23":"196","24":"0","_rn_":"87"},{"1":"8.00","2":"12","3":"14","4":"4","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.0794415","23":"196","24":"16","_rn_":"88"},{"1":"9.85","2":"8","3":"40","4":"24","5":"1","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.2874715","23":"1600","24":"576","_rn_":"89"},{"1":"7.50","2":"12","3":"11","4":"7","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.0149031","23":"121","24":"49","_rn_":"90"},{"1":"5.91","2":"12","3":"14","4":"6","5":"0","6":"0","7":"1","8":"2","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7766458","23":"196","24":"36","_rn_":"91"},{"1":"11.76","2":"14","3":"40","4":"39","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.4647040","23":"1600","24":"1521","_rn_":"92"},{"1":"3.00","2":"12","3":"1","4":"0","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.0986123","23":"1","24":"0","_rn_":"93"},{"1":"4.81","2":"12","3":"2","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.5706971","23":"4","24":"0","_rn_":"94"},{"1":"6.50","2":"12","3":"4","4":"1","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8718022","23":"16","24":"1","_rn_":"95"},{"1":"4.00","2":"9","3":"19","4":"1","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.3862944","23":"361","24":"1","_rn_":"96"},{"1":"3.50","2":"13","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.2527629","23":"1","24":"0","_rn_":"97"},{"1":"13.16","2":"12","3":"34","4":"22","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.5771818","23":"1156","24":"484","_rn_":"98"},{"1":"4.25","2":"14","3":"5","4":"2","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.4469190","23":"25","24":"4","_rn_":"99"},{"1":"3.50","2":"12","3":"3","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.2527629","23":"9","24":"0","_rn_":"100"},{"1":"5.13","2":"15","3":"6","4":"6","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.6351057","23":"36","24":"36","_rn_":"101"},{"1":"3.75","2":"12","3":"14","4":"0","5":"0","6":"1","7":"1","8":"3","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.3217559","23":"196","24":"0","_rn_":"102"},{"1":"4.50","2":"12","3":"35","4":"12","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.5040774","23":"1225","24":"144","_rn_":"103"},{"1":"7.63","2":"12","3":"8","4":"4","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"2.0320878","23":"64","24":"16","_rn_":"104"},{"1":"15.00","2":"14","3":"7","4":"7","5":"1","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.7080503","23":"49","24":"49","_rn_":"105"},{"1":"6.85","2":"15","3":"11","4":"3","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.9242487","23":"121","24":"9","_rn_":"106"},{"1":"13.33","2":"12","3":"14","4":"11","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.5900171","23":"196","24":"121","_rn_":"107"},{"1":"6.67","2":"12","3":"35","4":"10","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8976198","23":"1225","24":"100","_rn_":"108"},{"1":"2.53","2":"12","3":"46","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"0.9282193","23":"2116","24":"0","_rn_":"109"},{"1":"9.80","2":"17","3":"7","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"2.2823825","23":"49","24":"0","_rn_":"110"},{"1":"3.37","2":"11","3":"45","4":"12","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.2149127","23":"2025","24":"144","_rn_":"111"},{"1":"24.98","2":"18","3":"29","4":"25","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"3.2180755","23":"841","24":"625","_rn_":"112"},{"1":"5.40","2":"12","3":"6","4":"3","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.6863990","23":"36","24":"9","_rn_":"113"},{"1":"6.11","2":"14","3":"15","4":"0","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8099267","23":"225","24":"0","_rn_":"114"},{"1":"4.20","2":"14","3":"33","4":"16","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.4350845","23":"1089","24":"256","_rn_":"115"},{"1":"3.75","2":"10","3":"15","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3217559","23":"225","24":"0","_rn_":"116"},{"1":"3.50","2":"14","3":"5","4":"0","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.2527629","23":"25","24":"0","_rn_":"117"},{"1":"3.64","2":"12","3":"7","4":"2","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.2919837","23":"49","24":"4","_rn_":"118"},{"1":"3.80","2":"15","3":"6","4":"1","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3350011","23":"36","24":"1","_rn_":"119"},{"1":"3.00","2":"8","3":"33","4":"12","5":"0","6":"1","7":"1","8":"3","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"1089","24":"144","_rn_":"120"},{"1":"5.00","2":"16","3":"2","4":"1","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.6094379","23":"4","24":"1","_rn_":"121"},{"1":"4.63","2":"14","3":"4","4":"0","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.5325569","23":"16","24":"0","_rn_":"122"},{"1":"3.00","2":"15","3":"1","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.0986123","23":"1","24":"0","_rn_":"123"},{"1":"3.20","2":"12","3":"29","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.1631508","23":"841","24":"0","_rn_":"124"},{"1":"3.91","2":"18","3":"17","4":"3","5":"0","6":"0","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.3635374","23":"289","24":"9","_rn_":"125"},{"1":"6.43","2":"16","3":"17","4":"3","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8609746","23":"289","24":"9","_rn_":"126"},{"1":"5.48","2":"10","3":"36","4":"3","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7011051","23":"1296","24":"9","_rn_":"127"},{"1":"1.50","2":"8","3":"31","4":"30","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"0.4054651","23":"961","24":"900","_rn_":"128"},{"1":"2.90","2":"10","3":"23","4":"2","5":"0","6":"1","7":"0","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.0647107","23":"529","24":"4","_rn_":"129"},{"1":"5.00","2":"11","3":"13","4":"1","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6094379","23":"169","24":"1","_rn_":"130"},{"1":"8.92","2":"18","3":"3","4":"3","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.1882958","23":"9","24":"9","_rn_":"131"},{"1":"5.00","2":"15","3":"15","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.6094379","23":"225","24":"0","_rn_":"132"},{"1":"3.52","2":"12","3":"48","4":"1","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"0","22":"1.2584610","23":"2304","24":"1","_rn_":"133"},{"1":"2.90","2":"11","3":"6","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0647107","23":"36","24":"0","_rn_":"134"},{"1":"4.50","2":"12","3":"12","4":"0","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5040774","23":"144","24":"0","_rn_":"135"},{"1":"2.25","2":"12","3":"5","4":"0","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"0.8109302","23":"25","24":"0","_rn_":"136"},{"1":"5.00","2":"14","3":"19","4":"5","5":"0","6":"0","7":"1","8":"4","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6094379","23":"361","24":"25","_rn_":"137"},{"1":"10.00","2":"16","3":"9","4":"3","5":"1","6":"0","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.3025851","23":"81","24":"9","_rn_":"138"},{"1":"3.75","2":"2","3":"39","4":"13","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.3217559","23":"1521","24":"169","_rn_":"139"},{"1":"10.00","2":"14","3":"28","4":"11","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.3025851","23":"784","24":"121","_rn_":"140"},{"1":"10.95","2":"16","3":"23","4":"20","5":"0","6":"0","7":"1","8":"4","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.3933394","23":"529","24":"400","_rn_":"141"},{"1":"7.90","2":"12","3":"2","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.0668628","23":"4","24":"0","_rn_":"142"},{"1":"4.72","2":"12","3":"15","4":"1","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5518087","23":"225","24":"1","_rn_":"143"},{"1":"5.84","2":"13","3":"5","4":"0","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.7647308","23":"25","24":"0","_rn_":"144"},{"1":"3.83","2":"12","3":"18","4":"2","5":"0","6":"1","7":"0","8":"3","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.3428648","23":"324","24":"4","_rn_":"145"},{"1":"3.20","2":"15","3":"2","4":"2","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.1631508","23":"4","24":"4","_rn_":"146"},{"1":"2.00","2":"10","3":"3","4":"0","5":"1","6":"1","7":"0","8":"5","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"0.6931472","23":"9","24":"0","_rn_":"147"},{"1":"4.50","2":"12","3":"31","4":"4","5":"0","6":"1","7":"1","8":"3","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.5040774","23":"961","24":"16","_rn_":"148"},{"1":"11.55","2":"16","3":"20","4":"5","5":"0","6":"1","7":"1","8":"3","9":"1","10":"0","11":"1","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"2.4466856","23":"400","24":"25","_rn_":"149"},{"1":"2.14","2":"13","3":"34","4":"15","5":"1","6":"1","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"0.7608059","23":"1156","24":"225","_rn_":"150"},{"1":"2.38","2":"9","3":"5","4":"0","5":"1","6":"0","7":"0","8":"5","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"0.8671005","23":"25","24":"0","_rn_":"151"},{"1":"3.75","2":"12","3":"11","4":"0","5":"0","6":"0","7":"0","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3217559","23":"121","24":"0","_rn_":"152"},{"1":"5.52","2":"13","3":"31","4":"3","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7083778","23":"961","24":"9","_rn_":"153"},{"1":"6.50","2":"12","3":"8","4":"5","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.8718022","23":"64","24":"25","_rn_":"154"},{"1":"3.10","2":"12","3":"2","4":"2","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.1314021","23":"4","24":"4","_rn_":"155"},{"1":"10.00","2":"14","3":"18","4":"5","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.3025851","23":"324","24":"25","_rn_":"156"},{"1":"6.63","2":"16","3":"3","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8916048","23":"9","24":"0","_rn_":"157"},{"1":"10.00","2":"16","3":"3","4":"2","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.3025851","23":"9","24":"4","_rn_":"158"},{"1":"2.31","2":"9","3":"4","4":"1","5":"0","6":"1","7":"0","8":"5","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"0.8372475","23":"16","24":"1","_rn_":"159"},{"1":"6.88","2":"18","3":"4","4":"4","5":"0","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.9286187","23":"16","24":"16","_rn_":"160"},{"1":"2.83","2":"10","3":"1","4":"0","5":"0","6":"0","7":"0","8":"4","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0402766","23":"1","24":"0","_rn_":"161"},{"1":"3.13","2":"10","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.1410331","23":"1","24":"0","_rn_":"162"},{"1":"8.00","2":"13","3":"28","4":"5","5":"0","6":"0","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"2.0794415","23":"784","24":"25","_rn_":"163"},{"1":"4.50","2":"12","3":"47","4":"4","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.5040774","23":"2209","24":"16","_rn_":"164"},{"1":"8.65","2":"18","3":"13","4":"1","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.1575594","23":"169","24":"1","_rn_":"165"},{"1":"2.00","2":"13","3":"2","4":"6","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"0.6931472","23":"4","24":"36","_rn_":"166"},{"1":"4.75","2":"12","3":"48","4":"2","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.5581446","23":"2304","24":"4","_rn_":"167"},{"1":"6.25","2":"13","3":"6","4":"5","5":"0","6":"1","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8325815","23":"36","24":"25","_rn_":"168"},{"1":"6.00","2":"13","3":"8","4":"0","5":"0","6":"0","7":"1","8":"2","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.7917595","23":"64","24":"0","_rn_":"169"},{"1":"15.38","2":"13","3":"25","4":"21","5":"0","6":"0","7":"1","8":"2","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.7330680","23":"625","24":"441","_rn_":"170"},{"1":"14.58","2":"18","3":"13","4":"7","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.6796508","23":"169","24":"49","_rn_":"171"},{"1":"12.50","2":"12","3":"8","4":"1","5":"0","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.5257287","23":"64","24":"1","_rn_":"172"},{"1":"5.25","2":"12","3":"19","4":"10","5":"0","6":"1","7":"1","8":"2","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.6582280","23":"361","24":"100","_rn_":"173"},{"1":"2.17","2":"13","3":"1","4":"4","5":"0","6":"1","7":"0","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"0.7747272","23":"1","24":"16","_rn_":"174"},{"1":"7.14","2":"12","3":"43","4":"5","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.9657128","23":"1849","24":"25","_rn_":"175"},{"1":"6.22","2":"12","3":"19","4":"9","5":"0","6":"1","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.8277699","23":"361","24":"81","_rn_":"176"},{"1":"9.00","2":"12","3":"11","4":"5","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.1972246","23":"121","24":"25","_rn_":"177"},{"1":"10.00","2":"14","3":"43","4":"4","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.3025851","23":"1849","24":"16","_rn_":"178"},{"1":"5.77","2":"10","3":"44","4":"3","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.7526721","23":"1936","24":"9","_rn_":"179"},{"1":"4.00","2":"12","3":"22","4":"11","5":"0","6":"1","7":"1","8":"2","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3862944","23":"484","24":"121","_rn_":"180"},{"1":"8.75","2":"16","3":"3","4":"2","5":"0","6":"0","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.1690538","23":"9","24":"4","_rn_":"181"},{"1":"6.53","2":"16","3":"3","4":"2","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8764070","23":"9","24":"4","_rn_":"182"},{"1":"7.60","2":"12","3":"41","4":"11","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.0281482","23":"1681","24":"121","_rn_":"183"},{"1":"5.00","2":"14","3":"5","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6094379","23":"25","24":"0","_rn_":"184"},{"1":"5.00","2":"12","3":"14","4":"11","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.6094379","23":"196","24":"121","_rn_":"185"},{"1":"21.86","2":"12","3":"24","4":"16","5":"0","6":"0","7":"1","8":"3","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"3.0846586","23":"576","24":"256","_rn_":"186"},{"1":"8.64","2":"12","3":"28","4":"8","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.1564026","23":"784","24":"64","_rn_":"187"},{"1":"3.30","2":"12","3":"25","4":"8","5":"0","6":"0","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.1939224","23":"625","24":"64","_rn_":"188"},{"1":"4.44","2":"12","3":"3","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.4906543","23":"9","24":"0","_rn_":"189"},{"1":"4.55","2":"12","3":"11","4":"0","5":"0","6":"0","7":"1","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5151273","23":"121","24":"0","_rn_":"190"},{"1":"3.50","2":"12","3":"7","4":"6","5":"1","6":"1","7":"1","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2527629","23":"49","24":"36","_rn_":"191"},{"1":"6.25","2":"16","3":"9","4":"2","5":"0","6":"0","7":"1","8":"1","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8325815","23":"81","24":"4","_rn_":"192"},{"1":"3.85","2":"16","3":"5","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3480731","23":"25","24":"0","_rn_":"193"},{"1":"6.18","2":"14","3":"9","4":"3","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8213183","23":"81","24":"9","_rn_":"194"},{"1":"2.91","2":"11","3":"1","4":"0","5":"0","6":"1","7":"0","8":"3","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"1.0681531","23":"1","24":"0","_rn_":"195"},{"1":"6.25","2":"16","3":"2","4":"1","5":"1","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8325815","23":"4","24":"1","_rn_":"196"},{"1":"6.25","2":"12","3":"13","4":"0","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.8325815","23":"169","24":"0","_rn_":"197"},{"1":"9.05","2":"12","3":"10","4":"2","5":"0","6":"0","7":"1","8":"3","9":"1","10":"1","11":"0","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.2027647","23":"100","24":"4","_rn_":"198"},{"1":"10.00","2":"17","3":"5","4":"3","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.3025851","23":"25","24":"9","_rn_":"199"},{"1":"11.11","2":"12","3":"30","4":"8","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.4078455","23":"900","24":"64","_rn_":"200"},{"1":"6.88","2":"12","3":"31","4":"19","5":"0","6":"0","7":"1","8":"3","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.9286187","23":"961","24":"361","_rn_":"201"},{"1":"8.75","2":"16","3":"1","4":"2","5":"1","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.1690538","23":"1","24":"4","_rn_":"202"},{"1":"10.00","2":"8","3":"9","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.3025851","23":"81","24":"0","_rn_":"203"},{"1":"3.05","2":"12","3":"10","4":"0","5":"0","6":"1","7":"1","8":"2","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.1151416","23":"100","24":"0","_rn_":"204"},{"1":"3.00","2":"12","3":"38","4":"0","5":"0","6":"1","7":"1","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"0","22":"1.0986123","23":"1444","24":"0","_rn_":"205"},{"1":"5.80","2":"12","3":"19","4":"6","5":"0","6":"1","7":"1","8":"2","9":"0","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7578579","23":"361","24":"36","_rn_":"206"},{"1":"4.10","2":"16","3":"5","4":"0","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.4109869","23":"25","24":"0","_rn_":"207"},{"1":"8.00","2":"12","3":"26","4":"2","5":"0","6":"0","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.0794415","23":"676","24":"4","_rn_":"208"},{"1":"6.15","2":"12","3":"35","4":"12","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8164521","23":"1225","24":"144","_rn_":"209"},{"1":"2.70","2":"9","3":"2","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"0.9932518","23":"4","24":"0","_rn_":"210"},{"1":"2.75","2":"13","3":"1","4":"2","5":"0","6":"1","7":"0","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.0116010","23":"1","24":"4","_rn_":"211"},{"1":"3.00","2":"16","3":"19","4":"10","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.0986123","23":"361","24":"100","_rn_":"212"},{"1":"3.00","2":"14","3":"3","4":"2","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.0986123","23":"9","24":"4","_rn_":"213"},{"1":"7.36","2":"8","3":"36","4":"24","5":"0","6":"0","7":"1","8":"3","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.9960599","23":"1296","24":"576","_rn_":"214"},{"1":"7.50","2":"14","3":"29","4":"24","5":"0","6":"0","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.0149031","23":"841","24":"576","_rn_":"215"},{"1":"3.50","2":"13","3":"1","4":"2","5":"0","6":"0","7":"0","8":"3","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2527629","23":"1","24":"4","_rn_":"216"},{"1":"8.10","2":"12","3":"38","4":"3","5":"0","6":"1","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.0918641","23":"1444","24":"9","_rn_":"217"},{"1":"3.75","2":"18","3":"1","4":"2","5":"0","6":"0","7":"0","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.3217559","23":"1","24":"4","_rn_":"218"},{"1":"3.25","2":"9","3":"29","4":"0","5":"1","6":"0","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.1786550","23":"841","24":"0","_rn_":"219"},{"1":"5.83","2":"8","3":"36","4":"15","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.7630169","23":"1296","24":"225","_rn_":"220"},{"1":"3.50","2":"8","3":"4","4":"0","5":"0","6":"0","7":"0","8":"3","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.2527629","23":"16","24":"0","_rn_":"221"},{"1":"3.33","2":"12","3":"45","4":"4","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2029723","23":"2025","24":"16","_rn_":"222"},{"1":"4.00","2":"14","3":"22","4":"3","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.3862944","23":"484","24":"9","_rn_":"223"},{"1":"3.50","2":"12","3":"20","4":"4","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.2527629","23":"400","24":"16","_rn_":"224"},{"1":"6.25","2":"16","3":"5","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8325815","23":"25","24":"0","_rn_":"225"},{"1":"2.95","2":"8","3":"15","4":"2","5":"1","6":"1","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0818052","23":"225","24":"4","_rn_":"226"},{"1":"5.71","2":"13","3":"10","4":"2","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.7422190","23":"100","24":"4","_rn_":"227"},{"1":"3.00","2":"9","3":"3","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"9","24":"0","_rn_":"228"},{"1":"22.86","2":"16","3":"16","4":"7","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"3.1293886","23":"256","24":"49","_rn_":"229"},{"1":"9.00","2":"12","3":"38","4":"1","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.1972246","23":"1444","24":"1","_rn_":"230"},{"1":"8.33","2":"15","3":"33","4":"26","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.1198635","23":"1089","24":"676","_rn_":"231"},{"1":"3.00","2":"11","3":"2","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"4","24":"0","_rn_":"232"},{"1":"5.75","2":"14","3":"6","4":"5","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.7491999","23":"36","24":"25","_rn_":"233"},{"1":"6.76","2":"12","3":"19","4":"3","5":"1","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.9110229","23":"361","24":"9","_rn_":"234"},{"1":"10.00","2":"12","3":"29","4":"0","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"2.3025851","23":"841","24":"0","_rn_":"235"},{"1":"3.00","2":"12","3":"2","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"4","24":"0","_rn_":"236"},{"1":"3.50","2":"18","3":"3","4":"1","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.2527629","23":"9","24":"1","_rn_":"237"},{"1":"3.25","2":"12","3":"4","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.1786550","23":"16","24":"0","_rn_":"238"},{"1":"4.00","2":"12","3":"10","4":"1","5":"1","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.3862944","23":"100","24":"1","_rn_":"239"},{"1":"2.92","2":"12","3":"4","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.0715836","23":"16","24":"0","_rn_":"240"},{"1":"3.06","2":"12","3":"14","4":"10","5":"1","6":"1","7":"0","8":"3","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.1184149","23":"196","24":"100","_rn_":"241"},{"1":"3.20","2":"12","3":"15","4":"5","5":"0","6":"1","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.1631508","23":"225","24":"25","_rn_":"242"},{"1":"4.75","2":"12","3":"19","4":"0","5":"0","6":"0","7":"1","8":"3","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5581446","23":"361","24":"0","_rn_":"243"},{"1":"3.00","2":"14","3":"17","4":"0","5":"0","6":"1","7":"1","8":"4","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"0","22":"1.0986123","23":"289","24":"0","_rn_":"244"},{"1":"18.16","2":"16","3":"29","4":"7","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.8992214","23":"841","24":"49","_rn_":"245"},{"1":"3.50","2":"12","3":"2","4":"0","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.2527629","23":"4","24":"0","_rn_":"246"},{"1":"4.11","2":"14","3":"5","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.4134231","23":"25","24":"0","_rn_":"247"},{"1":"1.96","2":"11","3":"38","4":"3","5":"1","6":"1","7":"0","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"0.6729445","23":"1444","24":"9","_rn_":"248"},{"1":"4.29","2":"12","3":"3","4":"0","5":"0","6":"1","7":"0","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.4562867","23":"9","24":"0","_rn_":"249"},{"1":"3.00","2":"10","3":"47","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.0986123","23":"2209","24":"0","_rn_":"250"},{"1":"6.45","2":"12","3":"7","4":"6","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8640801","23":"49","24":"36","_rn_":"251"},{"1":"5.20","2":"6","3":"47","4":"13","5":"1","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6486586","23":"2209","24":"169","_rn_":"252"},{"1":"4.50","2":"13","3":"23","4":"2","5":"1","6":"1","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.5040774","23":"529","24":"4","_rn_":"253"},{"1":"3.88","2":"12","3":"12","4":"3","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.3558352","23":"144","24":"9","_rn_":"254"},{"1":"3.45","2":"10","3":"11","4":"0","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.2383742","23":"121","24":"0","_rn_":"255"},{"1":"10.91","2":"12","3":"25","4":"23","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.3896797","23":"625","24":"529","_rn_":"256"},{"1":"4.10","2":"14","3":"6","4":"0","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.4109869","23":"36","24":"0","_rn_":"257"},{"1":"3.00","2":"13","3":"3","4":"1","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"9","24":"1","_rn_":"258"},{"1":"5.90","2":"12","3":"14","4":"7","5":"1","6":"0","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.7749524","23":"196","24":"49","_rn_":"259"},{"1":"18.00","2":"18","3":"13","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.8903718","23":"169","24":"0","_rn_":"260"},{"1":"4.00","2":"12","3":"9","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.3862944","23":"81","24":"0","_rn_":"261"},{"1":"3.00","2":"12","3":"1","4":"0","5":"1","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"1","24":"0","_rn_":"262"},{"1":"3.55","2":"12","3":"6","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2669476","23":"36","24":"0","_rn_":"263"},{"1":"3.00","2":"12","3":"11","4":"1","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.0986123","23":"121","24":"1","_rn_":"264"},{"1":"8.75","2":"12","3":"47","4":"44","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.1690538","23":"2209","24":"1936","_rn_":"265"},{"1":"2.90","2":"8","3":"49","4":"6","5":"0","6":"1","7":"0","8":"1","9":"0","10":"0","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0647107","23":"2401","24":"36","_rn_":"266"},{"1":"6.26","2":"13","3":"37","4":"17","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8341802","23":"1369","24":"289","_rn_":"267"},{"1":"3.50","2":"13","3":"2","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.2527629","23":"4","24":"0","_rn_":"268"},{"1":"4.60","2":"14","3":"7","4":"0","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.5260563","23":"49","24":"0","_rn_":"269"},{"1":"6.00","2":"12","3":"22","4":"8","5":"0","6":"0","7":"0","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.7917595","23":"484","24":"64","_rn_":"270"},{"1":"2.89","2":"10","3":"8","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0612565","23":"64","24":"0","_rn_":"271"},{"1":"5.58","2":"16","3":"1","4":"1","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.7191888","23":"1","24":"1","_rn_":"272"},{"1":"4.00","2":"12","3":"43","4":"6","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3862944","23":"1849","24":"36","_rn_":"273"},{"1":"6.00","2":"16","3":"2","4":"2","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7917595","23":"4","24":"4","_rn_":"274"},{"1":"4.50","2":"12","3":"2","4":"1","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"0","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5040774","23":"4","24":"1","_rn_":"275"},{"1":"2.92","2":"14","3":"1","4":"3","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.0715836","23":"1","24":"9","_rn_":"276"},{"1":"4.33","2":"18","3":"1","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.4655675","23":"1","24":"0","_rn_":"277"},{"1":"18.89","2":"17","3":"26","4":"20","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.9386327","23":"676","24":"400","_rn_":"278"},{"1":"4.28","2":"13","3":"1","4":"1","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.4539530","23":"1","24":"1","_rn_":"279"},{"1":"4.57","2":"14","3":"37","4":"7","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.5195132","23":"1369","24":"49","_rn_":"280"},{"1":"6.25","2":"15","3":"12","4":"4","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8325815","23":"144","24":"16","_rn_":"281"},{"1":"2.95","2":"14","3":"41","4":"23","5":"1","6":"0","7":"1","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.0818052","23":"1681","24":"529","_rn_":"282"},{"1":"8.75","2":"12","3":"24","4":"1","5":"0","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.1690538","23":"576","24":"1","_rn_":"283"},{"1":"8.50","2":"8","3":"38","4":"26","5":"0","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.1400661","23":"1444","24":"676","_rn_":"284"},{"1":"3.75","2":"12","3":"18","4":"0","5":"0","6":"1","7":"1","8":"4","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.3217559","23":"324","24":"0","_rn_":"285"},{"1":"3.15","2":"12","3":"26","4":"1","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.1474025","23":"676","24":"1","_rn_":"286"},{"1":"5.00","2":"8","3":"45","4":"2","5":"0","6":"0","7":"0","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6094379","23":"2025","24":"4","_rn_":"287"},{"1":"6.46","2":"12","3":"27","4":"0","5":"0","6":"0","7":"1","8":"3","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8656293","23":"729","24":"0","_rn_":"288"},{"1":"2.00","2":"9","3":"2","4":"0","5":"0","6":"0","7":"0","8":"3","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"0.6931472","23":"4","24":"0","_rn_":"289"},{"1":"4.79","2":"12","3":"41","4":"8","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.5665303","23":"1681","24":"64","_rn_":"290"},{"1":"5.78","2":"16","3":"11","4":"4","5":"0","6":"0","7":"1","8":"2","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.7544037","23":"121","24":"16","_rn_":"291"},{"1":"3.18","2":"12","3":"5","4":"0","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.1568812","23":"25","24":"0","_rn_":"292"},{"1":"4.68","2":"16","3":"3","4":"1","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.5432981","23":"9","24":"1","_rn_":"293"},{"1":"4.10","2":"12","3":"3","4":"2","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.4109869","23":"9","24":"4","_rn_":"294"},{"1":"2.91","2":"12","3":"4","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0681531","23":"16","24":"0","_rn_":"295"},{"1":"6.00","2":"13","3":"21","4":"13","5":"0","6":"0","7":"1","8":"4","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7917595","23":"441","24":"169","_rn_":"296"},{"1":"3.60","2":"10","3":"34","4":"26","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2809339","23":"1156","24":"676","_rn_":"297"},{"1":"3.95","2":"6","3":"49","4":"6","5":"0","6":"0","7":"1","8":"6","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3737156","23":"2401","24":"36","_rn_":"298"},{"1":"7.00","2":"12","3":"6","4":"5","5":"1","6":"0","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.9459101","23":"36","24":"25","_rn_":"299"},{"1":"3.00","2":"12","3":"26","4":"9","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.0986123","23":"676","24":"81","_rn_":"300"},{"1":"6.08","2":"16","3":"9","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"1.8050047","23":"81","24":"0","_rn_":"301"},{"1":"8.63","2":"12","3":"23","4":"9","5":"0","6":"0","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.1552446","23":"529","24":"81","_rn_":"302"},{"1":"3.00","2":"8","3":"33","4":"2","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"1089","24":"4","_rn_":"303"},{"1":"3.75","2":"12","3":"5","4":"2","5":"0","6":"1","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.3217559","23":"25","24":"4","_rn_":"304"},{"1":"2.90","2":"6","3":"49","4":"7","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.0647107","23":"2401","24":"49","_rn_":"305"},{"1":"3.00","2":"4","3":"48","4":"0","5":"1","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"2304","24":"0","_rn_":"306"},{"1":"6.25","2":"11","3":"35","4":"31","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8325815","23":"1225","24":"961","_rn_":"307"},{"1":"3.50","2":"11","3":"23","4":"2","5":"1","6":"1","7":"0","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2527629","23":"529","24":"4","_rn_":"308"},{"1":"3.00","2":"7","3":"26","4":"1","5":"0","6":"1","7":"0","8":"3","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.0986123","23":"676","24":"1","_rn_":"309"},{"1":"3.24","2":"12","3":"16","4":"0","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.1755733","23":"256","24":"0","_rn_":"310"},{"1":"8.02","2":"18","3":"23","4":"3","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.0819385","23":"529","24":"9","_rn_":"311"},{"1":"3.33","2":"12","3":"36","4":"8","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.2029723","23":"1296","24":"64","_rn_":"312"},{"1":"5.25","2":"16","3":"4","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.6582280","23":"16","24":"0","_rn_":"313"},{"1":"6.25","2":"12","3":"10","4":"0","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"1","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8325815","23":"100","24":"0","_rn_":"314"},{"1":"3.50","2":"14","3":"18","4":"2","5":"0","6":"0","7":"1","8":"1","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.2527629","23":"324","24":"4","_rn_":"315"},{"1":"2.95","2":"12","3":"3","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0818052","23":"9","24":"1","_rn_":"316"},{"1":"3.00","2":"10","3":"7","4":"0","5":"0","6":"1","7":"1","8":"2","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.0986123","23":"49","24":"0","_rn_":"317"},{"1":"4.69","2":"10","3":"7","4":"7","5":"0","6":"0","7":"0","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5454326","23":"49","24":"49","_rn_":"318"},{"1":"3.73","2":"9","3":"33","4":"2","5":"0","6":"1","7":"0","8":"1","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3164083","23":"1089","24":"4","_rn_":"319"},{"1":"4.00","2":"10","3":"34","4":"12","5":"0","6":"0","7":"1","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3862944","23":"1156","24":"144","_rn_":"320"},{"1":"4.00","2":"12","3":"8","4":"0","5":"0","6":"1","7":"1","8":"2","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.3862944","23":"64","24":"0","_rn_":"321"},{"1":"2.90","2":"12","3":"17","4":"1","5":"0","6":"1","7":"1","8":"2","9":"0","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0647107","23":"289","24":"1","_rn_":"322"},{"1":"3.05","2":"12","3":"2","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.1151416","23":"4","24":"0","_rn_":"323"},{"1":"5.05","2":"10","3":"5","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.6193882","23":"25","24":"0","_rn_":"324"},{"1":"13.95","2":"16","3":"41","4":"16","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.6354795","23":"1681","24":"256","_rn_":"325"},{"1":"18.16","2":"16","3":"35","4":"28","5":"0","6":"0","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.8992214","23":"1225","24":"784","_rn_":"326"},{"1":"6.25","2":"16","3":"11","4":"4","5":"0","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"1.8325815","23":"121","24":"16","_rn_":"327"},{"1":"5.25","2":"12","3":"4","4":"0","5":"1","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.6582280","23":"16","24":"0","_rn_":"328"},{"1":"4.79","2":"12","3":"12","4":"3","5":"0","6":"1","7":"1","8":"3","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.5665303","23":"144","24":"9","_rn_":"329"},{"1":"3.35","2":"7","3":"35","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2089603","23":"1225","24":"0","_rn_":"330"},{"1":"3.00","2":"8","3":"33","4":"0","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"1089","24":"0","_rn_":"331"},{"1":"8.43","2":"16","3":"8","4":"6","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.1317968","23":"64","24":"36","_rn_":"332"},{"1":"5.70","2":"16","3":"2","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.7404661","23":"4","24":"0","_rn_":"333"},{"1":"11.98","2":"18","3":"8","4":"10","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.4832385","23":"64","24":"100","_rn_":"334"},{"1":"3.50","2":"13","3":"29","4":"1","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.2527629","23":"841","24":"1","_rn_":"335"},{"1":"4.24","2":"10","3":"14","4":"5","5":"1","6":"0","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.4445633","23":"196","24":"25","_rn_":"336"},{"1":"7.00","2":"16","3":"26","4":"3","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.9459101","23":"676","24":"9","_rn_":"337"},{"1":"6.00","2":"14","3":"11","4":"3","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.7917595","23":"121","24":"9","_rn_":"338"},{"1":"12.22","2":"16","3":"10","4":"2","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.5030739","23":"100","24":"4","_rn_":"339"},{"1":"4.50","2":"12","3":"13","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5040774","23":"169","24":"0","_rn_":"340"},{"1":"3.00","2":"9","3":"23","4":"20","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"529","24":"400","_rn_":"341"},{"1":"2.90","2":"11","3":"1","4":"2","5":"1","6":"0","7":"0","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.0647107","23":"1","24":"4","_rn_":"342"},{"1":"15.00","2":"11","3":"35","4":"31","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.7080503","23":"1225","24":"961","_rn_":"343"},{"1":"4.00","2":"12","3":"5","4":"2","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3862944","23":"25","24":"4","_rn_":"344"},{"1":"5.25","2":"11","3":"13","4":"11","5":"0","6":"0","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6582280","23":"169","24":"121","_rn_":"345"},{"1":"4.00","2":"12","3":"22","4":"3","5":"0","6":"0","7":"1","8":"3","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3862944","23":"484","24":"9","_rn_":"346"},{"1":"3.30","2":"12","3":"21","4":"9","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.1939224","23":"441","24":"81","_rn_":"347"},{"1":"5.05","2":"12","3":"19","4":"0","5":"0","6":"1","7":"1","8":"3","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.6193882","23":"361","24":"0","_rn_":"348"},{"1":"3.58","2":"12","3":"13","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.2753627","23":"169","24":"0","_rn_":"349"},{"1":"5.00","2":"14","3":"15","4":"5","5":"0","6":"0","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.6094379","23":"225","24":"25","_rn_":"350"},{"1":"4.57","2":"14","3":"3","4":"0","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.5195132","23":"9","24":"0","_rn_":"351"},{"1":"12.50","2":"18","3":"6","4":"2","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"0","22":"2.5257287","23":"36","24":"4","_rn_":"352"},{"1":"3.45","2":"12","3":"6","4":"5","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.2383742","23":"36","24":"25","_rn_":"353"},{"1":"4.63","2":"12","3":"16","4":"1","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.5325569","23":"256","24":"1","_rn_":"354"},{"1":"10.00","2":"12","3":"31","4":"2","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.3025851","23":"961","24":"4","_rn_":"355"},{"1":"2.92","2":"11","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.0715836","23":"1","24":"0","_rn_":"356"},{"1":"4.51","2":"12","3":"5","4":"2","5":"0","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5062972","23":"25","24":"4","_rn_":"357"},{"1":"6.50","2":"17","3":"3","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8718022","23":"9","24":"0","_rn_":"358"},{"1":"7.50","2":"16","3":"11","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"2.0149031","23":"121","24":"0","_rn_":"359"},{"1":"3.54","2":"13","3":"6","4":"7","5":"0","6":"1","7":"1","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.2641267","23":"36","24":"49","_rn_":"360"},{"1":"4.20","2":"13","3":"11","4":"3","5":"0","6":"1","7":"1","8":"2","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.4350845","23":"121","24":"9","_rn_":"361"},{"1":"3.51","2":"12","3":"7","4":"2","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.2556161","23":"49","24":"4","_rn_":"362"},{"1":"4.50","2":"14","3":"5","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.5040774","23":"25","24":"0","_rn_":"363"},{"1":"3.35","2":"14","3":"5","4":"4","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.2089603","23":"25","24":"16","_rn_":"364"},{"1":"2.91","2":"11","3":"2","4":"2","5":"0","6":"0","7":"0","8":"2","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.0681531","23":"4","24":"4","_rn_":"365"},{"1":"5.25","2":"10","3":"44","4":"7","5":"0","6":"0","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6582280","23":"1936","24":"49","_rn_":"366"},{"1":"4.05","2":"8","3":"44","4":"25","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.3987169","23":"1936","24":"625","_rn_":"367"},{"1":"3.75","2":"14","3":"13","4":"0","5":"0","6":"1","7":"1","8":"3","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.3217559","23":"169","24":"0","_rn_":"368"},{"1":"3.40","2":"12","3":"26","4":"15","5":"0","6":"1","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.2237755","23":"676","24":"225","_rn_":"369"},{"1":"3.00","2":"10","3":"2","4":"1","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.0986123","23":"4","24":"1","_rn_":"370"},{"1":"6.29","2":"17","3":"10","4":"3","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"1.8389610","23":"100","24":"9","_rn_":"371"},{"1":"2.54","2":"9","3":"2","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"0.9321641","23":"4","24":"0","_rn_":"372"},{"1":"4.50","2":"12","3":"35","4":"0","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.5040774","23":"1225","24":"0","_rn_":"373"},{"1":"3.13","2":"12","3":"6","4":"5","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.1410331","23":"36","24":"25","_rn_":"374"},{"1":"6.36","2":"14","3":"8","4":"1","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8500284","23":"64","24":"1","_rn_":"375"},{"1":"4.68","2":"16","3":"1","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.5432981","23":"1","24":"0","_rn_":"376"},{"1":"6.80","2":"12","3":"14","4":"10","5":"0","6":"0","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.9169227","23":"196","24":"100","_rn_":"377"},{"1":"8.53","2":"10","3":"14","4":"6","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.1435893","23":"196","24":"36","_rn_":"378"},{"1":"4.17","2":"0","3":"22","4":"10","5":"0","6":"1","7":"0","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.4279160","23":"484","24":"100","_rn_":"379"},{"1":"3.75","2":"14","3":"8","4":"4","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.3217559","23":"64","24":"16","_rn_":"380"},{"1":"11.10","2":"15","3":"1","4":"4","5":"0","6":"1","7":"0","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"2.4069452","23":"1","24":"16","_rn_":"381"},{"1":"3.26","2":"16","3":"15","4":"5","5":"1","6":"1","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.1817272","23":"225","24":"25","_rn_":"382"},{"1":"9.13","2":"12","3":"14","4":"12","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.2115657","23":"196","24":"144","_rn_":"383"},{"1":"4.50","2":"11","3":"37","4":"10","5":"0","6":"0","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5040774","23":"1369","24":"100","_rn_":"384"},{"1":"3.00","2":"11","3":"1","4":"1","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.0986123","23":"1","24":"1","_rn_":"385"},{"1":"8.75","2":"12","3":"4","4":"4","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"2.1690538","23":"16","24":"16","_rn_":"386"},{"1":"4.14","2":"13","3":"29","4":"0","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.4206958","23":"841","24":"0","_rn_":"387"},{"1":"2.87","2":"12","3":"45","4":"8","5":"0","6":"1","7":"1","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.0543120","23":"2025","24":"64","_rn_":"388"},{"1":"3.35","2":"13","3":"22","4":"0","5":"0","6":"1","7":"0","8":"2","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.2089603","23":"484","24":"0","_rn_":"389"},{"1":"6.08","2":"16","3":"42","4":"10","5":"0","6":"0","7":"0","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8050047","23":"1764","24":"100","_rn_":"390"},{"1":"3.00","2":"15","3":"9","4":"0","5":"1","6":"0","7":"0","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"81","24":"0","_rn_":"391"},{"1":"4.20","2":"16","3":"8","4":"0","5":"0","6":"1","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.4350845","23":"64","24":"0","_rn_":"392"},{"1":"5.60","2":"15","3":"31","4":"15","5":"0","6":"1","7":"0","8":"2","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.7227666","23":"961","24":"225","_rn_":"393"},{"1":"10.00","2":"12","3":"24","4":"24","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.3025851","23":"576","24":"576","_rn_":"394"},{"1":"12.50","2":"18","3":"16","4":"5","5":"0","6":"0","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.5257287","23":"256","24":"25","_rn_":"395"},{"1":"3.76","2":"6","3":"6","4":"0","5":"0","6":"0","7":"0","8":"4","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3244189","23":"36","24":"0","_rn_":"396"},{"1":"3.10","2":"6","3":"14","4":"0","5":"1","6":"1","7":"0","8":"5","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.1314021","23":"196","24":"0","_rn_":"397"},{"1":"4.29","2":"12","3":"47","4":"25","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.4562867","23":"2209","24":"625","_rn_":"398"},{"1":"10.92","2":"12","3":"34","4":"5","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.3905959","23":"1156","24":"25","_rn_":"399"},{"1":"7.50","2":"16","3":"6","4":"2","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.0149031","23":"36","24":"4","_rn_":"400"},{"1":"4.05","2":"9","3":"7","4":"4","5":"0","6":"1","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3987169","23":"49","24":"16","_rn_":"401"},{"1":"4.65","2":"12","3":"27","4":"2","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.5368673","23":"729","24":"4","_rn_":"402"},{"1":"5.00","2":"11","3":"24","4":"5","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6094379","23":"576","24":"25","_rn_":"403"},{"1":"2.90","2":"10","3":"18","4":"0","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.0647107","23":"324","24":"0","_rn_":"404"},{"1":"8.00","2":"12","3":"12","4":"3","5":"1","6":"1","7":"0","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.0794415","23":"144","24":"9","_rn_":"405"},{"1":"8.43","2":"8","3":"27","4":"3","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.1317968","23":"729","24":"9","_rn_":"406"},{"1":"2.92","2":"9","3":"49","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.0715836","23":"2401","24":"0","_rn_":"407"},{"1":"6.25","2":"17","3":"4","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8325815","23":"16","24":"0","_rn_":"408"},{"1":"6.25","2":"16","3":"24","4":"2","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8325815","23":"576","24":"4","_rn_":"409"},{"1":"5.11","2":"11","3":"3","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6311995","23":"9","24":"0","_rn_":"410"},{"1":"4.00","2":"10","3":"2","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.3862944","23":"4","24":"0","_rn_":"411"},{"1":"4.44","2":"8","3":"29","4":"11","5":"0","6":"0","7":"1","8":"3","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.4906543","23":"841","24":"121","_rn_":"412"},{"1":"6.88","2":"13","3":"34","4":"21","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"1.9286187","23":"1156","24":"441","_rn_":"413"},{"1":"5.43","2":"14","3":"10","4":"3","5":"1","6":"0","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.6919391","23":"100","24":"9","_rn_":"414"},{"1":"3.00","2":"13","3":"5","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.0986123","23":"25","24":"0","_rn_":"415"},{"1":"2.90","2":"11","3":"2","4":"0","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.0647107","23":"4","24":"0","_rn_":"416"},{"1":"6.25","2":"7","3":"39","4":"21","5":"1","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8325815","23":"1521","24":"441","_rn_":"417"},{"1":"4.34","2":"16","3":"5","4":"2","5":"1","6":"1","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.4678744","23":"25","24":"4","_rn_":"418"},{"1":"3.25","2":"12","3":"14","4":"2","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.1786550","23":"196","24":"4","_rn_":"419"},{"1":"7.26","2":"13","3":"8","4":"2","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.9823799","23":"64","24":"4","_rn_":"420"},{"1":"6.35","2":"14","3":"10","4":"1","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8484548","23":"100","24":"1","_rn_":"421"},{"1":"5.63","2":"16","3":"2","4":"2","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.7281095","23":"4","24":"4","_rn_":"422"},{"1":"8.75","2":"14","3":"9","4":"3","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.1690538","23":"81","24":"9","_rn_":"423"},{"1":"3.20","2":"11","3":"1","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.1631508","23":"1","24":"0","_rn_":"424"},{"1":"3.00","2":"8","3":"45","4":"1","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"2025","24":"1","_rn_":"425"},{"1":"3.00","2":"14","3":"33","4":"3","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.0986123","23":"1089","24":"9","_rn_":"426"},{"1":"12.50","2":"17","3":"21","4":"18","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.5257287","23":"441","24":"324","_rn_":"427"},{"1":"2.88","2":"10","3":"2","4":"0","5":"0","6":"1","7":"0","8":"3","9":"1","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.0577903","23":"4","24":"0","_rn_":"428"},{"1":"3.35","2":"12","3":"9","4":"1","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2089603","23":"81","24":"1","_rn_":"429"},{"1":"6.50","2":"12","3":"33","4":"2","5":"0","6":"0","7":"1","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8718022","23":"1089","24":"4","_rn_":"430"},{"1":"10.38","2":"18","3":"16","4":"2","5":"1","6":"0","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.3398809","23":"256","24":"4","_rn_":"431"},{"1":"4.50","2":"14","3":"10","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"0","22":"1.5040774","23":"100","24":"0","_rn_":"432"},{"1":"10.00","2":"18","3":"9","4":"8","5":"0","6":"0","7":"0","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.3025851","23":"81","24":"64","_rn_":"433"},{"1":"3.81","2":"12","3":"8","4":"1","5":"0","6":"1","7":"1","8":"2","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.3376292","23":"64","24":"1","_rn_":"434"},{"1":"8.80","2":"16","3":"9","4":"1","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.1747518","23":"81","24":"1","_rn_":"435"},{"1":"9.42","2":"14","3":"23","4":"0","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"2.2428350","23":"529","24":"0","_rn_":"436"},{"1":"6.33","2":"12","3":"23","4":"8","5":"0","6":"0","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8453002","23":"529","24":"64","_rn_":"437"},{"1":"4.00","2":"9","3":"22","4":"18","5":"1","6":"0","7":"0","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3862944","23":"484","24":"324","_rn_":"438"},{"1":"2.90","2":"12","3":"37","4":"0","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.0647107","23":"1369","24":"0","_rn_":"439"},{"1":"20.00","2":"12","3":"22","4":"4","5":"0","6":"0","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.9957323","23":"484","24":"16","_rn_":"440"},{"1":"11.25","2":"17","3":"28","4":"25","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.4203682","23":"784","24":"625","_rn_":"441"},{"1":"3.50","2":"12","3":"14","4":"0","5":"1","6":"1","7":"0","8":"2","9":"1","10":"0","11":"1","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2527629","23":"196","24":"0","_rn_":"442"},{"1":"6.00","2":"15","3":"19","4":"4","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.7917595","23":"361","24":"16","_rn_":"443"},{"1":"14.38","2":"17","3":"10","4":"9","5":"1","6":"0","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.6658382","23":"100","24":"81","_rn_":"444"},{"1":"6.36","2":"16","3":"25","4":"0","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8500284","23":"625","24":"0","_rn_":"445"},{"1":"3.55","2":"12","3":"21","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2669476","23":"441","24":"0","_rn_":"446"},{"1":"3.00","2":"15","3":"32","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.0986123","23":"1024","24":"0","_rn_":"447"},{"1":"4.50","2":"16","3":"21","4":"10","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.5040774","23":"441","24":"100","_rn_":"448"},{"1":"6.63","2":"12","3":"36","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.8916048","23":"1296","24":"0","_rn_":"449"},{"1":"9.30","2":"15","3":"2","4":"2","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.2300143","23":"4","24":"4","_rn_":"450"},{"1":"3.00","2":"12","3":"11","4":"0","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.0986123","23":"121","24":"0","_rn_":"451"},{"1":"3.25","2":"12","3":"40","4":"2","5":"0","6":"1","7":"0","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.1786550","23":"1600","24":"4","_rn_":"452"},{"1":"1.50","2":"12","3":"11","4":"1","5":"0","6":"1","7":"1","8":"2","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"0.4054651","23":"121","24":"1","_rn_":"453"},{"1":"5.90","2":"12","3":"9","4":"7","5":"0","6":"1","7":"1","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7749524","23":"81","24":"49","_rn_":"454"},{"1":"8.00","2":"16","3":"23","4":"4","5":"0","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.0794415","23":"529","24":"16","_rn_":"455"},{"1":"2.90","2":"11","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.0647107","23":"1","24":"0","_rn_":"456"},{"1":"3.29","2":"14","3":"30","4":"13","5":"0","6":"0","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.1908876","23":"900","24":"169","_rn_":"457"},{"1":"6.50","2":"14","3":"41","4":"33","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8718022","23":"1681","24":"1089","_rn_":"458"},{"1":"4.00","2":"13","3":"6","4":"0","5":"0","6":"1","7":"0","8":"1","9":"1","10":"1","11":"0","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.3862944","23":"36","24":"0","_rn_":"459"},{"1":"6.00","2":"14","3":"11","4":"0","5":"0","6":"0","7":"1","8":"0","9":"0","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7917595","23":"121","24":"0","_rn_":"460"},{"1":"4.08","2":"12","3":"43","4":"17","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.4060969","23":"1849","24":"289","_rn_":"461"},{"1":"3.75","2":"12","3":"39","4":"2","5":"0","6":"1","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"1.3217559","23":"1521","24":"4","_rn_":"462"},{"1":"3.05","2":"8","3":"50","4":"24","5":"0","6":"1","7":"0","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.1151416","23":"2500","24":"576","_rn_":"463"},{"1":"3.50","2":"12","3":"26","4":"20","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.2527629","23":"676","24":"400","_rn_":"464"},{"1":"2.92","2":"3","3":"51","4":"30","5":"1","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1.0715836","23":"2601","24":"900","_rn_":"465"},{"1":"4.50","2":"11","3":"3","4":"9","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"1","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5040774","23":"9","24":"81","_rn_":"466"},{"1":"3.35","2":"15","3":"3","4":"1","5":"0","6":"1","7":"1","8":"2","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"0","22":"1.2089603","23":"9","24":"1","_rn_":"467"},{"1":"5.95","2":"11","3":"15","4":"9","5":"1","6":"0","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7833912","23":"225","24":"81","_rn_":"468"},{"1":"8.00","2":"12","3":"17","4":"6","5":"0","6":"0","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.0794415","23":"289","24":"36","_rn_":"469"},{"1":"3.00","2":"4","3":"36","4":"0","5":"0","6":"0","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"1296","24":"0","_rn_":"470"},{"1":"5.00","2":"9","3":"31","4":"9","5":"1","6":"0","7":"1","8":"6","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.6094379","23":"961","24":"81","_rn_":"471"},{"1":"5.50","2":"12","3":"9","4":"4","5":"0","6":"0","7":"1","8":"1","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7047480","23":"81","24":"16","_rn_":"472"},{"1":"2.65","2":"12","3":"42","4":"10","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"0","22":"0.9745597","23":"1764","24":"100","_rn_":"473"},{"1":"3.00","2":"11","3":"3","4":"0","5":"0","6":"1","7":"0","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"9","24":"0","_rn_":"474"},{"1":"4.50","2":"12","3":"37","4":"14","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.5040774","23":"1369","24":"196","_rn_":"475"},{"1":"17.50","2":"16","3":"23","4":"22","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.8622010","23":"529","24":"484","_rn_":"476"},{"1":"8.18","2":"13","3":"21","4":"5","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.1016922","23":"441","24":"25","_rn_":"477"},{"1":"9.09","2":"15","3":"11","4":"12","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.2071750","23":"121","24":"144","_rn_":"478"},{"1":"11.82","2":"16","3":"35","4":"13","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.4697931","23":"1225","24":"169","_rn_":"479"},{"1":"3.25","2":"12","3":"42","4":"0","5":"0","6":"1","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.1786550","23":"1764","24":"0","_rn_":"480"},{"1":"4.50","2":"12","3":"3","4":"0","5":"0","6":"0","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5040774","23":"9","24":"0","_rn_":"481"},{"1":"4.50","2":"12","3":"13","4":"0","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5040774","23":"169","24":"0","_rn_":"482"},{"1":"3.71","2":"9","3":"14","4":"7","5":"0","6":"0","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.3110319","23":"196","24":"49","_rn_":"483"},{"1":"6.50","2":"10","3":"14","4":"11","5":"0","6":"0","7":"1","8":"3","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8718022","23":"196","24":"121","_rn_":"484"},{"1":"2.90","2":"12","3":"39","4":"1","5":"0","6":"1","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.0647107","23":"1521","24":"1","_rn_":"485"},{"1":"5.60","2":"11","3":"11","4":"8","5":"0","6":"0","7":"1","8":"2","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.7227666","23":"121","24":"64","_rn_":"486"},{"1":"2.23","2":"8","3":"28","4":"3","5":"0","6":"0","7":"1","8":"4","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"0.8020016","23":"784","24":"9","_rn_":"487"},{"1":"5.00","2":"6","3":"18","4":"0","5":"0","6":"1","7":"1","8":"3","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.6094379","23":"324","24":"0","_rn_":"488"},{"1":"8.33","2":"16","3":"6","4":"2","5":"0","6":"0","7":"1","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"2.1198635","23":"36","24":"4","_rn_":"489"},{"1":"2.90","2":"12","3":"26","4":"1","5":"0","6":"1","7":"0","8":"4","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.0647107","23":"676","24":"1","_rn_":"490"},{"1":"6.25","2":"12","3":"21","4":"6","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.8325815","23":"441","24":"36","_rn_":"491"},{"1":"4.55","2":"16","3":"34","4":"2","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.5151273","23":"1156","24":"4","_rn_":"492"},{"1":"3.28","2":"12","3":"17","4":"2","5":"0","6":"1","7":"0","8":"0","9":"0","10":"0","11":"1","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1.1878434","23":"289","24":"4","_rn_":"493"},{"1":"2.30","2":"10","3":"2","4":"0","5":"0","6":"1","7":"0","8":"4","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"0.8329091","23":"4","24":"0","_rn_":"494"},{"1":"3.30","2":"13","3":"5","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.1939224","23":"25","24":"0","_rn_":"495"},{"1":"3.15","2":"13","3":"1","4":"0","5":"0","6":"1","7":"0","8":"4","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1.1474025","23":"1","24":"0","_rn_":"496"},{"1":"12.50","2":"14","3":"40","4":"30","5":"0","6":"0","7":"1","8":"0","9":"1","10":"1","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.5257287","23":"1600","24":"900","_rn_":"497"},{"1":"5.15","2":"16","3":"39","4":"21","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.6389967","23":"1521","24":"441","_rn_":"498"},{"1":"3.13","2":"10","3":"1","4":"1","5":"0","6":"0","7":"0","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.1410331","23":"1","24":"1","_rn_":"499"},{"1":"7.25","2":"12","3":"14","4":"5","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.9810015","23":"196","24":"25","_rn_":"500"},{"1":"2.90","2":"12","3":"2","4":"2","5":"0","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.0647107","23":"4","24":"4","_rn_":"501"},{"1":"1.75","2":"11","3":"2","4":"1","5":"0","6":"0","7":"0","8":"2","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"0.5596158","23":"4","24":"1","_rn_":"502"},{"1":"2.89","2":"0","3":"42","4":"0","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.0612565","23":"1764","24":"0","_rn_":"503"},{"1":"2.90","2":"5","3":"34","4":"0","5":"0","6":"1","7":"1","8":"5","9":"0","10":"0","11":"0","12":"1","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.0647107","23":"1156","24":"0","_rn_":"504"},{"1":"17.71","2":"16","3":"10","4":"3","5":"0","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"2.8741293","23":"100","24":"9","_rn_":"505"},{"1":"6.25","2":"16","3":"4","4":"3","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1.8325815","23":"16","24":"9","_rn_":"506"},{"1":"2.60","2":"9","3":"4","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"0.9555114","23":"16","24":"0","_rn_":"507"},{"1":"6.63","2":"15","3":"21","4":"3","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.8916048","23":"441","24":"9","_rn_":"508"},{"1":"3.50","2":"12","3":"31","4":"3","5":"1","6":"1","7":"0","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.2527629","23":"961","24":"9","_rn_":"509"},{"1":"6.50","2":"12","3":"20","4":"14","5":"0","6":"0","7":"1","8":"3","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.8718022","23":"400","24":"196","_rn_":"510"},{"1":"3.00","2":"12","3":"36","4":"1","5":"1","6":"1","7":"0","8":"0","9":"1","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1.0986123","23":"1296","24":"1","_rn_":"511"},{"1":"4.38","2":"13","3":"7","4":"0","5":"1","6":"0","7":"1","8":"1","9":"1","10":"0","11":"0","12":"1","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.4770488","23":"49","24":"0","_rn_":"512"},{"1":"10.00","2":"12","3":"15","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"2.3025851","23":"225","24":"0","_rn_":"513"},{"1":"4.95","2":"7","3":"25","4":"17","5":"0","6":"0","7":"1","8":"5","9":"0","10":"0","11":"0","12":"0","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5993875","23":"625","24":"289","_rn_":"514"},{"1":"9.00","2":"17","3":"7","4":"0","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.1972246","23":"49","24":"0","_rn_":"515"},{"1":"1.43","2":"12","3":"17","4":"0","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"0.3576744","23":"289","24":"0","_rn_":"516"},{"1":"3.08","2":"12","3":"3","4":"1","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1.1249295","23":"9","24":"1","_rn_":"517"},{"1":"9.33","2":"14","3":"12","4":"11","5":"0","6":"0","7":"1","8":"3","9":"0","10":"0","11":"0","12":"0","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.2332351","23":"144","24":"121","_rn_":"518"},{"1":"7.50","2":"12","3":"18","4":"5","5":"0","6":"0","7":"1","8":"2","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.0149031","23":"324","24":"25","_rn_":"519"},{"1":"4.75","2":"13","3":"47","4":"1","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.5581446","23":"2209","24":"1","_rn_":"520"},{"1":"5.65","2":"12","3":"2","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0","11":"0","12":"1","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1.7316556","23":"4","24":"0","_rn_":"521"},{"1":"15.00","2":"16","3":"14","4":"2","5":"0","6":"1","7":"1","8":"2","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"1","20":"0","21":"0","22":"2.7080503","23":"196","24":"4","_rn_":"522"},{"1":"2.27","2":"10","3":"2","4":"0","5":"0","6":"1","7":"0","8":"3","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"0","22":"0.8197798","23":"4","24":"0","_rn_":"523"},{"1":"4.67","2":"15","3":"13","4":"18","5":"0","6":"0","7":"1","8":"3","9":"0","10":"0","11":"0","12":"1","13":"1","14":"0","15":"0","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1.5411590","23":"169","24":"324","_rn_":"524"},{"1":"11.56","2":"16","3":"5","4":"1","5":"0","6":"0","7":"1","8":"0","9":"0","10":"0","11":"0","12":"1","13":"0","14":"1","15":"0","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"2.4475510","23":"25","24":"1","_rn_":"525"},{"1":"3.50","2":"14","3":"5","4":"4","5":"1","6":"1","7":"0","8":"2","9":"0","10":"0","11":"0","12":"1","13":"0","14":"0","15":"0","16":"0","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1.2527629","23":"25","24":"16","_rn_":"526"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>

Kullanacağımız değişkenlerin açıklamalarına bakalım.


```r
?wage1
```

Kullanacağımız değişkenlerin açıklamalarını daha önce çevirdik. İsterseniz help(wage1) veya ?wage1 kodlarını kullanarak veriler hakkında bilgiye ulaşabilirsiniz.

Bu veri setini kullanarak deneyimin getirisini test etmeye çalışacağız, bunu yaparken eğitim ve güncel işindeki çalışma yıllarını kontrol edeceğiz.

$$
log(maaş)= \beta_0 + \beta_1 eğitim + \beta_2 deneyim  + \beta_3 iş.yılı + u
$$
 veri setindeki ingilizce değişkenler
 
 
$$
log(wage)= \beta_0 + \beta_1 educ + \beta_2 exper  + \beta_3 tenure + u
$$

Diğer iki değişkeni sabit tutarken, deneyimin getirisinin sıfır olup olmadığını test etmek için kurduğumuz hipotez $H_0: \beta_2=0$ olaarak yazılabilir. Bu hipotezi reddersek $H_1: \beta_2>0$ alternatif hipotezini kabul ediyoruz. 


```r
maasreg <- lm(log(wage)~ educ+exper+tenure,data = wage1)
summary(maasreg)
```

```
## 
## Call:
## lm(formula = log(wage) ~ educ + exper + tenure, data = wage1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.05802 -0.29645 -0.03265  0.28788  1.42809 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 0.284360   0.104190   2.729  0.00656 ** 
## educ        0.092029   0.007330  12.555  < 2e-16 ***
## exper       0.004121   0.001723   2.391  0.01714 *  
## tenure      0.022067   0.003094   7.133 3.29e-12 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.4409 on 522 degrees of freedom
## Multiple R-squared:  0.316,	Adjusted R-squared:  0.3121 
## F-statistic: 80.39 on 3 and 522 DF,  p-value: < 2.2e-16
```


$\beta_2$'nun popülasyon parametresi olduğunu unutmayın. Biz popülasyon parametresini test ediyoruz. exper'in tahmini katsayısı $\hat{\beta_2}$ gördüğünüz gibi 0.0041. Hipotezi tekrar yazmak isterseniz $0.0041=0$ ya da  $H_0:\hat{\beta_2}=0$ yazamazsınız. 

Veri setimizde her bir değişken için gözlem sayısı $n=526$, t dağılımı için serbestlik derecesini bulmak isterseniz $n-k-1= 526-3-1=522$ değerini kullanmanız gerekecektir. Bu değer aslında regresyon sonuçlarında "degrees of freedom" değeri olarak yazıldığına dikkat edin (Alttan üçüncü satır "Residual standard error: 0.4409 on $\bf{522}$ $\bf{degrees}$ $\bf{of}$ $\bf{freedom}$". 

R-studio ile 522 serbestlik derecesine sahip t dağılımının kritik değerlerini bulmak çok kolaydır. Bunun için bir formüle ya da tabloya ihtiyacımız yok. qt komutu size bu değeri verecektir.

Mesela eğer \%95 olasılıkta t değerini bulmak istiyorsanız aşağıdaki kod yeterli olacaktır.


```r
qt(0.95,522)
```

```
## [1] 1.647778
```

\%99 olasılıkta t değeri için 


```r
qt(0.99,522)
```

```
## [1] 2.333513
```

kullanıyoruz. 522 gibi büyük bir gözlem sayısına sahip olduğumuz için t değerlerimiz, normal dağılım kritik değerlerine çok yakındır. Kritik t değerini bulduktan sonra, regresyon tablomuzda karşılaştırma yapmak istediğimiz parametrenin t değerine bakalım. Exper değişkeni için bu değer t value'nun altında 2.391 olarak bulunur. 2.39 iki kritik değerimizden de büyük bu durumda $\hat{\beta_{exper}}$ veya exper \%1 seviyesinde istatistiksel olarak anlamlıdır ve \%1 anlamlılık seviyesinde istatiksel olarak sıfırdan büyüktür. Unutmayın ki negatif bir t değerini kritik değerlerle karşılaştırıyor olabilirdik. Böyle bir durumda t değerinin mutlak değerinin kritik t değerlerinden büyük olup olmadığına bakacaktık.

Aynı cevabı t değerlerine bakmadan olasılıklara bakarak da çıkarabilirdik. Tekrar regresyon tablomuza bir göz atın. Her bir değişken için olasılık değerlerini Pr (probability, olasılık) sütununda göreceksiniz. Biz exper değişkeni için olasılık değerine bakıyoruz. Olasılık 0.01714, exper katsayısının sıfır olma olasılığını yaklaşık olarak \%1.7 versede, biz t değerine göre \%1'in altında bulmuştuk. Bu durum kafanızı karıştırmamalı. Çünkü R p değerini her zaman iki taraflı test olarak verecektir. Eğer 0.01714 değerini 2'ye bölersek 0.00857 buluruz. Gördüğünüz gibi exper katsayısının 0 olma ihtimali \%1'den küçüktür. Bu yüzden $H_0$ hipotezini reddederiz.

## Güven Aralığı

Güven aralığını oluşturmayı daha önce basit bir konsepte konuşmuştuk. Örneğin bir parametre için \%95 güven aralığı oluşturmak istiyorsak, bulduğumuz katsayı sonucunun standart hatasının iki katından çıkarıyor ve topluyorduk.

$$
\beta_j \pm 2 \cdot se(\beta_j)
$$

Burada 2 yerine hangi yüzdeyle güven aralığı oluşturmak isteniyorsa o t kritik değeri kullanılmalıdır.

R bizim için bu güven aralıklarını kolaylıkla oluşturabilir. Örneğimizden devam edecek olursak


```r
confint(maasreg)
```

```
##                    2.5 %     97.5 %
## (Intercept) 0.0796755842 0.48904353
## educ        0.0776292137 0.10642876
## exper       0.0007356983 0.00750652
## tenure      0.0159896850 0.02814475
```

confint bizim için \%95 güven aralığını oluşturacaktır. \%99 güven aralığı oluşturmak isterseniz


```r
confint(maasreg, level=0.99)
```

```
##                     0.5 %      99.5 %
## (Intercept)  0.0149982043 0.553720906
## educ         0.0730790792 0.110978894
## exper       -0.0003340459 0.008576264
## tenure       0.0140692666 0.030065168
```

level detayını eklemeniz gerecektir.

Coefplot paketini yüklerseniz size güven aralığı grafiğini çıkaran bir kod sunar.


```r
library(coefplot)
```

```
## Loading required package: ggplot2
```

```r
coefplot(maasreg)
```

```
## Warning: It is deprecated to specify `guide = FALSE` to remove a guide. Please
## use `guide = "none"` instead.

## Warning: It is deprecated to specify `guide = FALSE` to remove a guide. Please
## use `guide = "none"` instead.

## Warning: It is deprecated to specify `guide = FALSE` to remove a guide. Please
## use `guide = "none"` instead.
```

<img src="/courses/example/ders_files/figure-html/unnamed-chunk-9-1.png" width="672" />


Grafikten de görebileceğiniz gibi exper katsayısı 0'a çok yakın ama güven aralığı 0'ı kapsamıyor.

## Çoklu Doğrusal Kısıtların Testi

Şimdiye kadar sadece bir parametrenin testi üzerinde durduk ve hipotezi bir katsayının sıfıra eşit olup olmadığı üzerinden kurduk. Ancak bir kaç değişkenin katsayısının aynı anda test edilmesi de mümkündür. Beş değişkenli bir model düşünün

$$
y= \beta_0 + \beta_1 x_1 + \beta_2 x_2  + \beta_3 x_3 + \beta_4 x_4  + \beta_5 x_5  + u
$$
$\beta_3, \beta_4, \beta_5$ katsayılarını aynı anda sıfır olup olmadığını merak ediyorsanız hipotezinizi şöyle oluşturursunuz

$$
H_0: \beta_3=0, \beta_4=0, \beta_5=0
$$

Farkındaysanız eğer bu hipotezi kabul edersek kısıtlı bir model elde etmiş oluruz.

$$
y= \beta_0 + \beta_1 x_1 + \beta_2 x_2 + u
$$

Bu iki model arasında hangi modelin doğru olduğunu F istatistiği ile kontrol ederiz. İlk modelimize kısıtsız model (unrestricted model, ur), ikinci modele ise kısıtlı model (restricted, r) diyeceğiz. F istatistiği şu şekide bulunur.

$$
F= \frac{(SSR_r-SSR_{ur})/q}{SSR_{ur}/(n-k-1)}
$$
$SSR_r$ kısıtlı modelin hata payının karelerinin toplamı, $SSR_{ur}$ kısıtsız modelin hata payının karelerinin toplamı, $q$ kısıt sayısı, $n-k-1$ kısıtsız modelin serbestlik derecesidir. F testi yaparken de t testi yaptığımızdabulduğumuz gibi bir F kritik değeri bulmamız gerekli. Ancak bu sefer t tablo değeri değil, F tablo değeri kullanmalıyız. Bulmamız gereken F değeri $F_{q, n-k-1}$ değeridir. F dağılımı için \%10, \%5, \%1'lik kritik değerler mevcuttur. 

F istatistiğini bulmanın bir başka yolu $R^2$ kullanmaktır.

$$
F= \frac{R^2_{ur}-R^2_r}{1-R^2_{ur}} \cdot \frac{n-k-1}{q}
$$

### Dışlama Kısıtlarının Test Edilmesi Örneği

F testi örneği için kullanacağımız data seti HPRICE1. Şimdi bu veri setini yükleyelim ve verilere bir göz atalım.


```r
data("hprice1")
paged_table(hprice1)
```

<div data-pagedtable="false">
  <script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["price"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["assess"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["bdrms"],"name":[3],"type":["int"],"align":["right"]},{"label":["lotsize"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["sqrft"],"name":[5],"type":["int"],"align":["right"]},{"label":["colonial"],"name":[6],"type":["int"],"align":["right"]},{"label":["lprice"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["lassess"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["llotsize"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["lsqrft"],"name":[10],"type":["dbl"],"align":["right"]}],"data":[{"1":"300.000","2":"349.1","3":"4","4":"6126","5":"2438","6":"1","7":"5.703783","8":"5.855359","9":"8.720297","10":"7.798934","_rn_":"1"},{"1":"370.000","2":"351.5","3":"3","4":"9903","5":"2076","6":"1","7":"5.913503","8":"5.862210","9":"9.200593","10":"7.638198","_rn_":"2"},{"1":"191.000","2":"217.7","3":"3","4":"5200","5":"1374","6":"0","7":"5.252274","8":"5.383118","9":"8.556414","10":"7.225482","_rn_":"3"},{"1":"195.000","2":"231.8","3":"3","4":"4600","5":"1448","6":"1","7":"5.273000","8":"5.445875","9":"8.433811","10":"7.277938","_rn_":"4"},{"1":"373.000","2":"319.1","3":"4","4":"6095","5":"2514","6":"1","7":"5.921578","8":"5.765504","9":"8.715224","10":"7.829630","_rn_":"5"},{"1":"466.275","2":"414.5","3":"5","4":"8566","5":"2754","6":"1","7":"6.144775","8":"6.027073","9":"9.055556","10":"7.920810","_rn_":"6"},{"1":"332.500","2":"367.8","3":"3","4":"9000","5":"2067","6":"1","7":"5.806640","8":"5.907539","9":"9.104980","10":"7.633853","_rn_":"7"},{"1":"315.000","2":"300.2","3":"3","4":"6210","5":"1731","6":"1","7":"5.752573","8":"5.704449","9":"8.733916","10":"7.456455","_rn_":"8"},{"1":"206.000","2":"236.1","3":"3","4":"6000","5":"1767","6":"0","7":"5.327876","8":"5.464255","9":"8.699514","10":"7.477038","_rn_":"9"},{"1":"240.000","2":"256.3","3":"3","4":"2892","5":"1890","6":"0","7":"5.480639","8":"5.546349","9":"7.969704","10":"7.544332","_rn_":"10"},{"1":"285.000","2":"314.0","3":"4","4":"6000","5":"2336","6":"1","7":"5.652489","8":"5.749393","9":"8.699514","10":"7.756196","_rn_":"11"},{"1":"300.000","2":"416.5","3":"5","4":"7047","5":"2634","6":"1","7":"5.703783","8":"6.031887","9":"8.860357","10":"7.876259","_rn_":"12"},{"1":"405.000","2":"434.0","3":"3","4":"12237","5":"3375","6":"1","7":"6.003887","8":"6.073044","9":"9.412219","10":"8.124150","_rn_":"13"},{"1":"212.000","2":"279.3","3":"3","4":"6460","5":"1899","6":"0","7":"5.356586","8":"5.632287","9":"8.773385","10":"7.549083","_rn_":"14"},{"1":"265.000","2":"287.5","3":"3","4":"6519","5":"2312","6":"1","7":"5.579730","8":"5.661223","9":"8.782476","10":"7.745868","_rn_":"15"},{"1":"227.400","2":"232.9","3":"4","4":"3597","5":"1760","6":"1","7":"5.426711","8":"5.450609","9":"8.187856","10":"7.473069","_rn_":"16"},{"1":"240.000","2":"303.8","3":"4","4":"5922","5":"2000","6":"0","7":"5.480639","8":"5.716370","9":"8.686430","10":"7.600903","_rn_":"17"},{"1":"285.000","2":"305.6","3":"3","4":"7123","5":"1774","6":"1","7":"5.652489","8":"5.722277","9":"8.871084","10":"7.480992","_rn_":"18"},{"1":"268.000","2":"266.7","3":"3","4":"5642","5":"1376","6":"1","7":"5.590987","8":"5.586124","9":"8.637994","10":"7.226936","_rn_":"19"},{"1":"310.000","2":"326.0","3":"4","4":"8602","5":"1835","6":"1","7":"5.736572","8":"5.786897","9":"9.059750","10":"7.514800","_rn_":"20"},{"1":"266.000","2":"294.3","3":"3","4":"5494","5":"2048","6":"1","7":"5.583496","8":"5.684599","9":"8.611412","10":"7.624619","_rn_":"21"},{"1":"270.000","2":"318.8","3":"3","4":"7800","5":"2124","6":"1","7":"5.598422","8":"5.764564","9":"8.961879","10":"7.661057","_rn_":"22"},{"1":"225.000","2":"294.2","3":"3","4":"6003","5":"1768","6":"0","7":"5.416101","8":"5.684260","9":"8.700015","10":"7.477604","_rn_":"23"},{"1":"150.000","2":"208.0","3":"4","4":"5218","5":"1732","6":"0","7":"5.010635","8":"5.337538","9":"8.559870","10":"7.457032","_rn_":"24"},{"1":"247.000","2":"239.7","3":"3","4":"9425","5":"1440","6":"1","7":"5.509388","8":"5.479388","9":"9.151121","10":"7.272398","_rn_":"25"},{"1":"275.000","2":"294.1","3":"3","4":"6114","5":"1932","6":"0","7":"5.616771","8":"5.683920","9":"8.718336","10":"7.566311","_rn_":"26"},{"1":"230.000","2":"267.4","3":"3","4":"6710","5":"1932","6":"0","7":"5.438079","8":"5.588746","9":"8.811355","10":"7.566311","_rn_":"27"},{"1":"343.000","2":"359.9","3":"3","4":"8577","5":"2106","6":"1","7":"5.837730","8":"5.885826","9":"9.056840","10":"7.652546","_rn_":"28"},{"1":"477.500","2":"478.1","3":"7","4":"8400","5":"3529","6":"1","7":"6.168564","8":"6.169820","9":"9.035987","10":"8.168770","_rn_":"29"},{"1":"350.000","2":"355.3","3":"4","4":"9773","5":"2051","6":"1","7":"5.857933","8":"5.872962","9":"9.187379","10":"7.626083","_rn_":"30"},{"1":"230.000","2":"217.8","3":"4","4":"4806","5":"1573","6":"1","7":"5.438079","8":"5.383577","9":"8.477620","10":"7.360740","_rn_":"31"},{"1":"335.000","2":"385.0","3":"4","4":"15086","5":"2829","6":"0","7":"5.814130","8":"5.953243","9":"9.621523","10":"7.947679","_rn_":"32"},{"1":"251.000","2":"224.3","3":"3","4":"5763","5":"1630","6":"1","7":"5.525453","8":"5.412984","9":"8.659213","10":"7.396335","_rn_":"33"},{"1":"235.000","2":"251.9","3":"4","4":"6383","5":"1840","6":"1","7":"5.459586","8":"5.529032","9":"8.761394","10":"7.517521","_rn_":"34"},{"1":"361.000","2":"354.9","3":"4","4":"9000","5":"2066","6":"1","7":"5.888878","8":"5.871836","9":"9.104980","10":"7.633369","_rn_":"35"},{"1":"190.000","2":"212.5","3":"4","4":"3500","5":"1702","6":"0","7":"5.247024","8":"5.358942","9":"8.160519","10":"7.439559","_rn_":"36"},{"1":"360.000","2":"452.4","3":"4","4":"10892","5":"2750","6":"1","7":"5.886104","8":"6.114567","9":"9.295784","10":"7.919356","_rn_":"37"},{"1":"575.000","2":"518.1","3":"5","4":"15634","5":"3880","6":"1","7":"6.354370","8":"6.250168","9":"9.657204","10":"8.263591","_rn_":"38"},{"1":"209.001","2":"289.4","3":"4","4":"6400","5":"1854","6":"1","7":"5.342339","8":"5.667810","9":"8.764053","10":"7.525101","_rn_":"39"},{"1":"225.000","2":"268.1","3":"2","4":"8880","5":"1421","6":"0","7":"5.416101","8":"5.591360","9":"9.091557","10":"7.259116","_rn_":"40"},{"1":"246.000","2":"278.5","3":"3","4":"6314","5":"1662","6":"1","7":"5.505332","8":"5.629418","9":"8.750525","10":"7.415777","_rn_":"41"},{"1":"713.500","2":"655.4","3":"5","4":"28231","5":"3331","6":"1","7":"6.570182","8":"6.485246","9":"10.248176","10":"8.111028","_rn_":"42"},{"1":"248.000","2":"273.3","3":"4","4":"7050","5":"1656","6":"1","7":"5.513429","8":"5.610570","9":"8.860783","10":"7.412160","_rn_":"43"},{"1":"230.000","2":"212.1","3":"3","4":"5305","5":"1171","6":"0","7":"5.438079","8":"5.357058","9":"8.576406","10":"7.065613","_rn_":"44"},{"1":"375.000","2":"354.0","3":"5","4":"6637","5":"2293","6":"1","7":"5.926926","8":"5.869297","9":"8.800415","10":"7.737616","_rn_":"45"},{"1":"265.000","2":"252.1","3":"3","4":"7834","5":"1764","6":"1","7":"5.579730","8":"5.529826","9":"8.966228","10":"7.475339","_rn_":"46"},{"1":"313.000","2":"324.0","3":"3","4":"1000","5":"2768","6":"0","7":"5.746203","8":"5.780744","9":"6.907755","10":"7.925880","_rn_":"47"},{"1":"417.500","2":"475.5","3":"4","4":"8112","5":"3733","6":"0","7":"6.034285","8":"6.164367","9":"9.001100","10":"8.224967","_rn_":"48"},{"1":"253.000","2":"256.8","3":"3","4":"5850","5":"1536","6":"1","7":"5.533390","8":"5.548297","9":"8.674197","10":"7.336937","_rn_":"49"},{"1":"315.000","2":"279.2","3":"4","4":"6660","5":"1638","6":"1","7":"5.752573","8":"5.631928","9":"8.803875","10":"7.401231","_rn_":"50"},{"1":"264.000","2":"313.9","3":"3","4":"6637","5":"1972","6":"1","7":"5.575949","8":"5.749074","9":"8.800415","10":"7.586803","_rn_":"51"},{"1":"255.000","2":"279.8","3":"2","4":"15267","5":"1478","6":"0","7":"5.541264","8":"5.634075","9":"9.633449","10":"7.298445","_rn_":"52"},{"1":"210.000","2":"198.7","3":"3","4":"5146","5":"1408","6":"1","7":"5.347107","8":"5.291796","9":"8.545975","10":"7.249926","_rn_":"53"},{"1":"180.000","2":"221.5","3":"3","4":"6017","5":"1812","6":"1","7":"5.192957","8":"5.400423","9":"8.702344","10":"7.502186","_rn_":"54"},{"1":"250.000","2":"268.4","3":"3","4":"8410","5":"1722","6":"1","7":"5.521461","8":"5.592478","9":"9.037177","10":"7.451241","_rn_":"55"},{"1":"250.000","2":"282.3","3":"4","4":"5625","5":"1780","6":"1","7":"5.521461","8":"5.642970","9":"8.634976","10":"7.484369","_rn_":"56"},{"1":"209.000","2":"230.7","3":"4","4":"5600","5":"1674","6":"1","7":"5.342334","8":"5.441118","9":"8.630522","10":"7.422971","_rn_":"57"},{"1":"258.000","2":"287.0","3":"4","4":"6525","5":"1850","6":"1","7":"5.552959","8":"5.659482","9":"8.783396","10":"7.522941","_rn_":"58"},{"1":"289.000","2":"298.7","3":"3","4":"6060","5":"1925","6":"1","7":"5.666427","8":"5.699440","9":"8.709465","10":"7.562681","_rn_":"59"},{"1":"316.000","2":"314.6","3":"4","4":"5539","5":"2343","6":"0","7":"5.755742","8":"5.751302","9":"8.619569","10":"7.759187","_rn_":"60"},{"1":"225.000","2":"291.0","3":"3","4":"7566","5":"1567","6":"0","7":"5.416101","8":"5.673323","9":"8.931419","10":"7.356918","_rn_":"61"},{"1":"266.000","2":"286.4","3":"4","4":"5484","5":"1664","6":"1","7":"5.583496","8":"5.657390","9":"8.609590","10":"7.416980","_rn_":"62"},{"1":"310.000","2":"253.6","3":"6","4":"5348","5":"1386","6":"1","7":"5.736572","8":"5.535758","9":"8.584478","10":"7.234177","_rn_":"63"},{"1":"471.250","2":"482.0","3":"5","4":"15834","5":"2617","6":"1","7":"6.155389","8":"6.177944","9":"9.669915","10":"7.869784","_rn_":"64"},{"1":"335.000","2":"384.3","3":"4","4":"8022","5":"2321","6":"1","7":"5.814130","8":"5.951424","9":"8.989944","10":"7.749753","_rn_":"65"},{"1":"495.000","2":"543.6","3":"4","4":"11966","5":"2638","6":"1","7":"6.204558","8":"6.298213","9":"9.389825","10":"7.877776","_rn_":"66"},{"1":"279.500","2":"336.5","3":"4","4":"8460","5":"1915","6":"1","7":"5.633002","8":"5.818598","9":"9.043104","10":"7.557473","_rn_":"67"},{"1":"380.000","2":"515.1","3":"4","4":"15105","5":"2589","6":"1","7":"5.940171","8":"6.244361","9":"9.622781","10":"7.859027","_rn_":"68"},{"1":"325.000","2":"437.0","3":"4","4":"10859","5":"2709","6":"0","7":"5.783825","8":"6.079933","9":"9.292749","10":"7.904335","_rn_":"69"},{"1":"220.000","2":"263.4","3":"3","4":"6300","5":"1587","6":"1","7":"5.393628","8":"5.573674","9":"8.748305","10":"7.369601","_rn_":"70"},{"1":"215.000","2":"300.4","3":"3","4":"11554","5":"1694","6":"0","7":"5.370638","8":"5.705115","9":"9.354787","10":"7.434848","_rn_":"71"},{"1":"240.000","2":"250.7","3":"3","4":"6000","5":"1536","6":"1","7":"5.480639","8":"5.524257","9":"8.699514","10":"7.336937","_rn_":"72"},{"1":"725.000","2":"708.6","3":"5","4":"31000","5":"3662","6":"0","7":"6.586172","8":"6.563291","9":"10.341743","10":"8.205765","_rn_":"73"},{"1":"230.000","2":"276.3","3":"3","4":"4054","5":"1736","6":"1","7":"5.438079","8":"5.621487","9":"8.307459","10":"7.459339","_rn_":"74"},{"1":"306.000","2":"388.6","3":"2","4":"20700","5":"2205","6":"0","7":"5.723585","8":"5.962551","9":"9.937889","10":"7.698483","_rn_":"75"},{"1":"425.000","2":"252.5","3":"3","4":"5525","5":"1502","6":"0","7":"6.052089","8":"5.531411","9":"8.617039","10":"7.314553","_rn_":"76"},{"1":"318.000","2":"295.2","3":"4","4":"92681","5":"1696","6":"1","7":"5.762052","8":"5.687653","9":"11.436919","10":"7.436028","_rn_":"77"},{"1":"330.000","2":"359.5","3":"3","4":"8178","5":"2186","6":"1","7":"5.799093","8":"5.884714","9":"9.009203","10":"7.689829","_rn_":"78"},{"1":"246.000","2":"276.2","3":"4","4":"5944","5":"1928","6":"1","7":"5.505332","8":"5.621125","9":"8.690138","10":"7.564239","_rn_":"79"},{"1":"225.000","2":"249.8","3":"3","4":"18838","5":"1294","6":"0","7":"5.416101","8":"5.520660","9":"9.843632","10":"7.165493","_rn_":"80"},{"1":"111.000","2":"202.4","3":"4","4":"4315","5":"1535","6":"1","7":"4.709530","8":"5.310246","9":"8.369853","10":"7.336286","_rn_":"81"},{"1":"268.125","2":"254.0","3":"3","4":"5167","5":"1980","6":"1","7":"5.591453","8":"5.537334","9":"8.550048","10":"7.590852","_rn_":"82"},{"1":"244.000","2":"306.8","3":"4","4":"7893","5":"2090","6":"1","7":"5.497168","8":"5.726196","9":"8.973732","10":"7.644919","_rn_":"83"},{"1":"295.000","2":"318.3","3":"3","4":"6056","5":"1837","6":"1","7":"5.686975","8":"5.762994","9":"8.708805","10":"7.515889","_rn_":"84"},{"1":"236.000","2":"259.4","3":"3","4":"5828","5":"1715","6":"0","7":"5.463832","8":"5.558371","9":"8.670429","10":"7.447168","_rn_":"85"},{"1":"202.500","2":"258.1","3":"3","4":"6341","5":"1574","6":"0","7":"5.310740","8":"5.553347","9":"8.754792","10":"7.361375","_rn_":"86"},{"1":"219.000","2":"232.0","3":"2","4":"6362","5":"1185","6":"0","7":"5.389072","8":"5.446737","9":"8.758098","10":"7.077498","_rn_":"87"},{"1":"242.000","2":"252.0","3":"4","4":"4950","5":"1774","6":"1","7":"5.488938","8":"5.529429","9":"8.507143","10":"7.480992","_rn_":"88"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
Veri setinin ne ile ilgili olduğuna bakalım


```r
?hprice1
```

Açıklama
Wooldridge Kaynak: 1990 yılında Boston Globe'un emlak sayfalarından toplanmıştır. Bunlar Boston, MA bölgesinde satılan evlerdir.

Mesela price değişkeni ev fiyatlarını, assess değişkeni ev satılmadan önce belirlenmiş ev değerini, lotsize değişkeni arsa büyüklüğünü (feet kare cinsinden), sqrft değişkeni ev büyüklüğünü (feet kare cinsinden), bdrms yatak odası sayısını gösteriyor. lprice, lassess, llotsize ve lsqrft bütün bu değişkenlerin logaritması alınmış şekillerini temsil ediyor.


Kısıtsız modelimiz (unresricted model)

Kısıtsız modelimizle ev fiyatlarını tahmin etmeye çalışalım.

$$
log(price)= \beta_0 + \beta_1 log(assess) + \beta_2 log(lotsize)  + \beta_3 log(sqrft) + \beta_4 bdrms + u
$$


```r
evfiyaları_ur <- lm(lprice~ lassess+llotsize+lsqrft + bdrms,data = hprice1)
summary(evfiyaları_ur)
```

```
## 
## Call:
## lm(formula = lprice ~ lassess + llotsize + lsqrft + bdrms, data = hprice1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.53337 -0.06333  0.00686  0.07836  0.60825 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  0.263743   0.569665   0.463    0.645    
## lassess      1.043065   0.151446   6.887 1.01e-09 ***
## llotsize     0.007438   0.038561   0.193    0.848    
## lsqrft      -0.103238   0.138430  -0.746    0.458    
## bdrms        0.033839   0.022098   1.531    0.129    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.1481 on 83 degrees of freedom
## Multiple R-squared:  0.7728,	Adjusted R-squared:  0.7619 
## F-statistic: 70.58 on 4 and 83 DF,  p-value: < 2.2e-16
```

t teslerine bakarsak birtek llotsize anlamlı gibi görünüyor.

$$
H_0:  \beta_2=0, \beta_3=0, \beta_4=0
$$

Yukarıdaki hipotezimizi F testi kullanarak test edelim. Bu yüzden kısıtlı (restricted) modelimizi oluşturmamız gerekir.

$$
log(price)= \beta_0 + \beta_1 log(assess) + u
$$


```r
evfiyaları_r <- lm(lprice~ lassess,data = hprice1)
summary(evfiyaları_r)
```

```
## 
## Call:
## lm(formula = lprice ~ lassess, data = hprice1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.51044 -0.08257 -0.00496  0.08033  0.60799 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -0.16147    0.34607  -0.467    0.642    
## lassess      1.01341    0.06046  16.761   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.1478 on 86 degrees of freedom
## Multiple R-squared:  0.7656,	Adjusted R-squared:  0.7629 
## F-statistic: 280.9 on 1 and 86 DF,  p-value: < 2.2e-16
```

Bu iki modelde bize $R^2$'leri ve SSR'ları vermektedir. Model özetlerinden $R^2$'leri görsekte kayıt altına alabiliriz.


```r
r2_ur<-summary(evfiyaları_ur)$r.sq
r2_r<-summary(evfiyaları_r)$r.sq
r2_ur
```

```
## [1] 0.7728088
```

```r
r2_r
```

```
## [1] 0.7656314
```

Görüleceği üzere üç değiken eklememize rağmen kısıtsız (ur) modelin $R^2$'si kısıtlı modele (r) göre çok artmamış.

F testi

$$
F= \frac{R^2_{ur}-R^2_r}{1-R^2_{ur}} \cdot \frac{n-k-1}{q}
$$
Bu formülde diğer ihtiyacımız olan n,k ve q değerleri.

n için Global Environment kutusunda hprice1 veri setindeki gözlemlerin 88 tane olduğunu gözlemleyebiliyoruz. n değerinini kaydetmek istersek nobs fonksiyonu bize yardımcı olacaktır.


```r
n<-nobs(evfiyaları_ur)
n
```

```
## [1] 88
```

k kısıtsız modelimizde kaç tane bağımsız değişkenimiz olduğunu söyler. lassess, llotsize, lsqrft, bdrms olmak üzere 4 bağımsız değişken kullandık.


```r
k<-4
```

Son olarak q, kaç tane kısıt kullandığımız önemlidir. Hipotezimiz $H_0:  \beta_2=0, \beta_3=0, \beta_4=0 $ olduğuna göre toplam 3 tane kısıt kullandık.


```r
q<-3
```

Şimdi F_evfiyatlarını bulabiliriz.

$$
F= \frac{R^2_{ur}-R^2_r}{1-R^2_{ur}} \cdot \frac{n-k-1}{q}
$$


```r
F_evfiyatları<-((r2_ur-r2_r)/(1-r2_ur))*((n-k-1)/q)
F_evfiyatları
```

```
## [1] 0.8740445
```

Son olarak t testinde olduğu gibi F test sonucu karşılaştırabileceğimiz bir kritik değere ihtiyacımız var. Bulmamız gereken F değeri $F_{q, n-k-1}$ değeridir. Bunun için qf fonksiyonunu kullanacağız. \%99 kritik F değeri


```r
qf(0.99,q,n-k-1)
```

```
## [1] 4.026727
```

Görüleceği üzere test sonucumuz, kritik değerin çok altında. Bu yüzden hipotezimizi tahmin edebileceğiniz gibi kabul ediyoruz. 

$$
H_0:  \beta_2=0, \beta_3=0, \beta_4=0
$$ 

hipotezinin doğru olma olasığını bulmak istersek, 1-pf() fonksiyonunu kullanmamız yeterli.


```r
1-pf(F_evfiyatları,q,n-k-1)
```

```
## [1] 0.4580157
```
 
 Bu üç katsayının birlikte sıfır olma ihtimali yaklaşık olarak \%46 bu sonuç sıfır hipotezini kabul etmemiz için yeterli. Ancak hipotez kabul edilir diye bir açıklama yapılamaz.  Onun yerine $H_0:  \beta_2=0, \beta_3=0, \beta_4=0$ katsayılarının sıfır olduğu hipotezi \%45 anlamlılık seviyesinde bile reddedilememiştir denilir.
 
Diyelim ki hipotezimizi değiştirdik, bu üç sayının sıfır olduğunu kabul ediyoruz ve aynı zamanda $\beta_1$'in bire eşit olup olmadığını merak ediyoruz. Yeni sıfır hipotezimiz şu şekilde olacaktır.

$$
H_0: \beta_1=1, \beta_2=0, \beta_3=0, \beta_4=0
$$ 

 Bu durumda kısıtlı modelimizi artık şu şekilde yazabiliriz.
 
 Eski kısıtlı model
 
$$
log(price)= \beta_0 + \beta_1 log(assess) + u
$$

Yeni kısıtlı model $\beta_1$ bire eşit olduğu model olur ve şu şekilde yazılabilir.

$$
log(price) - log(assess) = \beta_0 + u
$$
 
Burda ev değerlemelerinin mantıksal olup olmadığını merak ediyoruz.

Burada kısıtsız modelimiz değişmemiş ancak kısıtlı model değişmiştir yeni kısıtlı modeli tahmin etmek için yeni bir y değerine ihtiyacımız var bu yeni y $y_{yeni}=log(price) - log(assess)$'dir.


```r
yyeni=hprice1$lprice-hprice1$lassess
```

Yeni kısıtlı modelimizi evfiyatları_r_yeni olarak kaydedelim ve sadece kesen katsayısıyla doğrusal regresyon sonucunu bulalım.


```r
evfiyatları_r_yeni <- lm(yyeni~ 1)
summary(evfiyatları_r_yeni)
```

```
## 
## Call:
## lm(formula = yyeni ~ 1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.51590 -0.08301 -0.00440  0.08498  0.60549 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -0.08481    0.01567  -5.412 5.43e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.147 on 87 degrees of freedom
```

Yeni kısıtlı modelimizin F istatistiğini bulmak için $R^2$ formu kullanılamaz. Çünkü artık iki farklı y kullanıyoruz. Kısıtsız modelimiz aynı ve y olarak lprice alınmıştı ancak şimdi yyeni değişkenini kullandık. Bu yüzden F istatistiği için SSR değerlerini kullanmalıyız.

Bildiğiniz gibi SSR sadece hata payının varyansının n-1 ile çarpılması

$$
SSR=(n-1) \cdot var(\hat{u})
$$

kısıtsız modelimizin hata payını bulalım.



```r
uhat_ur<-resid(evfiyaları_ur)
```
şimdi hata payının varyansını bulup n-1 ile çarpalım ve SSR_ur'yi bulalım.


```r
SSR_ur<- (n-1)*var(uhat_ur)
SSR_ur
```

```
## [1] 1.821529
```
 
Şimdi kısıtlı modelimizin SSR'ını bulmalıyız.


```r
uhat_r<-resid(evfiyatları_r_yeni)
SSR_r<- (n-1)*var(uhat_r)
SSR_r
```

```
## [1] 1.880149
```

Kısıtlı modelinizin SSR (hata payının karelerinin toplamı) Kısıtsız modelimizden çok fazla değil.

Şimdi F test değerimizi bulabiliriz.

$$
F= \frac{(SSR_r-SSR_{ur})/q}{SSR_{ur}/(n-k-1)}
$$
Formülde q artık ilk örneğimizde bulunan q'dan farklı, çünkü artık 4 kısıt kullanıyoruz. Kısıt sayısını hipotezimize bakıp hatırlayalım.

$$
H_0: \beta_1=1, \beta_2=0, \beta_3=0, \beta_4=0
$$ 

Yeni q sayımızı kaydedelim


```r
q_yeni=4
```

F test değeri


```r
F_evfiyatları_yeni<-((SSR_r-SSR_ur)/(q_yeni))/(SSR_ur/(n-k-1))
F_evfiyatları_yeni
```

```
## [1] 0.6677722
```

Bu F testti karşılaştıracağımız bir F kritik değerine ihtiyacımız var.


```r
qf(0.95,q_yeni,n-k-1)
```

```
## [1] 2.481661
```

Yine test değerimiz kritik değerin çok altında. Yine $H_0$'ı reddetmekte başarısız olduk.

Bu sonuçları tek tek bulmamıza gerek yok. car paketi sayesinde F testi sonuçlarını direk gözlemleyebiliriz. linearHypothesis komutu F testini yapmamıza yardımcı olacaktır. Kısıtsız modelimizin adını (evfiyatları_ur) hatırlamanız gerek.

$$
log(price)= \beta_0 + \beta_1 log(assess) + \beta_2 log(lotsize)  + \beta_3 log(sqrft) + \beta_4 bdrms + u
$$


```r
evfiyatları_ur <- lm(lprice~ lassess+llotsize+lsqrft + bdrms,data = hprice1)
summary(evfiyatları_ur)
```

```
## 
## Call:
## lm(formula = lprice ~ lassess + llotsize + lsqrft + bdrms, data = hprice1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.53337 -0.06333  0.00686  0.07836  0.60825 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  0.263743   0.569665   0.463    0.645    
## lassess      1.043065   0.151446   6.887 1.01e-09 ***
## llotsize     0.007438   0.038561   0.193    0.848    
## lsqrft      -0.103238   0.138430  -0.746    0.458    
## bdrms        0.033839   0.022098   1.531    0.129    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.1481 on 83 degrees of freedom
## Multiple R-squared:  0.7728,	Adjusted R-squared:  0.7619 
## F-statistic: 70.58 on 4 and 83 DF,  p-value: < 2.2e-16
```


```r
library(car)
```

```
## Loading required package: carData
```

```r
linearHypothesis(evfiyatları_ur, c("lassess=1", "llotsize=0","lsqrft=0","bdrms=0"))
```

```
## Linear hypothesis test
## 
## Hypothesis:
## lassess = 1
## llotsize = 0
## lsqrft = 0
## bdrms = 0
## 
## Model 1: restricted model
## Model 2: lprice ~ lassess + llotsize + lsqrft + bdrms
## 
##   Res.Df    RSS Df Sum of Sq      F Pr(>F)
## 1     87 1.8801                           
## 2     83 1.8215  4   0.05862 0.6678 0.6162
```

Sonuç bize hipotezlerimizi Res.Df'nin altında kısıtlı (restricted) ve kısıtsız (unrestricted) modellerin serbestlik derecelerini (n-k-1) verir. RSS'ler bizimde hesapladığımız  SSR değerleridir.  F değeri ve F'in olasılık değerleri verilmiştir. Sonuç olarak $H_0$ hipotezini \%60'lık bir anlamlılık düzeyinde bile reddedemeyiz.

## Ödev

A. Aşağıdaki soruları Rmarkdown'da yapın ve rpubs sitesine yükleyin. Ödevlerinizi web sitesi linki olarak gönderin. Tekrar 4 kişilik gruplar oluşturabilirsiniz.

1. Wooldridge veri setlerini araştırın ve 5 tanesinin açıklamasını yazın (sadece 3 değişkenin anlamını yazmanız yeterli).
2. Bu 5 veri setinden birini seçin ver en az 4 bağımısz değişkenli bir model tahmin edin. Değişkenlerde logaritma kullandınız mı? Neden kullandınız, neden kullanmadınız?
3. Modelinizin sonuçlarını açıklayın ve t testlerinden bahsedin.
4. Her bağımsız değişken katsayısı için bir güven aralığı oluşturun ve güven aralığı grafiğini çizin.
5. İstediğiniz katsayılar için bir kısıtlı model oluşturun ve F testi yapın. Sonuçlarınızı açıklayın.

B. R markdown ile basit bir CV hazırlayın ve yayınlayın. CV'nizin linkini ödev sonucu olarak paylaşın. Telefon numaralarınızı yazmanıza gerek yok.




 
 
 
