---
title: "R ile Çoklu Regresyon Analizi: (Wooldridge Örnekleri) "
author: "Dr. Hüseyin Utku Demir"
date: 2020-12-01T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
weight: 40
---

<link href="/rmarkdown-libs/pagedtable/css/pagedtable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/pagedtable/js/pagedtable.js"></script>
<script src="/rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="/rmarkdown-libs/plotly-binding/plotly.js"></script>
<script src="/rmarkdown-libs/typedarray/typedarray.min.js"></script>
<script src="/rmarkdown-libs/jquery/jquery.min.js"></script>
<link href="/rmarkdown-libs/crosstalk/css/crosstalk.min.css" rel="stylesheet" />
<script src="/rmarkdown-libs/crosstalk/js/crosstalk.min.js"></script>
<link href="/rmarkdown-libs/plotly-htmlwidgets-css/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="/rmarkdown-libs/plotly-main/plotly-latest.min.js"></script>

Önceki bölümlerde basit regresyon modeli ele alındı ancak basit regresyon açıklamak istediğimiz bağımlı değişkeni sadece bir bağımsız değişkenle açıklamaya çalıştığı için ceteris paribus (diğer herşey sabitken) varsayımını ihlal etmesi çok olasıydı. Üstelik bu bağımlı değişkeni açıklayan ve bağımlı değişkenin üzerinde de etkisi olan başka bir değişken olmaması olasılığı da çok düşüktü. Çoklu regresyon modeli tahmincimize başka değişkenler ekleyerek y nin üzerindeki varyasyonu daha fazla açıklama şansı doğuracaktır. Çoklu regresyon modelinin bir diğer avantajı bağımsız değişkenin derecelerini arttırarak parametrelerde doğrusal olmasına rağmen doğrusal olmayan fonksiyonlar elde edilebilir ve daha iyi bir açıklayıcı elde edilebilir. Çoklu regresyon analizinde bir çok fonksiyonel form kullanılabilir ve bu bize daha fazla esneklik sağlar.

## İki bağımsız değişkenli model

Bu bölümün Wooldridge kitabınızda bulunan ilk örnek maaş (wage) bağımlı değişkenin iki bağımsız değişkenle açıklamaya çalıştığımız model. Bu modeli tekrar hatırlayalım.

$$
wage= \beta_0 + \beta_1 educ + \beta_2 exper + u
$$

Burada $exper$ iş hayatında ki deneyim yılı, $educ$ eğitim yılını gösteren bağımsız değişkenler, ve $u$ ise gözlemleyemediğimiz diğer faktörler olarak özetlenebilir. Burada basit regresyon modelinde de anlamaya çalıştığımız gibi asıl ilgilendiğimiz parametre $\beta_1$ yani maaşı etkileyen diğer bütün faktörleri sabit tuttuğumuzda eğitimin gelir üzerinde ne kadar bir etkisi olduğu.

Basit regresyon bölümünde kurduğumuz modeli dikkate alalım

$$
wage= \beta_0 + \beta_1 educ + u
$$
Burada $\beta_2 exper$ gözlemleyemediğimiz diğer faktörler $u$’nun içindeydi. Çoklu regresyon modelimizde $\beta_2 exper$ terimini $u$’nun içinden çıkarıp modelimize ekleyince en azından deneyimin ($exper$), maaşlar ($wage$) üzerindeki etkisini $\beta_2$ katsayısıyla ölçebileceğiz.

Ancak hala yapmamız gereken önemli varsayımlar mevcut. Bu ikili değişken modelinin bize kattığı artık $\beta_1$ katsayısını en azından deneyimi ($exper$) sabit tutarak ölçebileceğimizi biliyoruz. Basit regresyon modelinde, yani deneyim ($exper$), $u$ teriminin içindeyken, deneyimin, eğitimle bir korelasyonu olmadığını varsaymak zorundaydık. Burada şunu unutmamak gerekir, iki açıklayıcı değişkenli modelde de hala $u$ teriminin içinde bulunan gözlemleyemediğimiz değişkenler, eğitim ($educ$) ve deneyim ($exper$) değişkenleriyle ilgisiz olmalıdır. Bunun sağlanması çok zor olan bir varsayım olduğunu aklınızdan çıkarmayın.

Anlaşıldığı gibi, bu bölüm atlanan (gözlemlenemeyen) değişken sapmasını (“omitted variable bias”) da belli bir ölçüde açıklayacaktır. Çoklu regresyon modelini kullanmamızın bir diğer nedeni de örneğimizden anlaşılacağı üzere gözlemlenemeyen (atlanan) değişken sapmasını ortadan kaldırabilmektir.

Çoklu regresyonun ana fikirlerinden biri, bu ihmal edilen değişkenler hakkında verimiz varsa, onları ek regresörler olarak modele dahil edebilmek ve böylece diğer değişkenleri (deneyim ($exper$) gibi) sabit tutarken bir diğer regresörün (eğitim ($educ$) gibi) bağımsız değişken (maaşlar ($wage$) gibi) üzerindeki nedensel etkisini tahmin edebilmektir.

Alternatif olarak, eğer biri nedensel çıkarımlar değil de tahminle ilgileniyorsa, çoklu regresyon modeli, tek bir regresör kullanılarak yapılan tahminleri geliştirmek için birden fazla değişkenin regresör olarak kullanılmasını mümkün kılar. Bu konuya ilerideki kesimlerde daha detaylı olarak geri döneceğiz.

Kitabınızda sunulan bir diğer iki bağımsız değişkenli regresyon örneği, öğrenci başına yapılan harcamanın ($expend$), lise öğrencilerinin ortalama test sonuçları ($avgscore$) üzerindeki etkisini inceliyor. Örnek olarak şu model kullanılıyor.

$$
avgscore= \beta_0 + \beta_1 expend + \beta_2 avginc + u
$$
$avginc$ ailenin ortalama geliri ve $u$ diğer gözlemlenemeyen faktörleri temsil eder. Bulmaya çalıştığımız etki, öğrenci başına yapılan harcamanın ($expend$), lise öğrencilerinin ortalama test sonuçları ($avgscore$) üzerindeki etkisini gösteren $\beta_1$ dir. Ancak ailenin ortalama geliri, harcamalar üzerinde bir etkiye sahip olduğundan, $avginc$ değişkenini regresyona dahil etmemek, en küçük kareler metoduyla bulduğumuz basit regresyon katsayısını ($\beta_1$) sapmalı hale getirecektir.

İki bağımsız değişkenli çoklu regresyon modelini genel bir şekilde yazarsak,

$$
y= \beta_0 + \beta_1 x_1+ \beta_2 x_2 + u
$$

Burada,

$\beta_0$ kesen,
$\beta_1$ diğer faktörleri sabit tutarak y’deki değişimi x1’e göre ölçer
$\beta_2$ diğer faktörleri sabit tutarak y’deki değişimi x2’ye göre ölçer

İki açıklayıcı değişkenli regresyon modelinin kitabınızdaki bir diğer örneği, doğrusal regresyon modelinin fonksiyonel olarak yazılabildiğini göstermek için verilmiştir. Ailenin tüketimini, ailenin gelirinin ikinci dereceden (quadratic) bir fonksiyonu olarak gösterirsek

$$
cons= \beta_0 + \beta_1 inc+ \beta_2 inc^2 + u
$$

$cons$ ailenin tüketimi, $inc$ ailenin geliri, $u$ tüketimi etkileyen diğer faktörler olarak özetlenebilir.

## k bağımsız değişkenli model

Çoklu regresyon modeli olarak adlandırılabilir.

$$
y= \beta_0 + \beta_1 x_1 + \beta_2 x_2  + \beta_3 x_3 + ... + \beta_k x_k  + u
$$

$u$ terimi hata terimi veya gözlenemeyen diğer faktörler olarak adlandırılabilir.

Çoklu regresyon modelinin temel varsayımını hatırlayalım.

$$
E(u | x_1, x_2, x_3,...,x_k)=0
$$
Gözleyemediğimiz diğer faktörlerin, bağımsız değişkenlerle ilişkisiz olması gerektiğini gösteren varsayımdır.

############## Örnek3.1 Kolej Gpa’sının Belirleyicileri

3.  ödeviniz olarak da verdiğim kolej Gpa’sının belirleyicileri örneğinin datasını indirelim ve içinde bulunan değişkenlere göz atalım.

``` r
library(wooldridge)
data(gpa1)
```

``` r
library(rmarkdown)
paged_table(gpa1)
```

<div data-pagedtable="false">

<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["age"],"name":[1],"type":["int"],"align":["right"]},{"label":["soph"],"name":[2],"type":["int"],"align":["right"]},{"label":["junior"],"name":[3],"type":["int"],"align":["right"]},{"label":["senior"],"name":[4],"type":["int"],"align":["right"]},{"label":["senior5"],"name":[5],"type":["int"],"align":["right"]},{"label":["male"],"name":[6],"type":["int"],"align":["right"]},{"label":["campus"],"name":[7],"type":["int"],"align":["right"]},{"label":["business"],"name":[8],"type":["int"],"align":["right"]},{"label":["engineer"],"name":[9],"type":["int"],"align":["right"]},{"label":["colGPA"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["hsGPA"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["ACT"],"name":[12],"type":["int"],"align":["right"]},{"label":["job19"],"name":[13],"type":["int"],"align":["right"]},{"label":["job20"],"name":[14],"type":["int"],"align":["right"]},{"label":["drive"],"name":[15],"type":["int"],"align":["right"]},{"label":["bike"],"name":[16],"type":["int"],"align":["right"]},{"label":["walk"],"name":[17],"type":["int"],"align":["right"]},{"label":["voluntr"],"name":[18],"type":["int"],"align":["right"]},{"label":["PC"],"name":[19],"type":["int"],"align":["right"]},{"label":["greek"],"name":[20],"type":["int"],"align":["right"]},{"label":["car"],"name":[21],"type":["int"],"align":["right"]},{"label":["siblings"],"name":[22],"type":["int"],"align":["right"]},{"label":["bgfriend"],"name":[23],"type":["int"],"align":["right"]},{"label":["clubs"],"name":[24],"type":["int"],"align":["right"]},{"label":["skipped"],"name":[25],"type":["dbl"],"align":["right"]},{"label":["alcohol"],"name":[26],"type":["dbl"],"align":["right"]},{"label":["gradMI"],"name":[27],"type":["int"],"align":["right"]},{"label":["fathcoll"],"name":[28],"type":["int"],"align":["right"]},{"label":["mothcoll"],"name":[29],"type":["int"],"align":["right"]}],"data":[{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.0","12":"21","13":"0","14":"1","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"2.00","26":"1.00","27":"1","28":"0","29":"0","_rn_":"1"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.4","11":"3.2","12":"24","13":"0","14":"1","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"0","23":"1","24":"1","25":"0.00","26":"1.00","27":"1","28":"1","29":"1","_rn_":"2"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.6","12":"26","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"1","25":"0.00","26":"1.00","27":"1","28":"1","29":"1","_rn_":"3"},{"1":"19","2":"1","3":"0","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"3.5","11":"3.5","12":"27","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1","23":"0","24":"0","25":"0.00","26":"0.00","27":"0","28":"0","29":"0","_rn_":"4"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.6","11":"3.9","12":"28","13":"0","14":"1","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"0","25":"0.00","26":"1.50","27":"1","28":"1","29":"0","_rn_":"5"},{"1":"20","2":"0","3":"0","4":"1","5":"0","6":"1","7":"1","8":"1","9":"0","10":"3.0","11":"3.4","12":"25","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"0.00","26":"0.00","27":"0","28":"1","29":"0","_rn_":"6"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"0","7":"0","8":"1","9":"0","10":"2.7","11":"3.5","12":"25","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"0","24":"1","25":"0.00","26":"2.00","27":"1","28":"0","29":"1","_rn_":"7"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"0","7":"0","8":"0","9":"0","10":"2.7","11":"3.0","12":"22","13":"1","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"0","22":"1","23":"1","24":"0","25":"3.00","26":"3.00","27":"1","28":"1","29":"1","_rn_":"8"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"0","7":"0","8":"0","9":"0","10":"2.7","11":"3.0","12":"21","13":"1","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"1","25":"2.00","26":"2.50","27":"1","28":"1","29":"1","_rn_":"9"},{"1":"19","2":"1","3":"0","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.8","11":"4.0","12":"27","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"1","23":"0","24":"1","25":"0.50","26":"0.75","27":"1","28":"0","29":"1","_rn_":"10"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.8","11":"3.0","12":"19","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"0","25":"2.00","26":"1.00","27":"1","28":"0","29":"0","_rn_":"11"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"0","7":"1","8":"1","9":"0","10":"2.9","11":"3.1","12":"22","13":"0","14":"1","15":"0","16":"0","17":"1","18":"1","19":"0","20":"0","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"1.00","27":"1","28":"0","29":"1","_rn_":"12"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"1","8":"1","9":"0","10":"3.0","11":"3.5","12":"23","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"1.00","27":"1","28":"0","29":"1","_rn_":"13"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"2.9","11":"3.8","12":"29","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1","23":"0","24":"0","25":"3.00","26":"2.50","27":"0","28":"1","29":"1","_rn_":"14"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.3","11":"3.7","12":"25","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"1","21":"0","22":"1","23":"0","24":"0","25":"1.00","26":"4.00","27":"1","28":"1","29":"1","_rn_":"15"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.6","11":"3.0","12":"21","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"1","25":"3.00","26":"3.50","27":"1","28":"1","29":"0","_rn_":"16"},{"1":"19","2":"1","3":"0","4":"0","5":"0","6":"1","7":"0","8":"0","9":"1","10":"2.5","11":"3.5","12":"29","13":"0","14":"1","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"0","25":"4.00","26":"3.00","27":"1","28":"1","29":"0","_rn_":"17"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.5","11":"3.0","12":"23","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"1","25":"5.00","26":"5.00","27":"0","28":"1","29":"0","_rn_":"18"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.4","11":"3.0","12":"21","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"2.00","26":"4.00","27":"0","28":"1","29":"0","_rn_":"19"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.6","11":"3.5","12":"29","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"5.00","27":"1","28":"1","29":"1","_rn_":"20"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.6","11":"3.5","12":"25","13":"1","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"1","24":"1","25":"3.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"21"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"0","9":"1","10":"2.7","11":"3.0","12":"23","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"1.00","27":"1","28":"0","29":"1","_rn_":"22"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.9","11":"3.6","12":"27","13":"0","14":"0","15":"0","16":"1","17":"0","18":"1","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"1.00","27":"0","28":"1","29":"0","_rn_":"23"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"1","8":"0","9":"0","10":"3.0","11":"4.0","12":"25","13":"1","14":"0","15":"0","16":"1","17":"0","18":"1","19":"1","20":"1","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"0.00","27":"1","28":"0","29":"0","_rn_":"24"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.3","11":"3.6","12":"33","13":"0","14":"0","15":"0","16":"1","17":"0","18":"1","19":"0","20":"1","21":"0","22":"1","23":"1","24":"0","25":"2.00","26":"5.00","27":"1","28":"1","29":"0","_rn_":"25"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.1","11":"3.3","12":"24","13":"1","14":"0","15":"0","16":"0","17":"1","18":"1","19":"0","20":"0","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"1.00","27":"1","28":"1","29":"0","_rn_":"26"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.6","12":"27","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"1","21":"0","22":"1","23":"1","24":"0","25":"2.00","26":"1.00","27":"1","28":"0","29":"0","_rn_":"27"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"3.2","11":"3.1","12":"20","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"1","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"28"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.4","12":"21","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"1","22":"0","23":"0","24":"0","25":"0.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"29"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.4","11":"3.7","12":"24","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1","23":"1","24":"0","25":"0.50","26":"2.00","27":"1","28":"1","29":"1","_rn_":"30"},{"1":"21","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.9","11":"3.7","12":"20","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"1.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"31"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.5","11":"3.3","12":"23","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"1","21":"1","22":"1","23":"1","24":"0","25":"1.00","26":"0.00","27":"1","28":"1","29":"1","_rn_":"32"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.7","11":"3.3","12":"22","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"1.00","27":"1","28":"1","29":"0","_rn_":"33"},{"1":"20","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.5","11":"3.5","12":"24","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"1","25":"0.00","26":"1.00","27":"1","28":"1","29":"1","_rn_":"34"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.8","11":"3.2","12":"28","13":"0","14":"1","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"3.00","27":"1","28":"1","29":"1","_rn_":"35"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"1","8":"1","9":"0","10":"2.5","11":"3.3","12":"25","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"1.00","27":"1","28":"1","29":"1","_rn_":"36"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.1","11":"3.4","12":"23","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"1","21":"1","22":"1","23":"1","24":"0","25":"0.50","26":"1.00","27":"1","28":"1","29":"1","_rn_":"37"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.5","11":"3.5","12":"24","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"3.00","27":"1","28":"1","29":"0","_rn_":"38"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.4","11":"3.4","12":"26","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"1","23":"1","24":"0","25":"0.50","26":"0.00","27":"1","28":"1","29":"1","_rn_":"39"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.5","11":"3.7","12":"23","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"1","21":"0","22":"1","23":"0","24":"1","25":"0.00","26":"2.00","27":"1","28":"0","29":"1","_rn_":"40"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.6","11":"2.5","12":"26","13":"0","14":"1","15":"0","16":"0","17":"1","18":"0","19":"1","20":"1","21":"1","22":"1","23":"1","24":"0","25":"1.00","26":"1.00","27":"0","28":"0","29":"0","_rn_":"41"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.8","11":"3.7","12":"23","13":"0","14":"1","15":"0","16":"0","17":"1","18":"1","19":"1","20":"1","21":"0","22":"1","23":"0","24":"1","25":"0.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"42"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.6","11":"3.0","12":"23","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"2.00","26":"3.00","27":"1","28":"0","29":"0","_rn_":"43"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.5","11":"3.0","12":"19","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"1","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"3.00","27":"1","28":"0","29":"1","_rn_":"44"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"0","7":"0","8":"1","9":"0","10":"4.0","11":"4.0","12":"26","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"0.50","27":"1","28":"1","29":"1","_rn_":"45"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.8","11":"3.8","12":"26","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"0","23":"1","24":"1","25":"1.00","26":"3.00","27":"1","28":"1","29":"1","_rn_":"46"},{"1":"19","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.8","11":"3.0","12":"21","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"1","21":"1","22":"1","23":"0","24":"0","25":"4.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"47"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.5","11":"3.7","12":"24","13":"1","14":"0","15":"0","16":"0","17":"1","18":"1","19":"0","20":"1","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"48"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.4","12":"24","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"1","22":"0","23":"0","24":"0","25":"2.00","26":"1.00","27":"1","28":"1","29":"1","_rn_":"49"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.6","11":"2.4","12":"24","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"1.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"50"},{"1":"21","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.8","12":"21","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"0","25":"1.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"51"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"0","7":"0","8":"0","9":"0","10":"3.7","11":"4.0","12":"25","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"52"},{"1":"19","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.5","12":"21","13":"1","14":"0","15":"0","16":"0","17":"1","18":"1","19":"0","20":"0","21":"1","22":"1","23":"0","24":"1","25":"0.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"53"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.9","11":"3.4","12":"27","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"3.00","27":"1","28":"1","29":"1","_rn_":"54"},{"1":"20","2":"0","3":"0","4":"1","5":"0","6":"1","7":"1","8":"0","9":"1","10":"2.6","11":"3.6","12":"19","13":"1","14":"0","15":"0","16":"1","17":"0","18":"1","19":"1","20":"0","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"0.00","27":"1","28":"1","29":"0","_rn_":"55"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"1","7":"0","8":"1","9":"0","10":"3.0","11":"3.2","12":"27","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"2.00","26":"5.00","27":"1","28":"1","29":"1","_rn_":"56"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.3","11":"3.8","12":"28","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1","23":"0","24":"1","25":"0.50","26":"1.00","27":"1","28":"0","29":"1","_rn_":"57"},{"1":"22","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.7","11":"3.3","12":"24","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"1","24":"1","25":"2.00","26":"3.00","27":"1","28":"1","29":"0","_rn_":"58"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"0","9":"0","10":"3.0","11":"3.4","12":"27","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"1","25":"0.00","26":"1.00","27":"1","28":"1","29":"1","_rn_":"59"},{"1":"21","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.2","11":"3.0","12":"24","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"0.00","26":"0.00","27":"1","28":"1","29":"1","_rn_":"60"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.7","11":"3.6","12":"27","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1","23":"0","24":"1","25":"1.00","26":"3.00","27":"1","28":"0","29":"1","_rn_":"61"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"1","8":"1","9":"0","10":"3.6","11":"3.9","12":"26","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"1","23":"0","24":"0","25":"1.00","26":"2.00","27":"1","28":"1","29":"0","_rn_":"62"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.4","11":"3.0","12":"19","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"0","24":"1","25":"2.00","26":"3.00","27":"1","28":"0","29":"1","_rn_":"63"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.9","11":"3.0","12":"24","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"0","25":"1.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"64"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"1","8":"0","9":"0","10":"3.3","11":"3.3","12":"26","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"1.00","27":"1","28":"0","29":"0","_rn_":"65"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.5","11":"3.3","12":"28","13":"0","14":"0","15":"0","16":"0","17":"1","18":"1","19":"1","20":"0","21":"1","22":"1","23":"0","24":"1","25":"0.50","26":"1.50","27":"1","28":"1","29":"1","_rn_":"66"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"0","9":"0","10":"3.0","11":"3.2","12":"22","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"1","25":"2.00","26":"3.00","27":"1","28":"1","29":"1","_rn_":"67"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.0","11":"3.4","12":"27","13":"0","14":"1","15":"0","16":"1","17":"0","18":"1","19":"0","20":"1","21":"1","22":"1","23":"0","24":"1","25":"0.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"68"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"0","9":"1","10":"2.8","11":"3.7","12":"26","13":"1","14":"0","15":"0","16":"1","17":"0","18":"1","19":"1","20":"0","21":"0","22":"1","23":"0","24":"1","25":"0.00","26":"1.00","27":"0","28":"0","29":"1","_rn_":"69"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"1","8":"0","9":"0","10":"2.9","11":"3.4","12":"26","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"0","25":"0.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"70"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"0","9":"1","10":"3.8","11":"3.9","12":"30","13":"0","14":"1","15":"0","16":"1","17":"0","18":"1","19":"1","20":"1","21":"1","22":"1","23":"1","24":"1","25":"2.00","26":"7.00","27":"1","28":"1","29":"1","_rn_":"71"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.5","11":"3.6","12":"24","13":"0","14":"1","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"1","22":"1","23":"0","24":"0","25":"2.00","26":"1.00","27":"1","28":"0","29":"0","_rn_":"72"},{"1":"21","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.0","11":"4.0","12":"26","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"4.00","27":"1","28":"0","29":"0","_rn_":"73"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.2","11":"3.6","12":"21","13":"0","14":"1","15":"0","16":"1","17":"0","18":"1","19":"0","20":"0","21":"0","22":"1","23":"0","24":"1","25":"1.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"74"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"1","8":"1","9":"0","10":"2.2","11":"3.0","12":"24","13":"1","14":"0","15":"1","16":"0","17":"0","18":"1","19":"1","20":"0","21":"1","22":"0","23":"0","24":"0","25":"0.00","26":"1.00","27":"0","28":"1","29":"1","_rn_":"75"},{"1":"30","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"0","9":"0","10":"3.4","11":"2.8","12":"24","13":"0","14":"1","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"0.00","27":"1","28":"0","29":"0","_rn_":"76"},{"1":"22","2":"0","3":"1","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"2.9","11":"3.2","12":"23","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"0.00","26":"3.00","27":"1","28":"1","29":"0","_rn_":"77"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.7","11":"2.9","12":"26","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"1","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"5.00","27":"1","28":"1","29":"0","_rn_":"78"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"2.9","11":"2.9","12":"24","13":"1","14":"0","15":"0","16":"1","17":"0","18":"1","19":"0","20":"1","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"0.50","27":"0","28":"1","29":"1","_rn_":"79"},{"1":"23","2":"0","3":"0","4":"0","5":"1","6":"1","7":"1","8":"0","9":"0","10":"2.8","11":"3.6","12":"24","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1","23":"1","24":"1","25":"0.50","26":"1.00","27":"0","28":"1","29":"1","_rn_":"80"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"1","7":"0","8":"0","9":"0","10":"3.2","11":"3.4","12":"27","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1","23":"0","24":"1","25":"1.00","26":"2.00","27":"1","28":"1","29":"0","_rn_":"81"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.4","11":"3.6","12":"23","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"1","24":"1","25":"0.50","26":"2.00","27":"0","28":"1","29":"1","_rn_":"82"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"0","7":"0","8":"0","9":"0","10":"3.0","11":"3.2","12":"31","13":"1","14":"0","15":"1","16":"0","17":"0","18":"1","19":"1","20":"1","21":"1","22":"0","23":"1","24":"1","25":"2.00","26":"1.00","27":"1","28":"0","29":"1","_rn_":"83"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.5","11":"3.2","12":"24","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1","23":"1","24":"1","25":"2.00","26":"1.00","27":"1","28":"0","29":"1","_rn_":"84"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.5","11":"3.2","12":"16","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"1","21":"1","22":"0","23":"0","24":"0","25":"1.00","26":"3.00","27":"1","28":"0","29":"1","_rn_":"85"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.1","11":"3.7","12":"27","13":"0","14":"0","15":"0","16":"1","17":"0","18":"1","19":"0","20":"1","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"4.00","27":"0","28":"1","29":"1","_rn_":"86"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.8","11":"2.9","12":"22","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"0","25":"0.00","26":"7.00","27":"1","28":"1","29":"1","_rn_":"87"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.9","11":"3.3","12":"23","13":"0","14":"1","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"88"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"1","8":"1","9":"0","10":"2.9","11":"3.1","12":"24","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"1","25":"2.00","26":"3.00","27":"1","28":"1","29":"0","_rn_":"89"},{"1":"19","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.4","11":"3.5","12":"24","13":"0","14":"0","15":"0","16":"1","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"1.00","27":"1","28":"0","29":"0","_rn_":"90"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"3.4","11":"3.5","12":"23","13":"0","14":"1","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"1.50","27":"1","28":"1","29":"1","_rn_":"91"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.6","11":"3.7","12":"23","13":"0","14":"1","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"0","25":"3.00","26":"3.00","27":"1","28":"0","29":"0","_rn_":"92"},{"1":"26","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.2","11":"3.0","12":"23","13":"0","14":"0","15":"1","16":"0","17":"0","18":"1","19":"1","20":"0","21":"1","22":"1","23":"1","24":"0","25":"0.25","26":"0.50","27":"1","28":"1","29":"0","_rn_":"93"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"3.2","11":"3.8","12":"25","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"2.00","27":"0","28":"1","29":"1","_rn_":"94"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.8","11":"3.3","12":"21","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"0.50","27":"0","28":"1","29":"1","_rn_":"95"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"3.1","11":"3.6","12":"22","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"0.00","26":"1.00","27":"1","28":"0","29":"0","_rn_":"96"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"2.8","11":"3.2","12":"24","13":"1","14":"0","15":"0","16":"0","17":"1","18":"1","19":"1","20":"1","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"97"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.4","11":"3.6","12":"27","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"3.00","26":"3.00","27":"1","28":"1","29":"0","_rn_":"98"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"0","9":"0","10":"2.7","11":"3.5","12":"29","13":"0","14":"1","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"0","24":"0","25":"0.00","26":"3.00","27":"1","28":"1","29":"1","_rn_":"99"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.7","12":"24","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"0","25":"0.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"100"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.5","11":"2.7","12":"25","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"0","25":"0.50","26":"3.00","27":"1","28":"0","29":"1","_rn_":"101"},{"1":"25","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"0","9":"0","10":"2.5","11":"3.1","12":"23","13":"0","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"0","25":"1.00","26":"1.00","27":"1","28":"0","29":"0","_rn_":"102"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.7","11":"3.4","12":"22","13":"0","14":"0","15":"0","16":"1","17":"0","18":"1","19":"0","20":"0","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"2.00","27":"1","28":"1","29":"0","_rn_":"103"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.6","11":"3.3","12":"24","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"0","22":"1","23":"0","24":"1","25":"0.00","26":"3.00","27":"1","28":"1","29":"1","_rn_":"104"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.9","11":"3.4","12":"23","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"0.50","27":"1","28":"1","29":"1","_rn_":"105"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.8","11":"3.5","12":"26","13":"0","14":"0","15":"0","16":"0","17":"1","18":"1","19":"1","20":"1","21":"1","22":"1","23":"1","24":"0","25":"1.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"106"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"0","9":"0","10":"3.9","11":"3.9","12":"26","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"0","25":"0.00","26":"0.50","27":"1","28":"0","29":"0","_rn_":"107"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.8","11":"3.5","12":"22","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"1","25":"2.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"108"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.9","11":"4.0","12":"26","13":"1","14":"0","15":"0","16":"0","17":"1","18":"1","19":"1","20":"0","21":"1","22":"1","23":"0","24":"1","25":"0.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"109"},{"1":"21","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.2","11":"2.9","12":"28","13":"1","14":"0","15":"0","16":"1","17":"0","18":"1","19":"0","20":"1","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"2.50","27":"1","28":"1","29":"0","_rn_":"110"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.3","11":"3.3","12":"24","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"1","24":"0","25":"2.00","26":"4.00","27":"0","28":"1","29":"1","_rn_":"111"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.3","11":"3.5","12":"24","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1","23":"0","24":"1","25":"2.00","26":"2.00","27":"1","28":"0","29":"0","_rn_":"112"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"1","8":"1","9":"0","10":"3.2","11":"3.5","12":"23","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1","23":"1","24":"1","25":"0.00","26":"1.00","27":"1","28":"1","29":"0","_rn_":"113"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"1","7":"1","8":"0","9":"0","10":"3.1","11":"3.1","12":"16","13":"0","14":"1","15":"0","16":"0","17":"1","18":"1","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"0.00","27":"1","28":"1","29":"0","_rn_":"114"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.0","11":"3.1","12":"21","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"1","21":"0","22":"1","23":"0","24":"0","25":"1.00","26":"0.50","27":"1","28":"0","29":"1","_rn_":"115"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.4","11":"3.7","12":"30","13":"1","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"0","24":"0","25":"5.00","26":"3.00","27":"1","28":"0","29":"0","_rn_":"116"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.1","11":"3.3","12":"23","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1","23":"1","24":"1","25":"2.00","26":"1.00","27":"1","28":"1","29":"1","_rn_":"117"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.2","11":"3.7","12":"23","13":"1","14":"0","15":"0","16":"0","17":"1","18":"1","19":"0","20":"0","21":"0","22":"1","23":"0","24":"1","25":"2.00","26":"0.00","27":"1","28":"0","29":"0","_rn_":"118"},{"1":"20","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.3","11":"3.0","12":"23","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"0","25":"0.00","26":"3.00","27":"1","28":"1","29":"1","_rn_":"119"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"0","9":"0","10":"3.0","11":"3.8","12":"22","13":"1","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"0","25":"1.00","26":"3.00","27":"1","28":"1","29":"1","_rn_":"120"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.8","11":"3.5","12":"22","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"1","21":"0","22":"1","23":"0","24":"0","25":"1.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"121"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"0","9":"0","10":"2.8","11":"3.6","12":"25","13":"1","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"1","21":"1","22":"1","23":"1","24":"0","25":"3.00","26":"0.00","27":"1","28":"0","29":"0","_rn_":"122"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.7","11":"3.5","12":"27","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"4.00","26":"3.00","27":"1","28":"0","29":"0","_rn_":"123"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"1","8":"0","9":"0","10":"2.6","11":"3.0","12":"19","13":"0","14":"1","15":"0","16":"0","17":"1","18":"1","19":"0","20":"0","21":"1","22":"0","23":"1","24":"1","25":"1.00","26":"0.00","27":"1","28":"0","29":"1","_rn_":"124"},{"1":"19","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.9","11":"3.8","12":"23","13":"1","14":"0","15":"1","16":"0","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1","23":"0","24":"1","25":"1.00","26":"2.00","27":"0","28":"1","29":"1","_rn_":"125"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.5","12":"26","13":"1","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1","23":"1","24":"0","25":"2.00","26":"1.00","27":"1","28":"0","29":"1","_rn_":"126"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.6","12":"22","13":"0","14":"0","15":"0","16":"1","17":"0","18":"1","19":"0","20":"1","21":"1","22":"0","23":"0","24":"1","25":"0.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"127"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"0","9":"0","10":"2.9","11":"3.8","12":"24","13":"0","14":"1","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"0","22":"1","23":"1","24":"1","25":"2.00","26":"1.00","27":"0","28":"0","29":"0","_rn_":"128"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"3.3","11":"3.6","12":"26","13":"0","14":"1","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"0.00","27":"1","28":"0","29":"1","_rn_":"129"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.7","11":"3.3","12":"23","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"1","24":"1","25":"1.00","26":"3.00","27":"1","28":"0","29":"0","_rn_":"130"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.0","11":"3.2","12":"21","13":"1","14":"0","15":"1","16":"0","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"1","25":"1.00","26":"1.00","27":"1","28":"1","29":"1","_rn_":"131"},{"1":"20","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.9","11":"3.3","12":"22","13":"0","14":"0","15":"0","16":"1","17":"0","18":"1","19":"0","20":"1","21":"1","22":"1","23":"0","24":"0","25":"2.00","26":"1.00","27":"1","28":"1","29":"0","_rn_":"132"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"3.8","11":"3.6","12":"26","13":"0","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1","23":"1","24":"1","25":"0.00","26":"0.00","27":"1","28":"1","29":"1","_rn_":"133"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"2.9","11":"3.8","12":"30","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"1","25":"0.00","26":"1.00","27":"1","28":"1","29":"0","_rn_":"134"},{"1":"22","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.0","11":"3.3","12":"22","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"1","20":"0","21":"1","22":"1","23":"0","24":"1","25":"0.00","26":"3.00","27":"1","28":"1","29":"0","_rn_":"135"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"3.2","11":"3.2","12":"19","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"0","22":"1","23":"1","24":"0","25":"0.00","26":"3.00","27":"1","28":"0","29":"0","_rn_":"136"},{"1":"22","2":"0","3":"0","4":"0","5":"1","6":"0","7":"0","8":"1","9":"0","10":"3.0","11":"3.3","12":"23","13":"0","14":"1","15":"0","16":"0","17":"1","18":"1","19":"0","20":"0","21":"1","22":"1","23":"1","24":"1","25":"0.00","26":"0.00","27":"1","28":"0","29":"0","_rn_":"137"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"1","9":"0","10":"2.3","11":"3.6","12":"25","13":"0","14":"1","15":"0","16":"0","17":"1","18":"0","19":"0","20":"0","21":"1","22":"1","23":"0","24":"0","25":"1.00","26":"1.00","27":"1","28":"0","29":"0","_rn_":"138"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"0","7":"0","8":"1","9":"0","10":"2.8","11":"3.4","12":"21","13":"0","14":"1","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"1","22":"1","23":"1","24":"0","25":"0.00","26":"0.30","27":"1","28":"0","29":"0","_rn_":"139"},{"1":"20","2":"0","3":"1","4":"0","5":"0","6":"1","7":"1","8":"1","9":"0","10":"3.4","11":"3.7","12":"26","13":"0","14":"0","15":"0","16":"0","17":"1","18":"0","19":"0","20":"1","21":"1","22":"1","23":"1","24":"1","25":"3.00","26":"4.00","27":"1","28":"0","29":"1","_rn_":"140"},{"1":"21","2":"0","3":"0","4":"1","5":"0","6":"1","7":"0","8":"0","9":"0","10":"2.8","11":"3.3","12":"28","13":"1","14":"0","15":"0","16":"1","17":"0","18":"0","19":"0","20":"0","21":"0","22":"1","23":"1","24":"1","25":"3.00","26":"2.00","27":"1","28":"1","29":"1","_rn_":"141"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>

</div>

Örnek için kullanacağımız değişkenlerin tanımlarını şöyle yapabiliriz.

colGPA: MSU GPA, Michigan State Üniversitesi not ortalaması

hsGPA: high school GPA, lise not ortalaması

ACT: ‘achievement’ score, ACT, bir öğrencinin okulda ne öğrendiğini ölçen bir başarı testidir. SAT daha çok bir yetenek testidir, muhakeme ve sözel yetenekleri test eder. Üniversiteler SAT veya ACT sonuçları ile öğrenci kabul eder.

Kitabınızda regresyon sonuçları direk verilen örneğin sonuçlarını bulmak isterseniz şu komutları kullanabilirsiniz.

``` r
coklureg <- lm(colGPA~ hsGPA+ACT,data = gpa1)
summary(coklureg)
```

    ## 
    ## Call:
    ## lm(formula = colGPA ~ hsGPA + ACT, data = gpa1)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -0.85442 -0.24666 -0.02614  0.28127  0.85357 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) 1.286328   0.340822   3.774 0.000238 ***
    ## hsGPA       0.453456   0.095813   4.733 5.42e-06 ***
    ## ACT         0.009426   0.010777   0.875 0.383297    
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.3403 on 138 degrees of freedom
    ## Multiple R-squared:  0.1764, Adjusted R-squared:  0.1645 
    ## F-statistic: 14.78 on 2 and 138 DF,  p-value: 1.526e-06

$$
colGPA= 1.29 + 0.453 hsGPA+ 0.0094 ACT + u
$$

Peki bu modeli nasıl yorumlayacağız? İlk olarak kesişim katsayısı, hsGPA ve ACT’nin her ikisi de sıfır olursa, öngörülen üniversite GPA’sini göstermektedir ve örneğimizde 1.29 olarak hesaplanmıştır. Üniversiteye giden hiç kimsenin lise not ortalaması sıfır veya başarı testi sıfır olmadığı için, bu denklemdeki kesişim kendi başına anlamlı değildir. Eğim katsayılarına bakınca ikisinin de bekleneceği gibi pozitif olduğunu görüyoruz. Eğer ACT puanını sabit tutarsak, hsGPA’deki 1 birimlik artış colGPA üzerinde 0.453 puanlık bir artış yaratacaktır. Başka bir deyişle, eğer ACT puanları aynı olan iki öğrenci varsa ve bir öğrencinin lise not ortalaması diğer öğrenciden bir puan yüksekse, bu öğrencinin üniversite not ortalamasının yarım puan daha fazla olmasını tahmin edebiliriz.

Üniversite not ortalamalarının 4 üzerinden, ACT sonuçlarının 36 puan üzerinden hesaplandığı düşünülürse, ACT’nin eğimi 0.0094’ün üniversite not ortalaması üzerinde fazla bir etkisi olmadığı düşünülebilir. Hata paylarını göz önüne aldığımızda ACT’nin sadece küçük değil aynı zamanda istatiksel olarak da anlamlı olmadığını göreceğiz.

Basit regresyon örneğimizi hatırlarsak

``` r
basitreg <- lm(colGPA~ACT,data = gpa1)
summary(basitreg)
```

    ## 
    ## Call:
    ## lm(formula = colGPA ~ ACT, data = gpa1)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -0.85251 -0.25251 -0.04426  0.26400  0.89336 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)  2.40298    0.26420   9.095  8.8e-16 ***
    ## ACT          0.02706    0.01086   2.491   0.0139 *  
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.3656 on 139 degrees of freedom
    ## Multiple R-squared:  0.04275,    Adjusted R-squared:  0.03586 
    ## F-statistic: 6.207 on 1 and 139 DF,  p-value: 0.0139

ACT’nin katsayısı çoklu regresyona göre bir hayli büyük kalıyor (0.02706/0.009426=2.87 kat daha fazla). ACT değerinin çoklu regresyonda lise not ortalaması eklenince azaldığını gözlemliyoruz. Çünkü lise not ortalaması ve ACT arasında yüksek bir korelasyon var. Bu durum bize aslında basit regresyon kullanıldığında temel varsayımı ihlal ettiğimize dair güçlü bir ipucu veriyor.

Bu örnekte son olarak basit ve iki bağımsız değişkenli regresyon grafiklerini gösterelim. Basit regresyon örneğimiz için, dağılım grafiğine bir regresyon çizgisi eklememizin yeterli olduğunu hatırlayalım.

``` r
plot(gpa1$ACT,gpa1$colGPA)
abline(basitreg)
```

<img src="/courses/example/dersilk_files/figure-html/unnamed-chunk-4-1.png" width="672" />
Bu grafik sadece iki boyutlu olduğundan, iki boyutlu bilgisayar ekranlarımızda göstermek daha kolaydır. Y eksenine üniversite not ortalaması, X eksenine ACT puanlarını koyuyoruz. Son olarak bulduğumuz eğim ve kesen katsayılarını grafiğimizde temsil eden doğrumuzu çiziyoruz.

Ancak çok değişkenli regresyon grafiklerini, iki boyutlu bilgisayar ekranlarda göstermek biraz daha zor olabilir. En azından örneğimizdeki gibi üç boyutlu bir grafiğe ihtiyacımız var. Önce bütün değişkenler için üç boyutlu bir dağılım grafiği çizelim daha sonra doğru yerine bir düzlem eklememiz gerekecek.

``` r
library(plotly)
library(reshape2)
cf.mod <- coef(coklureg)
hsGPA <- seq(min(gpa1$hsGPA),max(gpa1$hsGPA),length.out=50)
ACT <- seq(min(gpa1$ACT),max(gpa1$ACT),length.out=50)
colGPA <- t(outer(hsGPA, ACT, function(x,y) cf.mod[1]+cf.mod[2]*x+cf.mod[3]*y))
p <- plot_ly(x=~hsGPA, y=~ACT, z=~colGPA,type="surface") %>%
  add_trace(data=gpa1, x=gpa1$hsGPA, y=gpa1$ACT, z=gpa1$colGPA, mode="markers", type="scatter3d", opacity=0.5)
p
```

<div id="htmlwidget-1" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"visdat":{"7bec66d1fd2f":["function () ","plotlyVisDat"],"7bec64454d65":["function () ","data"]},"cur_data":"7bec64454d65","attrs":{"7bec66d1fd2f":{"x":{},"y":{},"z":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"surface"},"7bec64454d65":{"x":[3,3.20000004768372,3.59999990463257,3.5,3.90000009536743,3.40000009536743,3.5,3,3,4,3,3.09999990463257,3.5,3.79999995231628,3.70000004768372,3,3.5,3,3,3.5,3.5,3,3.59999990463257,4,3.59999990463257,3.29999995231628,3.59999990463257,3.09999990463257,3.40000009536743,3.70000004768372,3.70000004768372,3.29999995231628,3.29999995231628,3.5,3.20000004768372,3.29999995231628,3.40000009536743,3.5,3.40000009536743,3.70000004768372,2.5,3.70000004768372,3,3,4,3.79999995231628,3,3.70000004768372,3.40000009536743,2.40000009536743,3.79999995231628,4,3.5,3.40000009536743,3.59999990463257,3.20000004768372,3.79999995231628,3.29999995231628,3.40000009536743,3,3.59999990463257,3.90000009536743,3,3,3.29999995231628,3.29999995231628,3.20000004768372,3.40000009536743,3.70000004768372,3.40000009536743,3.90000009536743,3.59999990463257,4,3.59999990463257,3,2.79999995231628,3.20000004768372,2.90000009536743,2.90000009536743,3.59999990463257,3.40000009536743,3.59999990463257,3.20000004768372,3.20000004768372,3.20000004768372,3.70000004768372,2.90000009536743,3.29999995231628,3.09999990463257,3.5,3.5,3.70000004768372,3,3.79999995231628,3.29999995231628,3.59999990463257,3.20000004768372,3.59999990463257,3.5,3.70000004768372,2.70000004768372,3.09999990463257,3.40000009536743,3.29999995231628,3.40000009536743,3.5,3.90000009536743,3.5,4,2.90000009536743,3.29999995231628,3.5,3.5,3.09999990463257,3.09999990463257,3.70000004768372,3.29999995231628,3.70000004768372,3,3.79999995231628,3.5,3.59999990463257,3.5,3,3.79999995231628,3.5,3.59999990463257,3.79999995231628,3.59999990463257,3.29999995231628,3.20000004768372,3.29999995231628,3.59999990463257,3.79999995231628,3.29999995231628,3.20000004768372,3.29999995231628,3.59999990463257,3.40000009536743,3.70000004768372,3.29999995231628],"y":[21,24,26,27,28,25,25,22,21,27,19,22,23,29,25,21,29,23,21,29,25,23,27,25,33,24,27,20,21,24,20,23,22,24,28,25,23,24,26,23,26,23,23,19,26,26,21,24,24,24,21,25,21,27,19,27,28,24,27,24,27,26,19,24,26,28,22,27,26,26,30,24,26,21,24,24,23,26,24,24,27,23,31,24,16,27,22,23,24,24,23,23,23,25,21,22,24,27,29,24,25,23,22,24,23,26,26,22,26,28,24,24,23,16,21,30,23,23,23,22,22,25,27,19,23,26,22,24,26,23,21,22,26,30,22,19,23,25,21,26,28],"z":[3,3.40000009536743,3,3.5,3.59999990463257,3,2.70000004768372,2.70000004768372,2.70000004768372,3.79999995231628,2.79999995231628,2.90000009536743,3,2.90000009536743,3.29999995231628,2.59999990463257,2.5,2.5,2.40000009536743,3.59999990463257,2.59999990463257,2.70000004768372,2.90000009536743,3,3.29999995231628,3.09999990463257,3,3.20000004768372,3,3.40000009536743,2.90000009536743,3.5,3.70000004768372,3.5,2.79999995231628,2.5,3.09999990463257,3.5,3.40000009536743,3.5,2.59999990463257,2.79999995231628,2.59999990463257,3.5,4,3.79999995231628,2.79999995231628,3.5,3,2.59999990463257,3,3.70000004768372,3,2.90000009536743,2.59999990463257,3,3.29999995231628,2.70000004768372,3,3.20000004768372,2.70000004768372,3.59999990463257,2.40000009536743,2.90000009536743,3.29999995231628,3.5,3,3,2.79999995231628,2.90000009536743,3.79999995231628,2.5,3,3.20000004768372,2.20000004768372,3.40000009536743,2.90000009536743,3.70000004768372,2.90000009536743,2.79999995231628,3.20000004768372,3.40000009536743,3,2.5,3.5,3.09999990463257,2.79999995231628,2.90000009536743,2.90000009536743,3.40000009536743,3.40000009536743,3.59999990463257,3.20000004768372,3.20000004768372,2.79999995231628,3.09999990463257,2.79999995231628,3.40000009536743,2.70000004768372,3,2.5,2.5,2.70000004768372,3.59999990463257,2.90000009536743,2.79999995231628,3.90000009536743,2.79999995231628,3.90000009536743,3.20000004768372,3.29999995231628,3.29999995231628,3.20000004768372,3.09999990463257,3,3.40000009536743,3.09999990463257,3.20000004768372,3.29999995231628,3,2.79999995231628,2.79999995231628,2.70000004768372,2.59999990463257,2.90000009536743,3,3,2.90000009536743,3.29999995231628,2.70000004768372,3,2.90000009536743,3.79999995231628,2.90000009536743,3,3.20000004768372,3,2.29999995231628,2.79999995231628,3.40000009536743,2.79999995231628],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d","mode":"markers","opacity":0.5,"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"hsGPA"},"yaxis":{"title":"ACT"},"zaxis":{"title":"colGPA"}},"hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.5}},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"colorbar":{"title":"colGPA","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":true,"x":[2.40000009536743,2.43265315464565,2.46530621392386,2.49795927320208,2.53061233248029,2.56326539175851,2.59591845103673,2.62857151031494,2.66122456959316,2.69387762887137,2.72653068814959,2.7591837474278,2.79183680670602,2.82448986598424,2.85714292526245,2.88979598454067,2.92244904381888,2.9551021030971,2.98775516237531,3.02040822165353,3.05306128093175,3.08571434020996,3.11836739948818,3.15102045876639,3.18367351804461,3.21632657732282,3.24897963660104,3.28163269587925,3.31428575515747,3.34693881443569,3.3795918737139,3.41224493299212,3.44489799227033,3.47755105154855,3.51020411082676,3.54285717010498,3.5755102293832,3.60816328866141,3.64081634793963,3.67346940721784,3.70612246649606,3.73877552577427,3.77142858505249,3.80408164433071,3.83673470360892,3.86938776288714,3.90204082216535,3.93469388144357,3.96734694072178,4],"y":[16,16.3469387755102,16.6938775510204,17.0408163265306,17.3877551020408,17.734693877551,18.0816326530612,18.4285714285714,18.7755102040816,19.1224489795918,19.469387755102,19.8163265306122,20.1632653061224,20.5102040816327,20.8571428571429,21.2040816326531,21.5510204081633,21.8979591836735,22.2448979591837,22.5918367346939,22.9387755102041,23.2857142857143,23.6326530612245,23.9795918367347,24.3265306122449,24.6734693877551,25.0204081632653,25.3673469387755,25.7142857142857,26.0612244897959,26.4081632653061,26.7551020408163,27.1020408163265,27.4489795918367,27.7959183673469,28.1428571428571,28.4897959183673,28.8367346938776,29.1836734693878,29.530612244898,29.8775510204082,30.2244897959184,30.5714285714286,30.9183673469388,31.265306122449,31.6122448979592,31.9591836734694,32.3061224489796,32.6530612244898,33],"z":[[2.52543813076926,2.54024485267359,2.55505157457792,2.56985829648225,2.58466501838658,2.5994717402909,2.61427846219523,2.62908518409956,2.64389190600389,2.65869862790821,2.67350534981254,2.68831207171687,2.7031187936212,2.71792551552552,2.73273223742985,2.74753895933418,2.76234568123851,2.77715240314284,2.79195912504716,2.80676584695149,2.82157256885582,2.83637929076015,2.85118601266447,2.8659927345688,2.88079945647313,2.89560617837746,2.91041290028178,2.92521962218611,2.94002634409044,2.95483306599477,2.9696397878991,2.98444650980342,2.99925323170775,3.01405995361208,3.02886667551641,3.04367339742073,3.05848011932506,3.07328684122939,3.08809356313372,3.10290028503804,3.11770700694237,3.1325137288467,3.14732045075103,3.16212717265536,3.17693389455968,3.19174061646401,3.20654733836834,3.22135406027267,3.23616078217699,3.25096750408132],[2.52870837992086,2.54351510182518,2.55832182372951,2.57312854563384,2.58793526753817,2.6027419894425,2.61754871134682,2.63235543325115,2.64716215515548,2.66196887705981,2.67677559896413,2.69158232086846,2.70638904277279,2.72119576467712,2.73600248658144,2.75080920848577,2.7656159303901,2.78042265229443,2.79522937419876,2.81003609610308,2.82484281800741,2.83964953991174,2.85445626181607,2.86926298372039,2.88406970562472,2.89887642752905,2.91368314943338,2.9284898713377,2.94329659324203,2.95810331514636,2.97291003705069,2.98771675895502,3.00252348085934,3.01733020276367,3.032136924668,3.04694364657233,3.06175036847665,3.07655709038098,3.09136381228531,3.10617053418964,3.12097725609396,3.13578397799829,3.15059069990262,3.16539742180695,3.18020414371128,3.1950108656156,3.20981758751993,3.22462430942426,3.23943103132859,3.25423775323291],[2.53197862907245,2.54678535097678,2.5615920728811,2.57639879478543,2.59120551668976,2.60601223859409,2.62081896049842,2.63562568240274,2.65043240430707,2.6652391262114,2.68004584811573,2.69485257002005,2.70965929192438,2.72446601382871,2.73927273573304,2.75407945763736,2.76888617954169,2.78369290144602,2.79849962335035,2.81330634525468,2.828113067159,2.84291978906333,2.85772651096766,2.87253323287199,2.88733995477631,2.90214667668064,2.91695339858497,2.9317601204893,2.94656684239362,2.96137356429795,2.97618028620228,2.99098700810661,3.00579373001094,3.02060045191526,3.03540717381959,3.05021389572392,3.06502061762825,3.07982733953257,3.0946340614369,3.10944078334123,3.12424750524556,3.13905422714988,3.15386094905421,3.16866767095854,3.18347439286287,3.1982811147672,3.21308783667152,3.22789455857585,3.24270128048018,3.25750800238451],[2.53524887822404,2.55005560012837,2.5648623220327,2.57966904393703,2.59447576584135,2.60928248774568,2.62408920965001,2.63889593155434,2.65370265345866,2.66850937536299,2.68331609726732,2.69812281917165,2.71292954107597,2.7277362629803,2.74254298488463,2.75734970678896,2.77215642869329,2.78696315059761,2.80176987250194,2.81657659440627,2.8313833163106,2.84619003821492,2.86099676011925,2.87580348202358,2.89061020392791,2.90541692583223,2.92022364773656,2.93503036964089,2.94983709154522,2.96464381344955,2.97945053535387,2.9942572572582,3.00906397916253,3.02387070106686,3.03867742297118,3.05348414487551,3.06829086677984,3.08309758868417,3.09790431058849,3.11271103249282,3.12751775439715,3.14232447630148,3.15713119820581,3.17193792011013,3.18674464201446,3.20155136391879,3.21635808582312,3.23116480772744,3.24597152963177,3.2607782515361],[2.53851912737563,2.55332584927996,2.56813257118429,2.58293929308862,2.59774601499295,2.61255273689727,2.6273594588016,2.64216618070593,2.65697290261026,2.67177962451458,2.68658634641891,2.70139306832324,2.71619979022757,2.73100651213189,2.74581323403622,2.76061995594055,2.77542667784488,2.79023339974921,2.80504012165353,2.81984684355786,2.83465356546219,2.84946028736652,2.86426700927084,2.87907373117517,2.8938804530795,2.90868717498383,2.92349389688815,2.93830061879248,2.95310734069681,2.96791406260114,2.98272078450547,2.99752750640979,3.01233422831412,3.02714095021845,3.04194767212278,3.0567543940271,3.07156111593143,3.08636783783576,3.10117455974009,3.11598128164441,3.13078800354874,3.14559472545307,3.1604014473574,3.17520816926173,3.19001489116605,3.20482161307038,3.21962833497471,3.23443505687904,3.24924177878336,3.26404850068769],[2.54178937652723,2.55659609843156,2.57140282033588,2.58620954224021,2.60101626414454,2.61582298604887,2.63062970795319,2.64543642985752,2.66024315176185,2.67504987366618,2.6898565955705,2.70466331747483,2.71947003937916,2.73427676128349,2.74908348318781,2.76389020509214,2.77869692699647,2.7935036489008,2.80831037080513,2.82311709270945,2.83792381461378,2.85273053651811,2.86753725842244,2.88234398032676,2.89715070223109,2.91195742413542,2.92676414603975,2.94157086794408,2.9563775898484,2.97118431175273,2.98599103365706,3.00079775556139,3.01560447746571,3.03041119937004,3.04521792127437,3.0600246431787,3.07483136508302,3.08963808698735,3.10444480889168,3.11925153079601,3.13405825270033,3.14886497460466,3.16367169650899,3.17847841841332,3.19328514031765,3.20809186222197,3.2228985841263,3.23770530603063,3.25251202793496,3.26731874983928],[2.54505962567882,2.55986634758315,2.57467306948748,2.5894797913918,2.60428651329613,2.61909323520046,2.63389995710479,2.64870667900911,2.66351340091344,2.67832012281777,2.6931268447221,2.70793356662642,2.72274028853075,2.73754701043508,2.75235373233941,2.76716045424374,2.78196717614806,2.79677389805239,2.81158061995672,2.82638734186105,2.84119406376537,2.8560007856697,2.87080750757403,2.88561422947836,2.90042095138268,2.91522767328701,2.93003439519134,2.94484111709567,2.959647839,2.97445456090432,2.98926128280865,3.00406800471298,3.01887472661731,3.03368144852163,3.04848817042596,3.06329489233029,3.07810161423462,3.09290833613894,3.10771505804327,3.1225217799476,3.13732850185193,3.15213522375625,3.16694194566058,3.18174866756491,3.19655538946924,3.21136211137357,3.22616883327789,3.24097555518222,3.25578227708655,3.27058899899088],[2.54832987483041,2.56313659673474,2.57794331863907,2.5927500405434,2.60755676244772,2.62236348435205,2.63717020625638,2.65197692816071,2.66678365006503,2.68159037196936,2.69639709387369,2.71120381577802,2.72601053768234,2.74081725958667,2.755623981491,2.77043070339533,2.78523742529966,2.80004414720398,2.81485086910831,2.82965759101264,2.84446431291697,2.85927103482129,2.87407775672562,2.88888447862995,2.90369120053428,2.9184979224386,2.93330464434293,2.94811136624726,2.96291808815159,2.97772481005592,2.99253153196024,3.00733825386457,3.0221449757689,3.03695169767323,3.05175841957755,3.06656514148188,3.08137186338621,3.09617858529054,3.11098530719486,3.12579202909919,3.14059875100352,3.15540547290785,3.17021219481218,3.1850189167165,3.19982563862083,3.21463236052516,3.22943908242949,3.24424580433381,3.25905252623814,3.27385924814247],[2.55160012398201,2.56640684588633,2.58121356779066,2.59602028969499,2.61082701159932,2.62563373350364,2.64044045540797,2.6552471773123,2.67005389921663,2.68486062112095,2.69966734302528,2.71447406492961,2.72928078683394,2.74408750873827,2.75889423064259,2.77370095254692,2.78850767445125,2.80331439635558,2.8181211182599,2.83292784016423,2.84773456206856,2.86254128397289,2.87734800587721,2.89215472778154,2.90696144968587,2.9217681715902,2.93657489349453,2.95138161539885,2.96618833730318,2.98099505920751,2.99580178111184,3.01060850301616,3.02541522492049,3.04022194682482,3.05502866872915,3.06983539063347,3.0846421125378,3.09944883444213,3.11425555634646,3.12906227825079,3.14386900015511,3.15867572205944,3.17348244396377,3.1882891658681,3.20309588777242,3.21790260967675,3.23270933158108,3.24751605348541,3.26232277538973,3.27712949729406],[2.5548703731336,2.56967709503793,2.58448381694225,2.59929053884658,2.61409726075091,2.62890398265524,2.64371070455956,2.65851742646389,2.67332414836822,2.68813087027255,2.70293759217687,2.7177443140812,2.73255103598553,2.74735775788986,2.76216447979419,2.77697120169851,2.79177792360284,2.80658464550717,2.8213913674115,2.83619808931582,2.85100481122015,2.86581153312448,2.88061825502881,2.89542497693313,2.91023169883746,2.92503842074179,2.93984514264612,2.95465186455045,2.96945858645477,2.9842653083591,2.99907203026343,3.01387875216776,3.02868547407208,3.04349219597641,3.05829891788074,3.07310563978507,3.08791236168939,3.10271908359372,3.11752580549805,3.13233252740238,3.14713924930671,3.16194597121103,3.17675269311536,3.19155941501969,3.20636613692402,3.22117285882834,3.23597958073267,3.250786302637,3.26559302454133,3.28039974644565],[2.55814062228519,2.57294734418952,2.58775406609385,2.60256078799817,2.6173675099025,2.63217423180683,2.64698095371116,2.66178767561548,2.67659439751981,2.69140111942414,2.70620784132847,2.7210145632328,2.73582128513712,2.75062800704145,2.76543472894578,2.78024145085011,2.79504817275443,2.80985489465876,2.82466161656309,2.83946833846742,2.85427506037174,2.86908178227607,2.8838885041804,2.89869522608473,2.91350194798905,2.92830866989338,2.94311539179771,2.95792211370204,2.97272883560637,2.98753555751069,3.00234227941502,3.01714900131935,3.03195572322368,3.046762445128,3.06156916703233,3.07637588893666,3.09118261084099,3.10598933274531,3.12079605464964,3.13560277655397,3.1504094984583,3.16521622036263,3.18002294226695,3.19482966417128,3.20963638607561,3.22444310797994,3.23924982988426,3.25405655178859,3.26886327369292,3.28366999559725],[2.56141087143678,2.57621759334111,2.59102431524544,2.60583103714977,2.62063775905409,2.63544448095842,2.65025120286275,2.66505792476708,2.6798646466714,2.69467136857573,2.70947809048006,2.72428481238439,2.73909153428872,2.75389825619304,2.76870497809737,2.7835117000017,2.79831842190603,2.81312514381035,2.82793186571468,2.84273858761901,2.85754530952334,2.87235203142766,2.88715875333199,2.90196547523632,2.91677219714065,2.93157891904498,2.9463856409493,2.96119236285363,2.97599908475796,2.99080580666229,3.00561252856661,3.02041925047094,3.03522597237527,3.0500326942796,3.06483941618392,3.07964613808825,3.09445285999258,3.10925958189691,3.12406630380124,3.13887302570556,3.15367974760989,3.16848646951422,3.18329319141855,3.19809991332287,3.2129066352272,3.22771335713153,3.24252007903586,3.25732680094018,3.27213352284451,3.28694024474884],[2.56468112058838,2.5794878424927,2.59429456439703,2.60910128630136,2.62390800820569,2.63871473011001,2.65352145201434,2.66832817391867,2.683134895823,2.69794161772732,2.71274833963165,2.72755506153598,2.74236178344031,2.75716850534464,2.77197522724896,2.78678194915329,2.80158867105762,2.81639539296195,2.83120211486627,2.8460088367706,2.86081555867493,2.87562228057926,2.89042900248359,2.90523572438791,2.92004244629224,2.93484916819657,2.9496558901009,2.96446261200522,2.97926933390955,2.99407605581388,3.00888277771821,3.02368949962253,3.03849622152686,3.05330294343119,3.06810966533552,3.08291638723984,3.09772310914417,3.1125298310485,3.12733655295283,3.14214327485716,3.15694999676148,3.17175671866581,3.18656344057014,3.20137016247447,3.21617688437879,3.23098360628312,3.24579032818745,3.26059705009178,3.27540377199611,3.29021049390043],[2.56795136973997,2.5827580916443,2.59756481354862,2.61237153545295,2.62717825735728,2.64198497926161,2.65679170116593,2.67159842307026,2.68640514497459,2.70121186687892,2.71601858878324,2.73082531068757,2.7456320325919,2.76043875449623,2.77524547640056,2.79005219830488,2.80485892020921,2.81966564211354,2.83447236401787,2.84927908592219,2.86408580782652,2.87889252973085,2.89369925163518,2.9085059735395,2.92331269544383,2.93811941734816,2.95292613925249,2.96773286115682,2.98253958306114,2.99734630496547,3.0121530268698,3.02695974877413,3.04176647067845,3.05657319258278,3.07137991448711,3.08618663639144,3.10099335829576,3.11580008020009,3.13060680210442,3.14541352400875,3.16022024591308,3.1750269678174,3.18983368972173,3.20464041162606,3.21944713353039,3.23425385543471,3.24906057733904,3.26386729924337,3.2786740211477,3.29348074305202],[2.57122161889156,2.58602834079589,2.60083506270022,2.61564178460454,2.63044850650887,2.6452552284132,2.66006195031753,2.67486867222185,2.68967539412618,2.70448211603051,2.71928883793484,2.73409555983917,2.74890228174349,2.76370900364782,2.77851572555215,2.79332244745648,2.8081291693608,2.82293589126513,2.83774261316946,2.85254933507379,2.86735605697811,2.88216277888244,2.89696950078677,2.9117762226911,2.92658294459543,2.94138966649975,2.95619638840408,2.97100311030841,2.98580983221274,3.00061655411706,3.01542327602139,3.03022999792572,3.04503671983005,3.05984344173437,3.0746501636387,3.08945688554303,3.10426360744736,3.11907032935169,3.13387705125601,3.14868377316034,3.16349049506467,3.178297216969,3.19310393887332,3.20791066077765,3.22271738268198,3.23752410458631,3.25233082649063,3.26713754839496,3.28194427029929,3.29675099220362],[2.57449186804315,2.58929858994748,2.60410531185181,2.61891203375614,2.63371875566046,2.64852547756479,2.66333219946912,2.67813892137345,2.69294564327777,2.7077523651821,2.72255908708643,2.73736580899076,2.75217253089509,2.76697925279941,2.78178597470374,2.79659269660807,2.8113994185124,2.82620614041672,2.84101286232105,2.85581958422538,2.87062630612971,2.88543302803404,2.90023974993836,2.91504647184269,2.92985319374702,2.94465991565135,2.95946663755567,2.97427335946,2.98908008136433,3.00388680326866,3.01869352517298,3.03350024707731,3.04830696898164,3.06311369088597,3.0779204127903,3.09272713469462,3.10753385659895,3.12234057850328,3.13714730040761,3.15195402231193,3.16676074421626,3.18156746612059,3.19637418802492,3.21118090992924,3.22598763183357,3.2407943537379,3.25560107564223,3.27040779754656,3.28521451945088,3.30002124135521],[2.57776211719475,2.59256883909907,2.6073755610034,2.62218228290773,2.63698900481206,2.65179572671638,2.66660244862071,2.68140917052504,2.69621589242937,2.7110226143337,2.72582933623802,2.74063605814235,2.75544278004668,2.77024950195101,2.78505622385533,2.79986294575966,2.81466966766399,2.82947638956832,2.84428311147264,2.85908983337697,2.8738965552813,2.88870327718563,2.90350999908996,2.91831672099428,2.93312344289861,2.94793016480294,2.96273688670727,2.97754360861159,2.99235033051592,3.00715705242025,3.02196377432458,3.0367704962289,3.05157721813323,3.06638394003756,3.08119066194189,3.09599738384621,3.11080410575054,3.12561082765487,3.1404175495592,3.15522427146353,3.17003099336785,3.18483771527218,3.19964443717651,3.21445115908084,3.22925788098516,3.24406460288949,3.25887132479382,3.27367804669815,3.28848476860248,3.3032914905068],[2.58103236634634,2.59583908825067,2.61064581015499,2.62545253205932,2.64025925396365,2.65506597586798,2.66987269777231,2.68467941967663,2.69948614158096,2.71429286348529,2.72909958538962,2.74390630729394,2.75871302919827,2.7735197511026,2.78832647300693,2.80313319491125,2.81793991681558,2.83274663871991,2.84755336062424,2.86236008252856,2.87716680443289,2.89197352633722,2.90678024824155,2.92158697014588,2.9363936920502,2.95120041395453,2.96600713585886,2.98081385776319,2.99562057966751,3.01042730157184,3.02523402347617,3.0400407453805,3.05484746728483,3.06965418918915,3.08446091109348,3.09926763299781,3.11407435490214,3.12888107680646,3.14368779871079,3.15849452061512,3.17330124251945,3.18810796442377,3.2029146863281,3.21772140823243,3.23252813013676,3.24733485204108,3.26214157394541,3.27694829584974,3.29175501775407,3.3065617396584],[2.58430261549793,2.59910933740226,2.61391605930659,2.62872278121091,2.64352950311524,2.65833622501957,2.6731429469239,2.68794966882822,2.70275639073255,2.71756311263688,2.73236983454121,2.74717655644554,2.76198327834986,2.77679000025419,2.79159672215852,2.80640344406285,2.82121016596717,2.8360168878715,2.85082360977583,2.86563033168016,2.88043705358448,2.89524377548881,2.91005049739314,2.92485721929747,2.9396639412018,2.95447066310612,2.96927738501045,2.98408410691478,2.99889082881911,3.01369755072343,3.02850427262776,3.04331099453209,3.05811771643642,3.07292443834075,3.08773116024507,3.1025378821494,3.11734460405373,3.13215132595806,3.14695804786238,3.16176476976671,3.17657149167104,3.19137821357537,3.20618493547969,3.22099165738402,3.23579837928835,3.25060510119268,3.26541182309701,3.28021854500133,3.29502526690566,3.30983198880999],[2.58757286464952,2.60237958655385,2.61718630845818,2.63199303036251,2.64679975226683,2.66160647417116,2.67641319607549,2.69121991797982,2.70602663988415,2.72083336178847,2.7356400836928,2.75044680559713,2.76525352750146,2.78006024940578,2.79486697131011,2.80967369321444,2.82448041511877,2.83928713702309,2.85409385892742,2.86890058083175,2.88370730273608,2.89851402464041,2.91332074654473,2.92812746844906,2.94293419035339,2.95774091225772,2.97254763416204,2.98735435606637,3.0021610779707,3.01696779987503,3.03177452177935,3.04658124368368,3.06138796558801,3.07619468749234,3.09100140939667,3.10580813130099,3.12061485320532,3.13542157510965,3.15022829701398,3.1650350189183,3.17984174082263,3.19464846272696,3.20945518463129,3.22426190653561,3.23906862843994,3.25387535034427,3.2686820722486,3.28348879415293,3.29829551605725,3.31310223796158],[2.59084311380112,2.60564983570544,2.62045655760977,2.6352632795141,2.65007000141843,2.66487672332276,2.67968344522708,2.69449016713141,2.70929688903574,2.72410361094007,2.73891033284439,2.75371705474872,2.76852377665305,2.78333049855738,2.7981372204617,2.81294394236603,2.82775066427036,2.84255738617469,2.85736410807901,2.87217082998334,2.88697755188767,2.901784273792,2.91659099569633,2.93139771760065,2.94620443950498,2.96101116140931,2.97581788331364,2.99062460521796,3.00543132712229,3.02023804902662,3.03504477093095,3.04985149283528,3.0646582147396,3.07946493664393,3.09427165854826,3.10907838045259,3.12388510235691,3.13869182426124,3.15349854616557,3.1683052680699,3.18311198997422,3.19791871187855,3.21272543378288,3.22753215568721,3.24233887759153,3.25714559949586,3.27195232140019,3.28675904330452,3.30156576520885,3.31637248711317],[2.59411336295271,2.60892008485704,2.62372680676136,2.63853352866569,2.65334025057002,2.66814697247435,2.68295369437868,2.697760416283,2.71256713818733,2.72737386009166,2.74218058199599,2.75698730390031,2.77179402580464,2.78660074770897,2.8014074696133,2.81621419151762,2.83102091342195,2.84582763532628,2.86063435723061,2.87544107913493,2.89024780103926,2.90505452294359,2.91986124484792,2.93466796675225,2.94947468865657,2.9642814105609,2.97908813246523,2.99389485436956,3.00870157627388,3.02350829817821,3.03831502008254,3.05312174198687,3.0679284638912,3.08273518579552,3.09754190769985,3.11234862960418,3.12715535150851,3.14196207341283,3.15676879531716,3.17157551722149,3.18638223912582,3.20118896103014,3.21599568293447,3.2308024048388,3.24560912674313,3.26041584864746,3.27522257055178,3.29002929245611,3.30483601436044,3.31964273626477],[2.5973836121043,2.61219033400863,2.62699705591296,2.64180377781728,2.65661049972161,2.67141722162594,2.68622394353027,2.7010306654346,2.71583738733892,2.73064410924325,2.74545083114758,2.76025755305191,2.77506427495623,2.78987099686056,2.80467771876489,2.81948444066922,2.83429116257355,2.84909788447787,2.8639046063822,2.87871132828653,2.89351805019086,2.90832477209518,2.92313149399951,2.93793821590384,2.95274493780817,2.96755165971249,2.98235838161682,2.99716510352115,3.01197182542548,3.0267785473298,3.04158526923413,3.05639199113846,3.07119871304279,3.08600543494712,3.10081215685144,3.11561887875577,3.1304256006601,3.14523232256443,3.16003904446875,3.17484576637308,3.18965248827741,3.20445921018174,3.21926593208607,3.23407265399039,3.24887937589472,3.26368609779905,3.27849281970338,3.2932995416077,3.30810626351203,3.32291298541636],[2.60065386125589,2.61546058316022,2.63026730506455,2.64507402696888,2.65988074887321,2.67468747077753,2.68949419268186,2.70430091458619,2.71910763649052,2.73391435839484,2.74872108029917,2.7635278022035,2.77833452410783,2.79314124601215,2.80794796791648,2.82275468982081,2.83756141172514,2.85236813362947,2.86717485553379,2.88198157743812,2.89678829934245,2.91159502124678,2.9264017431511,2.94120846505543,2.95601518695976,2.97082190886409,2.98562863076841,3.00043535267274,3.01524207457707,3.0300487964814,3.04485551838573,3.05966224029005,3.07446896219438,3.08927568409871,3.10408240600304,3.11888912790736,3.13369584981169,3.14850257171602,3.16330929362035,3.17811601552467,3.192922737429,3.20772945933333,3.22253618123766,3.23734290314199,3.25214962504631,3.26695634695064,3.28176306885497,3.2965697907593,3.31137651266362,3.32618323456795],[2.60392411040749,2.61873083231181,2.63353755421614,2.64834427612047,2.6631509980248,2.67795771992913,2.69276444183345,2.70757116373778,2.72237788564211,2.73718460754644,2.75199132945076,2.76679805135509,2.78160477325942,2.79641149516375,2.81121821706807,2.8260249389724,2.84083166087673,2.85563838278106,2.87044510468539,2.88525182658971,2.90005854849404,2.91486527039837,2.9296719923027,2.94447871420702,2.95928543611135,2.97409215801568,2.98889887992001,3.00370560182433,3.01851232372866,3.03331904563299,3.04812576753732,3.06293248944165,3.07773921134597,3.0925459332503,3.10735265515463,3.12215937705896,3.13696609896328,3.15177282086761,3.16657954277194,3.18138626467627,3.19619298658059,3.21099970848492,3.22580643038925,3.24061315229358,3.25541987419791,3.27022659610223,3.28503331800656,3.29984003991089,3.31464676181522,3.32945348371954],[2.60719435955908,2.62200108146341,2.63680780336773,2.65161452527206,2.66642124717639,2.68122796908072,2.69603469098505,2.71084141288937,2.7256481347937,2.74045485669803,2.75526157860236,2.77006830050668,2.78487502241101,2.79968174431534,2.81448846621967,2.82929518812399,2.84410191002832,2.85890863193265,2.87371535383698,2.88852207574131,2.90332879764563,2.91813551954996,2.93294224145429,2.94774896335862,2.96255568526294,2.97736240716727,2.9921691290716,3.00697585097593,3.02178257288025,3.03658929478458,3.05139601668891,3.06620273859324,3.08100946049757,3.09581618240189,3.11062290430622,3.12542962621055,3.14023634811488,3.1550430700192,3.16984979192353,3.18465651382786,3.19946323573219,3.21426995763651,3.22907667954084,3.24388340144517,3.2586901233495,3.27349684525383,3.28830356715815,3.30311028906248,3.31791701096681,3.33272373287114],[2.61046460871067,2.625271330615,2.64007805251933,2.65488477442366,2.66969149632798,2.68449821823231,2.69930494013664,2.71411166204097,2.72891838394529,2.74372510584962,2.75853182775395,2.77333854965828,2.7881452715626,2.80295199346693,2.81775871537126,2.83256543727559,2.84737215917992,2.86217888108424,2.87698560298857,2.8917923248929,2.90659904679723,2.92140576870155,2.93621249060588,2.95101921251021,2.96582593441454,2.98063265631886,2.99543937822319,3.01024610012752,3.02505282203185,3.03985954393618,3.0546662658405,3.06947298774483,3.08427970964916,3.09908643155349,3.11389315345781,3.12869987536214,3.14350659726647,3.1583133191708,3.17312004107512,3.18792676297945,3.20273348488378,3.21754020678811,3.23234692869244,3.24715365059676,3.26196037250109,3.27676709440542,3.29157381630975,3.30638053821407,3.3211872601184,3.33599398202273],[2.61373485786227,2.62854157976659,2.64334830167092,2.65815502357525,2.67296174547958,2.6877684673839,2.70257518928823,2.71738191119256,2.73218863309689,2.74699535500121,2.76180207690554,2.77660879880987,2.7914155207142,2.80622224261852,2.82102896452285,2.83583568642718,2.85064240833151,2.86544913023584,2.88025585214016,2.89506257404449,2.90986929594882,2.92467601785315,2.93948273975747,2.9542894616618,2.96909618356613,2.98390290547046,2.99870962737478,3.01351634927911,3.02832307118344,3.04312979308777,3.0579365149921,3.07274323689642,3.08754995880075,3.10235668070508,3.11716340260941,3.13197012451373,3.14677684641806,3.16158356832239,3.17639029022672,3.19119701213104,3.20600373403537,3.2208104559397,3.23561717784403,3.25042389974836,3.26523062165268,3.28003734355701,3.29484406546134,3.30965078736567,3.32445750926999,3.33926423117432],[2.61700510701386,2.63181182891819,2.64661855082251,2.66142527272684,2.67623199463117,2.6910387165355,2.70584543843982,2.72065216034415,2.73545888224848,2.75026560415281,2.76507232605713,2.77987904796146,2.79468576986579,2.80949249177012,2.82429921367444,2.83910593557877,2.8539126574831,2.86871937938743,2.88352610129176,2.89833282319608,2.91313954510041,2.92794626700474,2.94275298890907,2.95755971081339,2.97236643271772,2.98717315462205,3.00197987652638,3.01678659843071,3.03159332033503,3.04640004223936,3.06120676414369,3.07601348604802,3.09082020795234,3.10562692985667,3.120433651761,3.13524037366533,3.15004709556965,3.16485381747398,3.17966053937831,3.19446726128264,3.20927398318696,3.22408070509129,3.23888742699562,3.25369414889995,3.26850087080428,3.2833075927086,3.29811431461293,3.31292103651726,3.32772775842159,3.34253448032591],[2.62027535616545,2.63508207806978,2.64988879997411,2.66469552187843,2.67950224378276,2.69430896568709,2.70911568759142,2.72392240949574,2.73872913140007,2.7535358533044,2.76834257520873,2.78314929711305,2.79795601901738,2.81276274092171,2.82756946282604,2.84237618473037,2.85718290663469,2.87198962853902,2.88679635044335,2.90160307234768,2.916409794252,2.93121651615633,2.94602323806066,2.96082995996499,2.97563668186931,2.99044340377364,3.00525012567797,3.0200568475823,3.03486356948663,3.04967029139095,3.06447701329528,3.07928373519961,3.09409045710394,3.10889717900826,3.12370390091259,3.13851062281692,3.15331734472125,3.16812406662557,3.1829307885299,3.19773751043423,3.21254423233856,3.22735095424289,3.24215767614721,3.25696439805154,3.27177111995587,3.2865778418602,3.30138456376452,3.31619128566885,3.33099800757318,3.34580472947751],[2.62354560531704,2.63835232722137,2.6531590491257,2.66796577103003,2.68277249293435,2.69757921483868,2.71238593674301,2.72719265864734,2.74199938055166,2.75680610245599,2.77161282436032,2.78641954626465,2.80122626816897,2.8160329900733,2.83083971197763,2.84564643388196,2.86045315578629,2.87525987769061,2.89006659959494,2.90487332149927,2.9196800434036,2.93448676530792,2.94929348721225,2.96410020911658,2.97890693102091,2.99371365292523,3.00852037482956,3.02332709673389,3.03813381863822,3.05294054054255,3.06774726244687,3.0825539843512,3.09736070625553,3.11216742815986,3.12697415006418,3.14178087196851,3.15658759387284,3.17139431577717,3.18620103768149,3.20100775958582,3.21581448149015,3.23062120339448,3.24542792529881,3.26023464720313,3.27504136910746,3.28984809101179,3.30465481291612,3.31946153482044,3.33426825672477,3.3490749786291],[2.62681585446864,2.64162257637296,2.65642929827729,2.67123602018162,2.68604274208595,2.70084946399027,2.7156561858946,2.73046290779893,2.74526962970326,2.76007635160758,2.77488307351191,2.78968979541624,2.80449651732057,2.8193032392249,2.83410996112922,2.84891668303355,2.86372340493788,2.87853012684221,2.89333684874653,2.90814357065086,2.92295029255519,2.93775701445952,2.95256373636384,2.96737045826817,2.9821771801725,2.99698390207683,3.01179062398116,3.02659734588548,3.04140406778981,3.05621078969414,3.07101751159847,3.08582423350279,3.10063095540712,3.11543767731145,3.13024439921578,3.1450511211201,3.15985784302443,3.17466456492876,3.18947128683309,3.20427800873742,3.21908473064174,3.23389145254607,3.2486981744504,3.26350489635473,3.27831161825905,3.29311834016338,3.30792506206771,3.32273178397204,3.33753850587636,3.35234522778069],[2.63008610362023,2.64489282552456,2.65969954742888,2.67450626933321,2.68931299123754,2.70411971314187,2.71892643504619,2.73373315695052,2.74853987885485,2.76334660075918,2.7781533226635,2.79296004456783,2.80776676647216,2.82257348837649,2.83738021028081,2.85218693218514,2.86699365408947,2.8818003759938,2.89660709789813,2.91141381980245,2.92622054170678,2.94102726361111,2.95583398551544,2.97064070741976,2.98544742932409,3.00025415122842,3.01506087313275,3.02986759503708,3.0446743169414,3.05948103884573,3.07428776075006,3.08909448265439,3.10390120455871,3.11870792646304,3.13351464836737,3.1483213702717,3.16312809217602,3.17793481408035,3.19274153598468,3.20754825788901,3.22235497979334,3.23716170169766,3.25196842360199,3.26677514550632,3.28158186741065,3.29638858931497,3.3111953112193,3.32600203312363,3.34080875502796,3.35561547693228],[2.63335635277182,2.64816307467615,2.66296979658048,2.6777765184848,2.69258324038913,2.70738996229346,2.72219668419779,2.73700340610211,2.75181012800644,2.76661684991077,2.7814235718151,2.79623029371943,2.81103701562375,2.82584373752808,2.84065045943241,2.85545718133674,2.87026390324106,2.88507062514539,2.89987734704972,2.91468406895405,2.92949079085837,2.9442975127627,2.95910423466703,2.97391095657136,2.98871767847568,3.00352440038001,3.01833112228434,3.03313784418867,3.047944566093,3.06275128799732,3.07755800990165,3.09236473180598,3.10717145371031,3.12197817561463,3.13678489751896,3.15159161942329,3.16639834132762,3.18120506323194,3.19601178513627,3.2108185070406,3.22562522894493,3.24043195084926,3.25523867275358,3.27004539465791,3.28485211656224,3.29965883846657,3.31446556037089,3.32927228227522,3.34407900417955,3.35888572608388],[2.63662660192341,2.65143332382774,2.66624004573207,2.6810467676364,2.69585348954072,2.71066021144505,2.72546693334938,2.74027365525371,2.75508037715803,2.76988709906236,2.78469382096669,2.79950054287102,2.81430726477535,2.82911398667967,2.843920708584,2.85872743048833,2.87353415239266,2.88834087429698,2.90314759620131,2.91795431810564,2.93276104000997,2.9475677619143,2.96237448381862,2.97718120572295,2.99198792762728,3.00679464953161,3.02160137143593,3.03640809334026,3.05121481524459,3.06602153714892,3.08082825905324,3.09563498095757,3.1104417028619,3.12524842476623,3.14005514667055,3.15486186857488,3.16966859047921,3.18447531238354,3.19928203428787,3.21408875619219,3.22889547809652,3.24370220000085,3.25850892190518,3.2733156438095,3.28812236571383,3.30292908761816,3.31773580952249,3.33254253142681,3.34734925333114,3.36215597523547],[2.63989685107501,2.65470357297933,2.66951029488366,2.68431701678799,2.69912373869232,2.71393046059664,2.72873718250097,2.7435439044053,2.75835062630963,2.77315734821395,2.78796407011828,2.80277079202261,2.81757751392694,2.83238423583127,2.84719095773559,2.86199767963992,2.87680440154425,2.89161112344858,2.9064178453529,2.92122456725723,2.93603128916156,2.95083801106589,2.96564473297021,2.98045145487454,2.99525817677887,3.0100648986832,3.02487162058753,3.03967834249185,3.05448506439618,3.06929178630051,3.08409850820484,3.09890523010916,3.11371195201349,3.12851867391782,3.14332539582215,3.15813211772647,3.1729388396308,3.18774556153513,3.20255228343946,3.21735900534379,3.23216572724811,3.24697244915244,3.26177917105677,3.2765858929611,3.29139261486542,3.30619933676975,3.32100605867408,3.33581278057841,3.35061950248273,3.36542622438706],[2.6431671002266,2.65797382213093,2.67278054403525,2.68758726593958,2.70239398784391,2.71720070974824,2.73200743165256,2.74681415355689,2.76162087546122,2.77642759736555,2.79123431926988,2.8060410411742,2.82084776307853,2.83565448498286,2.85046120688719,2.86526792879151,2.88007465069584,2.89488137260017,2.9096880945045,2.92449481640882,2.93930153831315,2.95410826021748,2.96891498212181,2.98372170402614,2.99852842593046,3.01333514783479,3.02814186973912,3.04294859164345,3.05775531354777,3.0725620354521,3.08736875735643,3.10217547926076,3.11698220116508,3.13178892306941,3.14659564497374,3.16140236687807,3.1762090887824,3.19101581068672,3.20582253259105,3.22062925449538,3.23543597639971,3.25024269830403,3.26504942020836,3.27985614211269,3.29466286401702,3.30946958592134,3.32427630782567,3.33908302973,3.35388975163433,3.36869647353866],[2.64643734937819,2.66124407128252,2.67605079318685,2.69085751509117,2.7056642369955,2.72047095889983,2.73527768080416,2.75008440270848,2.76489112461281,2.77969784651714,2.79450456842147,2.8093112903258,2.82411801223012,2.83892473413445,2.85373145603878,2.86853817794311,2.88334489984743,2.89815162175176,2.91295834365609,2.92776506556042,2.94257178746474,2.95737850936907,2.9721852312734,2.98699195317773,3.00179867508206,3.01660539698638,3.03141211889071,3.04621884079504,3.06102556269937,3.07583228460369,3.09063900650802,3.10544572841235,3.12025245031668,3.135059172221,3.14986589412533,3.16467261602966,3.17947933793399,3.19428605983832,3.20909278174264,3.22389950364697,3.2387062255513,3.25351294745563,3.26831966935995,3.28312639126428,3.29793311316861,3.31273983507294,3.32754655697726,3.34235327888159,3.35716000078592,3.37196672269025],[2.64970759852978,2.66451432043411,2.67932104233844,2.69412776424277,2.70893448614709,2.72374120805142,2.73854792995575,2.75335465186008,2.7681613737644,2.78296809566873,2.79777481757306,2.81258153947739,2.82738826138172,2.84219498328604,2.85700170519037,2.8718084270947,2.88661514899903,2.90142187090335,2.91622859280768,2.93103531471201,2.94584203661634,2.96064875852067,2.97545548042499,2.99026220232932,3.00506892423365,3.01987564613798,3.0346823680423,3.04948908994663,3.06429581185096,3.07910253375529,3.09390925565961,3.10871597756394,3.12352269946827,3.1383294213726,3.15313614327692,3.16794286518125,3.18274958708558,3.19755630898991,3.21236303089424,3.22716975279856,3.24197647470289,3.25678319660722,3.27158991851155,3.28639664041587,3.3012033623202,3.31601008422453,3.33081680612886,3.34562352803318,3.36043024993751,3.37523697184184],[2.65297784768138,2.6677845695857,2.68259129149003,2.69739801339436,2.71220473529869,2.72701145720301,2.74181817910734,2.75662490101167,2.771431622916,2.78623834482033,2.80104506672465,2.81585178862898,2.83065851053331,2.84546523243764,2.86027195434196,2.87507867624629,2.88988539815062,2.90469212005495,2.91949884195927,2.9343055638636,2.94911228576793,2.96391900767226,2.97872572957659,2.99353245148091,3.00833917338524,3.02314589528957,3.0379526171939,3.05275933909822,3.06756606100255,3.08237278290688,3.09717950481121,3.11198622671553,3.12679294861986,3.14159967052419,3.15640639242852,3.17121311433285,3.18601983623717,3.2008265581415,3.21563328004583,3.23044000195016,3.24524672385448,3.26005344575881,3.27486016766314,3.28966688956747,3.30447361147179,3.31928033337612,3.33408705528045,3.34889377718478,3.36370049908911,3.37850722099343],[2.65624809683297,2.6710548187373,2.68586154064162,2.70066826254595,2.71547498445028,2.73028170635461,2.74508842825893,2.75989515016326,2.77470187206759,2.78950859397192,2.80431531587625,2.81912203778057,2.8339287596849,2.84873548158923,2.86354220349356,2.87834892539788,2.89315564730221,2.90796236920654,2.92276909111087,2.93757581301519,2.95238253491952,2.96718925682385,2.98199597872818,2.99680270063251,3.01160942253683,3.02641614444116,3.04122286634549,3.05602958824982,3.07083631015414,3.08564303205847,3.1004497539628,3.11525647586713,3.13006319777146,3.14486991967578,3.15967664158011,3.17448336348444,3.18929008538877,3.20409680729309,3.21890352919742,3.23371025110175,3.24851697300608,3.2633236949104,3.27813041681473,3.29293713871906,3.30774386062339,3.32255058252771,3.33735730443204,3.35216402633637,3.3669707482407,3.38177747014503],[2.65951834598456,2.67432506788889,2.68913178979322,2.70393851169754,2.71874523360187,2.7335519555062,2.74835867741053,2.76316539931486,2.77797212121918,2.79277884312351,2.80758556502784,2.82239228693217,2.83719900883649,2.85200573074082,2.86681245264515,2.88161917454948,2.8964258964538,2.91123261835813,2.92603934026246,2.94084606216679,2.95565278407111,2.97045950597544,2.98526622787977,3.0000729497841,3.01487967168843,3.02968639359275,3.04449311549708,3.05929983740141,3.07410655930574,3.08891328121006,3.10372000311439,3.11852672501872,3.13333344692305,3.14814016882738,3.1629468907317,3.17775361263603,3.19256033454036,3.20736705644469,3.22217377834901,3.23698050025334,3.25178722215767,3.266593944062,3.28140066596632,3.29620738787065,3.31101410977498,3.32582083167931,3.34062755358364,3.35543427548796,3.37024099739229,3.38504771929662],[2.66278859513615,2.67759531704048,2.69240203894481,2.70720876084914,2.72201548275346,2.73682220465779,2.75162892656212,2.76643564846645,2.78124237037078,2.7960490922751,2.81085581417943,2.82566253608376,2.84046925798809,2.85527597989241,2.87008270179674,2.88488942370107,2.8996961456054,2.91450286750972,2.92930958941405,2.94411631131838,2.95892303322271,2.97372975512704,2.98853647703136,3.00334319893569,3.01814992084002,3.03295664274435,3.04776336464867,3.062570086553,3.07737680845733,3.09218353036166,3.10699025226598,3.12179697417031,3.13660369607464,3.15141041797897,3.1662171398833,3.18102386178762,3.19583058369195,3.21063730559628,3.22544402750061,3.24025074940493,3.25505747130926,3.26986419321359,3.28467091511792,3.29947763702224,3.31428435892657,3.3290910808309,3.34389780273523,3.35870452463956,3.37351124654388,3.38831796844821],[2.66605884428775,2.68086556619207,2.6956722880964,2.71047901000073,2.72528573190506,2.74009245380938,2.75489917571371,2.76970589761804,2.78451261952237,2.7993193414267,2.81412606333102,2.82893278523535,2.84373950713968,2.85854622904401,2.87335295094833,2.88815967285266,2.90296639475699,2.91777311666132,2.93257983856564,2.94738656046997,2.9621932823743,2.97700000427863,2.99180672618296,3.00661344808728,3.02142016999161,3.03622689189594,3.05103361380027,3.06584033570459,3.08064705760892,3.09545377951325,3.11026050141758,3.12506722332191,3.13987394522623,3.15468066713056,3.16948738903489,3.18429411093922,3.19910083284354,3.21390755474787,3.2287142766522,3.24352099855653,3.25832772046085,3.27313444236518,3.28794116426951,3.30274788617384,3.31755460807817,3.33236132998249,3.34716805188682,3.36197477379115,3.37678149569548,3.3915882175998],[2.66932909343934,2.68413581534367,2.69894253724799,2.71374925915232,2.72855598105665,2.74336270296098,2.75816942486531,2.77297614676963,2.78778286867396,2.80258959057829,2.81739631248262,2.83220303438694,2.84700975629127,2.8618164781956,2.87662320009993,2.89142992200425,2.90623664390858,2.92104336581291,2.93585008771724,2.95065680962156,2.96546353152589,2.98027025343022,2.99507697533455,3.00988369723888,3.0246904191432,3.03949714104753,3.05430386295186,3.06911058485619,3.08391730676051,3.09872402866484,3.11353075056917,3.1283374724735,3.14314419437783,3.15795091628215,3.17275763818648,3.18756436009081,3.20237108199514,3.21717780389946,3.23198452580379,3.24679124770812,3.26159796961245,3.27640469151677,3.2912114134211,3.30601813532543,3.32082485722976,3.33563157913408,3.35043830103841,3.36524502294274,3.38005174484707,3.3948584667514],[2.67259934259093,2.68740606449526,2.70221278639959,2.71701950830391,2.73182623020824,2.74663295211257,2.7614396740169,2.77624639592123,2.79105311782555,2.80585983972988,2.82066656163421,2.83547328353854,2.85028000544286,2.86508672734719,2.87989344925152,2.89470017115585,2.90950689306018,2.9243136149645,2.93912033686883,2.95392705877316,2.96873378067749,2.98354050258181,2.99834722448614,3.01315394639047,3.0279606682948,3.04276739019912,3.05757411210345,3.07238083400778,3.08718755591211,3.10199427781643,3.11680099972076,3.13160772162509,3.14641444352942,3.16122116543375,3.17602788733807,3.1908346092424,3.20564133114673,3.22044805305106,3.23525477495538,3.25006149685971,3.26486821876404,3.27967494066837,3.2944816625727,3.30928838447702,3.32409510638135,3.33890182828568,3.35370855019001,3.36851527209433,3.38332199399866,3.39812871590299],[2.67586959174252,2.69067631364685,2.70548303555118,2.72028975745551,2.73509647935984,2.74990320126416,2.76470992316849,2.77951664507282,2.79432336697715,2.80913008888147,2.8239368107858,2.83874353269013,2.85355025459446,2.86835697649878,2.88316369840311,2.89797042030744,2.91277714221177,2.9275838641161,2.94239058602042,2.95719730792475,2.97200402982908,2.98681075173341,3.00161747363773,3.01642419554206,3.03123091744639,3.04603763935072,3.06084436125504,3.07565108315937,3.0904578050637,3.10526452696803,3.12007124887236,3.13487797077668,3.14968469268101,3.16449141458534,3.17929813648967,3.19410485839399,3.20891158029832,3.22371830220265,3.23852502410698,3.2533317460113,3.26813846791563,3.28294518981996,3.29775191172429,3.31255863362862,3.32736535553294,3.34217207743727,3.3569787993416,3.37178552124593,3.38659224315025,3.40139896505458],[2.67913984089412,2.69394656279844,2.70875328470277,2.7235600066071,2.73836672851143,2.75317345041576,2.76798017232008,2.78278689422441,2.79759361612874,2.81240033803307,2.82720705993739,2.84201378184172,2.85682050374605,2.87162722565038,2.8864339475547,2.90124066945903,2.91604739136336,2.93085411326769,2.94566083517202,2.96046755707634,2.97527427898067,2.990081000885,3.00488772278933,3.01969444469365,3.03450116659798,3.04930788850231,3.06411461040664,3.07892133231096,3.09372805421529,3.10853477611962,3.12334149802395,3.13814821992828,3.1529549418326,3.16776166373693,3.18256838564126,3.19737510754559,3.21218182944991,3.22698855135424,3.24179527325857,3.2566019951629,3.27140871706722,3.28621543897155,3.30102216087588,3.31582888278021,3.33063560468454,3.34544232658886,3.36024904849319,3.37505577039752,3.38986249230185,3.40466921420617],[2.68241009004571,2.69721681195004,2.71202353385437,2.72683025575869,2.74163697766302,2.75644369956735,2.77125042147168,2.786057143376,2.80086386528033,2.81567058718466,2.83047730908899,2.84528403099331,2.86009075289764,2.87489747480197,2.8897041967063,2.90451091861063,2.91931764051495,2.93412436241928,2.94893108432361,2.96373780622794,2.97854452813226,2.99335125003659,3.00815797194092,3.02296469384525,3.03777141574957,3.0525781376539,3.06738485955823,3.08219158146256,3.09699830336689,3.11180502527121,3.12661174717554,3.14141846907987,3.1562251909842,3.17103191288852,3.18583863479285,3.20064535669718,3.21545207860151,3.23025880050583,3.24506552241016,3.25987224431449,3.27467896621882,3.28948568812314,3.30429241002747,3.3190991319318,3.33390585383613,3.34871257574046,3.36351929764478,3.37832601954911,3.39313274145344,3.40793946335777],[2.6856803391973,2.70048706110163,2.71529378300596,2.73010050491028,2.74490722681461,2.75971394871894,2.77452067062327,2.7893273925276,2.80413411443192,2.81894083633625,2.83374755824058,2.84855428014491,2.86336100204923,2.87816772395356,2.89297444585789,2.90778116776222,2.92258788966655,2.93739461157087,2.9522013334752,2.96700805537953,2.98181477728386,2.99662149918818,3.01142822109251,3.02623494299684,3.04104166490117,3.05584838680549,3.07065510870982,3.08546183061415,3.10026855251848,3.1150752744228,3.12988199632713,3.14468871823146,3.15949544013579,3.17430216204012,3.18910888394444,3.20391560584877,3.2187223277531,3.23352904965743,3.24833577156175,3.26314249346608,3.27794921537041,3.29275593727474,3.30756265917907,3.32236938108339,3.33717610298772,3.35198282489205,3.36678954679638,3.3815962687007,3.39640299060503,3.41120971250936]],"type":"surface","frame":null},{"x":[3,3.20000004768372,3.59999990463257,3.5,3.90000009536743,3.40000009536743,3.5,3,3,4,3,3.09999990463257,3.5,3.79999995231628,3.70000004768372,3,3.5,3,3,3.5,3.5,3,3.59999990463257,4,3.59999990463257,3.29999995231628,3.59999990463257,3.09999990463257,3.40000009536743,3.70000004768372,3.70000004768372,3.29999995231628,3.29999995231628,3.5,3.20000004768372,3.29999995231628,3.40000009536743,3.5,3.40000009536743,3.70000004768372,2.5,3.70000004768372,3,3,4,3.79999995231628,3,3.70000004768372,3.40000009536743,2.40000009536743,3.79999995231628,4,3.5,3.40000009536743,3.59999990463257,3.20000004768372,3.79999995231628,3.29999995231628,3.40000009536743,3,3.59999990463257,3.90000009536743,3,3,3.29999995231628,3.29999995231628,3.20000004768372,3.40000009536743,3.70000004768372,3.40000009536743,3.90000009536743,3.59999990463257,4,3.59999990463257,3,2.79999995231628,3.20000004768372,2.90000009536743,2.90000009536743,3.59999990463257,3.40000009536743,3.59999990463257,3.20000004768372,3.20000004768372,3.20000004768372,3.70000004768372,2.90000009536743,3.29999995231628,3.09999990463257,3.5,3.5,3.70000004768372,3,3.79999995231628,3.29999995231628,3.59999990463257,3.20000004768372,3.59999990463257,3.5,3.70000004768372,2.70000004768372,3.09999990463257,3.40000009536743,3.29999995231628,3.40000009536743,3.5,3.90000009536743,3.5,4,2.90000009536743,3.29999995231628,3.5,3.5,3.09999990463257,3.09999990463257,3.70000004768372,3.29999995231628,3.70000004768372,3,3.79999995231628,3.5,3.59999990463257,3.5,3,3.79999995231628,3.5,3.59999990463257,3.79999995231628,3.59999990463257,3.29999995231628,3.20000004768372,3.29999995231628,3.59999990463257,3.79999995231628,3.29999995231628,3.20000004768372,3.29999995231628,3.59999990463257,3.40000009536743,3.70000004768372,3.29999995231628],"y":[21,24,26,27,28,25,25,22,21,27,19,22,23,29,25,21,29,23,21,29,25,23,27,25,33,24,27,20,21,24,20,23,22,24,28,25,23,24,26,23,26,23,23,19,26,26,21,24,24,24,21,25,21,27,19,27,28,24,27,24,27,26,19,24,26,28,22,27,26,26,30,24,26,21,24,24,23,26,24,24,27,23,31,24,16,27,22,23,24,24,23,23,23,25,21,22,24,27,29,24,25,23,22,24,23,26,26,22,26,28,24,24,23,16,21,30,23,23,23,22,22,25,27,19,23,26,22,24,26,23,21,22,26,30,22,19,23,25,21,26,28],"z":[3,3.40000009536743,3,3.5,3.59999990463257,3,2.70000004768372,2.70000004768372,2.70000004768372,3.79999995231628,2.79999995231628,2.90000009536743,3,2.90000009536743,3.29999995231628,2.59999990463257,2.5,2.5,2.40000009536743,3.59999990463257,2.59999990463257,2.70000004768372,2.90000009536743,3,3.29999995231628,3.09999990463257,3,3.20000004768372,3,3.40000009536743,2.90000009536743,3.5,3.70000004768372,3.5,2.79999995231628,2.5,3.09999990463257,3.5,3.40000009536743,3.5,2.59999990463257,2.79999995231628,2.59999990463257,3.5,4,3.79999995231628,2.79999995231628,3.5,3,2.59999990463257,3,3.70000004768372,3,2.90000009536743,2.59999990463257,3,3.29999995231628,2.70000004768372,3,3.20000004768372,2.70000004768372,3.59999990463257,2.40000009536743,2.90000009536743,3.29999995231628,3.5,3,3,2.79999995231628,2.90000009536743,3.79999995231628,2.5,3,3.20000004768372,2.20000004768372,3.40000009536743,2.90000009536743,3.70000004768372,2.90000009536743,2.79999995231628,3.20000004768372,3.40000009536743,3,2.5,3.5,3.09999990463257,2.79999995231628,2.90000009536743,2.90000009536743,3.40000009536743,3.40000009536743,3.59999990463257,3.20000004768372,3.20000004768372,2.79999995231628,3.09999990463257,2.79999995231628,3.40000009536743,2.70000004768372,3,2.5,2.5,2.70000004768372,3.59999990463257,2.90000009536743,2.79999995231628,3.90000009536743,2.79999995231628,3.90000009536743,3.20000004768372,3.29999995231628,3.29999995231628,3.20000004768372,3.09999990463257,3,3.40000009536743,3.09999990463257,3.20000004768372,3.29999995231628,3,2.79999995231628,2.79999995231628,2.70000004768372,2.59999990463257,2.90000009536743,3,3,2.90000009536743,3.29999995231628,2.70000004768372,3,2.90000009536743,3.79999995231628,2.90000009536743,3,3.20000004768372,3,2.29999995231628,2.79999995231628,3.40000009536743,2.79999995231628],"type":"scatter3d","mode":"markers","opacity":0.5,"marker":{"color":"rgba(255,127,14,1)","line":{"color":"rgba(255,127,14,1)"}},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"line":{"color":"rgba(255,127,14,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>

Üç boyutlu grafiğimiz olduğu için artık üzerine gidip sağa sola çevirebilirsiniz. Tahmin edebileceğiniz gibi üç boyutlu grafikleri algılamamız daha büyük boyutlu grafiklerden daha kolay. Şimdi bu noktalarda oluşacak hata payını minimize edecek bir düzleme ihtiyacımız var. Bunun için çoklu regresyonumuzdan yardım alacağız.

Sizin şimdilik bu grafikleri çizerken kullandığımız kodları anlamanıza gerek yok. Sadece grafiklerin şekline odaklanın. Bu grafik bize yapmış olduğumuz minimizasyon işleminin neden basit regresyona bir değişken daha eklediğimizde farklılaştığı ve ek değişkenin toplamda neden daha çok varyasyon açıklamaya yardım ettiği hakkında daha fazla bir içgüdü sunabilir.

## Regresyon Tahmin Değerleri ve Hata Payı (OLS Fitted Values and Residuals)

Kitabınızdaki bu bölümde çoklu regresyonda tahmin değerleri ve hata payı üzerinde duruluyor. Tahmin değerlerini şapkayla (hat) gösteriyorduk.

$$
\hat{y_i}= \hat{\beta_0} + \hat{\beta_1} x_{i1} + \hat{\beta_2} x_{i2}  + \hat{\beta_3} x_{i3} + ... + \hat{\beta_k} x_{ik} 
$$
Gerçek popülasyon modelimiz ise bu şekilde gösteriliyordu.

$$
y_i= \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2}  + \beta_3 x_{i3} + ... + \beta_k x_{ik} + u_i
$$
Normalde, bir $i$ gözlemi için gerçek değer $y_i$ ve tahmin edilen $\hat{y_i}$ birbirine eşit olmaz. Biz ancak bu hata payını minimize eden en küçük kareler yöntemini kullanarak doğrusal regresyon tahminlerini kullanabiliriz. Bu durumda her bir gözlem için hata payını şu şekilde tahmin edebiliriz.

$$
y_i-\hat{y_i}=\hat{u_i}
$$

## Çoklu regresyon tahmin değerleri ve hata payının özellikleri.

1.  Hata payının örnek ortalaması sıfırdır, bu yüzden $\bar{\hat{y}}=\bar{y}$ olur.
2.  Hata payının herbir bağımsız değişkenle örnek kovaryası sıfırdır. Bu yüzden çoklu regresyon tahmin değerleri ve hata payı arasında örnek kovaryans da sıfırdır.
3.  Bütün bağımsız değişkenlerin ve bağımlı değişkenin ortalamaları regresyon çizgisi üzerindedir.

$$
 \bar{y}= \hat{\beta_0} + \hat{\beta_1} \bar{x_1} + \hat{\beta_2} \bar{x_2} + \hat{\beta_3} \bar{x_3} + ... + \hat{\beta_k} \bar{x_k} 
$$

## Çoklu Regresyon Modeli (Multiple Linear Regression (MLR) Model) Varsayımları

-   Birinci Varsayım (MLR.1): Parametrelerde doğrusaldır.

$$
y= \beta_0 + \beta_1 x_{1} + \beta_2 x_{2}  + \beta_3 x_{3} + ... + \beta_k x_{k} + u
$$
$\beta$ terimleri doğrusaldır ancak $x$ terimlerinin doğrusal olmasına gerek yoktur. Çoğu zaman $x$ terimlerinin logaritması alınabilir veya $x^2$ gibi fonksiyonal formları kullanılabilir.

-   İkinci Varsayım (MLR.2): Rastgele Örnekleme.

Rastgele n örnek gözlemimiz var.

-   Üçüncü Varsayım (MLR.3): Mükemmel bir eş doğrusallık yoktur.

Örneklemde (ve dolayısıyla popülasyonda), bağımsız değişkenlerin hiçbiri sabit değildir ve bağımsız değişkenler arasında kesin doğrusal ilişkiler yoktur.

-   Dördüncü Varsayım (MLR.4): Sıfır koşullu ortalama.

Modelde bulunan bağımısız değişkenlerin herhangi bir değeri için hata payı $u$’nun koşullu beklenen değeri sıfırdır. $E(u | x_1, x_2, ..., x_k) = 0$

## Gözlemlenemeyen Değişken Sapması (Omitted Variable Bias)

Gerçek popülasyon modelinde bulunan bir değişkeni modelimize eklememek gözlenemeyen değişken sapmasına yol açabilir. Bu sapmayı kitabınızda verilen örnek üzerinden inceleyeceğiz.

Varsayalım ki maaşları açıklayabilen sadece iki değişkene ihtiyacımız var. Bunlar eğitim ve yetenek. O zaman gerçek popülasyon modelimiz şu şekilde olur.

$$
maaş = \beta_0 + \beta_1 eğitim + \beta_2 yetenek + u
$$

Bu modelin bütün çoklu regresyon varsayımlarını (MLR1-MLR4) sağladığını varsayalım. Şimdi yeteneği gözlemleyemediğinizi varsayalım ve sadece, eğitim ve maaş verilerine sahip olduğunuzu düşünün. Sadece basit regresyon modelini kullanabilirsiniz ve $\beta$ katsayılarını tahmin edebilirsiniz. Burda gerçek modeli kullanamadığınız için bu regresyon modelinden elde ettiğimiz tahminleri tilda $\sim$ ile gösterelim.

$$
maaş = \beta_0 + \beta_1 eğitim  + v
$$

$$
\tilde{maaş} = \tilde{\beta_0} + \tilde{\beta_1} eğitim 
$$
$v$ hata payı, yetenek gözlenemediği için şu şekilde yazılabilir: $v=\beta_2 yetenek + u$

Eğer $yetenek$ gözlemlenebilseydi şu şekilde tahmin edebilirdik.

$$
\hat{maaş} = \hat{\beta_0} + \hat{\beta_1} eğitim + \hat{\beta_2} yetenek
$$
$\hat{\beta_1}$ tahmincisi yetenek değişkenini sabit tutarak bir birim eğitim değişimin maaşı kaç birim değiştireceğini göstermektedir. $\tilde{\beta_1}$ ise bir birim eğitim değişimin maaşı kaç birim değiştireceğini gösterir ancak yetenek değişkenini sabit tutmaz.

Burdan $\tilde{\beta_1}$ sapması şu şekide gösterilebilir

$$
\tilde{\beta_1}= \hat{\beta_1} + \hat{\beta_2} \tilde{\delta_1}
$$
$\tilde{\delta_1}$ yeteneğin eğitim üzerindeki basit regresyonunun eğim parametresidir.

$$
\tilde{eğitim} = \tilde{\delta_0} + \tilde{\delta_1} yetenek 
$$
Eğitim yetenek arttığı için artacağından, yeteneği modele katmamak $\tilde{\beta_1}$ tahmininin o kadar artmasına yol açar.

Şimdi bu hesaplamamızı bir örnek üzerinden gösterelim. Bu örneği hatırlarsak

``` r
##install.packages("stargazer")
library(stargazer)
stargazer(list(coklureg,basitreg),type = "text")
```

    ## 
    ## =================================================================
    ##                                  Dependent variable:             
    ##                     ---------------------------------------------
    ##                                        colGPA                    
    ##                               (1)                    (2)         
    ## -----------------------------------------------------------------
    ## hsGPA                      0.453***                              
    ##                             (0.096)                              
    ##                                                                  
    ## ACT                          0.009                 0.027**       
    ##                             (0.011)                (0.011)       
    ##                                                                  
    ## Constant                   1.286***               2.403***       
    ##                             (0.341)                (0.264)       
    ##                                                                  
    ## -----------------------------------------------------------------
    ## Observations                  141                    141         
    ## R2                           0.176                  0.043        
    ## Adjusted R2                  0.164                  0.036        
    ## Residual Std. Error    0.340 (df = 138)       0.366 (df = 139)   
    ## F Statistic         14.781*** (df = 2; 138) 6.207** (df = 1; 139)
    ## =================================================================
    ## Note:                                 *p<0.1; **p<0.05; ***p<0.01

Çoklu regresyon modeli şu şekilde yazılabilir

$$
colGPA = \beta_0 + \beta_1 ACT + \beta_2 hsGPA + u
$$
Çoklu regresyonun sonuçları şu şekilde rapor edilebilir

$$
colGPA = 1.286 + 0.009 ACT + 0.453 hsGPA
$$
Basit regresyon modeli

$$
colGPA = \beta_0 + \beta_1 ACT  + v
$$
Basit regresyon modeli sonuçları

$$
colGPA = 2.403 + 0.027 ACT
$$
Bu sonuçlar sapmalı sonuçlar olduğu için $\sim$ işaretiyle gösterelim

$$
\tilde{colGPA} = \tilde{\beta_0} + \tilde{\beta_1} ACT 
$$

Çoklu regresyon modelimiz gerçeğe daha yakın bir model olduğundan tahminleri şapkayla gösteriyoruz.

$$
\hat{colGPA} = \hat{\beta_0} + \hat{\beta_1} ACT + \hat{\beta_2} hsGPA
$$
Sapmalı tahminleri bu formülle gösteriyorduk

$$
\tilde{\beta_1}= \hat{\beta_1} + \hat{\beta_2} \tilde{\delta_1}
$$
Bütün bildiğimiz değerleri yerine koyarsak

$$
0.027= 0.009 + 0.453 \tilde{\delta_1}
$$
Önce işlemle sonra basit regresyonla sapmayı $\tilde{\delta_1}$ bulalım.

$$
0.027= 0.009 + 0.453 \tilde{\delta_1}\\
\tilde{\delta_1}= \frac{(0.027-0.009)}{0.453}=0.0397
$$
$\tilde{\delta_1}$ iki bağımsız değişkenin birbirleri arasındaki basit regresyon ilişkisinden de bulunabilir

$$
\tilde{ACT} = \tilde{\delta_0} + \tilde{\delta_1} hsGPA 
$$

``` r
sapmareg<-lm(hsGPA~ACT,data = gpa1)
stargazer(list(sapmareg),type = "text")
```

    ## 
    ## ===============================================
    ##                         Dependent variable:    
    ##                     ---------------------------
    ##                                hsGPA           
    ## -----------------------------------------------
    ## ACT                          0.039***          
    ##                               (0.009)          
    ##                                                
    ## Constant                     2.463***          
    ##                               (0.218)          
    ##                                                
    ## -----------------------------------------------
    ## Observations                    141            
    ## R2                             0.120           
    ## Adjusted R2                    0.113           
    ## Residual Std. Error      0.301 (df = 139)      
    ## F Statistic           18.879*** (df = 1; 139)  
    ## ===============================================
    ## Note:               *p<0.1; **p<0.05; ***p<0.01

Regresyon sonucuyla bulduğumuz ve hesapladığımız $\tilde{\delta_1}$ aynı olduğuna dikkat edin. Basit regresyon yaptığımızda gözlemleyemediğimiz değişken yüzünden olan sapma $\hat{\beta_2} \tilde{\delta_1}=0.453 \cdot 0.0397=0.017$ olur. Bu fark $\tilde{\beta_1}-\hat{\beta_1}$ arasındaki farka eşittir.

## Çoklu regresyon (En küçük kareler (OLS)) tahmincilerinin varyansı

### Homoskedastisite (Eş varyanslık), Çoklu eşdoğrusallık (Multicollinearity) ve Varyans enflasyon faktörü (Variance inflation factor (VIF))

Çoklu regresyonun 5. varsayımını hatırlayalım.

Beşinci Varsayım (MLR.5): Hata terimi $u$ açıklayıcı değişkenlerin her bir değeri için aynı varyansa sahiptir.

MLR.1 ila MLR.5 arasındaki varsayımlar topluca Gauss-Markov varsayımları olarak bilinir (kesitsel regresyon için).

Bir eğimin varyansını hesaplamak için şu formül kullanılabilir.

$$
var(\hat{\beta_j})=\frac{\sigma^2}{SST_j(1-R_j^2)}
$$
$SST_j$’yi hatırlarsak

$$
SST_j = \sum{(x_{ji}-\bar{x_j})^2}=(n-1)(var(x_j))
$$
Bu durumda $var(\hat{\beta_j})$’yi üç parça halinde yazabiliriz.

$$
var(\hat{\beta_j})=\frac{1}{n}\cdot\frac{\sigma^2}{var(x_j)}\cdot\frac{1}{1-R_j^2}
$$

Bu formülle birlikte şu çıkarımları yapabiliriz.

-   $\frac{1}{n}$ bize n yani gözlem sayısı arttıkça eğimin varyansının azalacağını söyler.
-   $\sigma^2$ bize hata teriminin çok fazla değişiklik gösterdiğinde, $\beta$ varyansının artacağını söyler.
-   $\frac{1}{var(x_j)}$ bize $x_j$’nin varyansı arttıkça $\beta$ varyansının azalacağını söyler. Bunun nedeni $x_j$’in bu sayede konuyla ilgili daha ilişkili bilgiler sağlayabilecek olmasıdır.
-   $\frac{1}{1-R_j^2}$ varyans enflasyon faktörü (Variance inflation factor (VIF)) olarak adlandırılır ve çoklu eşdoğrusallık (Multicollinearity) ölçer. Eğer $x_j$ bağımlı değişkeni diğer regresörlerle çok ilişkiliyse (korelasyon yüksekse) bu $R_j^2$’yi arttırır. $R_j^2$ bire yaklaştıkça $\frac{1}{1-R_j^2}$ paydası sıfıra yaklaşır ve $\frac{1}{1-R_j^2}$ sonsuza yaklaşır. Dolayısıyla $\beta_j$’in varyası çok fazla artar.

Örneğimizi kullanarak bu parçaları çıkaralım.

``` r
standarthata<-summary(coklureg)$sigma
standarthata
```

    ## [1] 0.3403158

Standart hatayi hesaplamak için sadece sigma komutunu kullanıyoruz. Standart hatayi colGPA örneği için 0.34 olarak hesapladık. $\sigma^2$ yani standart hatanın karesi bize regresyonumuzun hata payının varyansını verecektir.

``` r
sigmakare<-standarthata^2
sigmakare
```

    ## [1] 0.1158148

Regresörlerimiz arasındaki $R_j^2$ hesaplamak için daha önce hesapladığımız sapmareg’i kullanabiliriz. Bu $R_j^2$ bizim için lise not ortalamasıyla ACT sonuçları arasındaki ilişkiyi gösterecektir. Eğer $R_j^2$ bir’e yakınsa çoklu eş doğrusallık muhtemel olabilir.

``` r
Rjkare<-summary(sapmareg)$r.squared
Rjkare
```

    ## [1] 0.1195815

İki bağımsız değişkenimizin basit regresyonundan elde ettiğimiz $R_j^2$ yaklaşık olarak yüzde 12’dir.

$\frac{1}{1-R_j^2}$ varyans enflasyon faktörü (Variance inflation factor (VIF))’i hesaplayalım.

``` r
VIF<-1/(1-Rjkare)
VIF
```

    ## [1] 1.135823

son olarak n’i bulmalıyız.

``` r
n<-nobs(coklureg)
n
```

    ## [1] 141

son olarak $var(x_j)$’yi bulmamız lazım.

``` r
varxj<-var(gpa1$hsGPA)*(n-1)/n
varxj
```

    ## [1] 0.1016267

Şimdi formülümüzü kullanarak $var(\hat{\beta_j})$’yi hesaplayabiliriz.

$$
var(\hat{\beta_j})=\frac{1}{n}\cdot\frac{\sigma^2}{var(x_j)}\cdot\frac{1}{1-R_j^2}
$$

``` r
varbetaj<-(1/n)*(sigmakare/varxj)*VIF
varbetaj
```

    ## [1] 0.009180115

$\beta_j$’nin standart hatası $var(\hat{\beta_j})$’nin karaköküdür.

``` r
sdbetaj<-varbetaj^0.5
sdbetaj
```

    ## [1] 0.09581292

Tablodan hsGPA’in standart hatasına bakarsanız bulduğumuz rakamla aynı olduğunu göreceksiniz.

VIF’i bulmanın kolay bir yolu car paketini yüklemektir.

``` r
require(car)
vif(coklureg)
```

    ##    hsGPA      ACT 
    ## 1.135823 1.135823

require komutu paket yükleme komutu (install.packages) ve library komutunun ortak komutu olarak düşünülebilir. Eğer bir paketi daha önce yükleyip yüklemediğinizi hatırlamıyorsanız. require paket yüklenmemişse yükleyecek ve library() yapacaktır. Eğer daha önceden yüklüyse sadece library() yapacaktır. vif() komutu VIF’i regresyonunuz için otomatik olarak hesaplar. 1.1358’in bizim daha önce hesapladığımız VIF değeriyle aynı olduğuna dikkat edin.
